add place model
Studio-Yandex-Practicum/Lubimovka_backend pull request #10
Opened 2021-09-24 11:02 UTC by DRAGANmik

Добавил модель "Place" - площадка, в приложение инфо.

2021-09-24 14:15 UTC, AntonZelinsky requested changes

2021-09-24 14:15 UTC, AntonZelinsky commented on apps/info/views.py
> +class PlaceAPIView(generics.ListAPIView):
Площадки будут отдаваться пользователю на главную станицу в рамках одного запроса, который загрузит все данные сразу. Делать дополнительно эндпоинт пока не нужно

2021-09-24 14:37 UTC, DRAGANmik commented on apps/info/views.py
> +class PlaceAPIView(generics.ListAPIView):
Убрал

2021-09-25 17:15 UTC, raikhert13 commented on apps/info/models.py
> +class Place(BaseModel):
Нам бы определить единый стиль кода:
```
    first_name = models.CharField(
        max_length=200,
        verbose_name="Имя",
    )
    last_name = models.CharField(
        max_length=200,
        verbose_name="Фамилия",
    )
    birthday = models.DateField(
        verbose_name="День рождения",
    )
```
Насчет стиля это только предложение.

2021-09-25 20:58 UTC, AntonZelinsky commented on apps/info/models.py
> +class Place(BaseModel):
Хорошее предложение. Нужно посмотреть рекомендации в разных гайдлайнах, определить и прописать в ридми этот стандарт как правило.

2021-09-26 01:12 UTC, nkiryanov requested changes
Уникальность в Meta лучше убрать (если не накосячил я сам где :))

2021-09-26 01:12 UTC, nkiryanov commented on apps/info/models.py
> +    def clean(self):
А для чего этот метод? Нам нужно проверить уникальность place? Тогда это правильней в constraints вынести в Meta. Там и ValidataionError будет возвращаться ок.

2021-09-26 01:12 UTC, nkiryanov commented on apps/info/urls.py
> +#
Предлагаю убрать закоменченный код.

2021-09-26 01:12 UTC, nkiryanov commented on apps/info/urls.py
> +from apps.info.views import PlaceAPIView  # , QuestionsAPIView, PartnersAPIView
Предлагаю закоменченный код не включать в PR

2021-09-26 10:12 UTC, DRAGANmik commented on apps/info/urls.py
> +#
это из прошлого коммита наверное

2021-09-26 10:18 UTC, DRAGANmik commented on apps/info/models.py
> +    def clean(self):
Убрал

2021-09-26 10:21 UTC, DRAGANmik commented on apps/info/models.py
> +class Place(BaseModel):
Пока что оставлю как есть

2021-09-26 10:22 UTC, DRAGANmik commented on apps/info/urls.py
> +from apps.info.views import PlaceAPIView  # , QuestionsAPIView, PartnersAPIView
Это прошлый коммит, я это все убрал в последнем

2021-09-26 10:41 UTC, nkiryanov requested changes
Почти 👍 
Ещё чуть-чуть

2021-09-26 10:41 UTC, nkiryanov commented on apps/info/models.py
> +        unique_together = (("name", "city"),)
Блин, это устаревшая сущность. Она пока поддерживается, но в документашке неоднозначная рекомендация

https://docs.djangoproject.com/en/3.2/ref/models/options/#unique-together

2021-09-26 11:08 UTC, nkiryanov approved these changes
👍

2021-09-26 20:48 UTC, nkiryanov commented
@AntonZelinsky по-моем нужно твоё подтверждение чтоб смерджить PR.
У меня показывается что 1 change requested от твоего имени. Поменять сам не могу (только если "dismiss review" сделать, но это вроде не по фэншую)
<img width="927" alt="Screenshot 2021-09-26 at 23 46 02" src="https://user-images.githubusercontent.com/70921439/134823660-de38283e-9756-46f0-9d5c-d3c182cd3948.png">

2021-09-26 23:11 UTC, AntonZelinsky commented on apps/info/models.py
> +class Place(BaseModel):
Для меня нет значения как вы решите, главное, чтобы везде одинаково было!

2021-09-26 23:11 UTC, AntonZelinsky commented on apps/info/models.py
> +class Place(BaseModel):
Раз оставляете так, то об этом нужно прописать в каком-то файле. У гитхаба есть специальные механизмы для названия таких файлов. Нужно начинать по чуть-чуть формировать собственный гайдлайн. Можно взять чужой и просто отредактировать так, как нравится.

2021-09-26 23:12 UTC, AntonZelinsky approved these changes

2021-09-27 00:38 UTC, merged

2021-09-27 00:44 UTC, AntonZelinsky commented
@nkiryanov нет, по идее не нужно, просто нужно было под комментарием, который я зареквестал как обязательный нажать резолв.

2021-09-27 23:48 UTC, AntonZelinsky commented on requirements/dev.txt
> +<<<<<<< HEAD
@nkiryanov мы с тобой ревьювили-ревьювили да не выревьювили)