Bugfix/general partners footer
Studio-Yandex-Practicum/Lubimovka_backend pull request #101
Opened 2021-12-05 22:53 UTC by KonstantinRaikhert

Когда создаёте PR, убедитесь, что:

- [ ] вы проверили обновления в [брифе](https://www.notion.so/00f5d5a6d39e426fa1ea7ab69b694f07)
- [ ] синхронизировали изменения кода с [ER-диаграммой базы данных](https://drive.google.com/file/d/1RCIPaEgaLUSqek3znd38VPCKSzOlmJFy/view) связей моделей
- [ ] тесты все пройдены и нет конфликтов
- [ ] созданы необходимые миграции

Когда ваш PR смержен:

- [ ] если у вас были изменения в API, сообщите об этом команде Фронта, им это важно знать!

2021-12-05 23:03 UTC, KonstantinRaikhert commented
Этот PR по этой [задаче](https://www.notion.so/https-lubimovka-kiryanov-ru-api-v1-schema-swagger-ui-info-info_partners_list--a7689ce09dc64637bdf2945284317316)
Что было изменено и добавлено:

-  добавлено дополнительное поле in_footer в Partner (отображение в футере парочки генеральных партнеров)
-  добавлен новый ендпоинт *info/partners/in-footer/* для более удобного получения
- в админке нововведения:
    - при выборе генерального партнера открывается bool галочка in_footer (JS). Т.е. нет возможности администратору задать для других партнеров эту опцию
    - на странице со всеми партнерами ссылки на сайты кликабельны
- изменена фабрика партнеров (добавляется 5 ген. партнеров в футер) и команда filldb

2021-12-06 22:08 UTC, kr0t commented on apps/info/models.py
> +    in_footer = models.BooleanField(
Первая мысль, которая возникла, может стоит добавить конкретики в названии, например in_footer_partners. Но может из контекста модели это и так понятно 🤔

2021-12-06 22:10 UTC, kr0t commented on apps/info/models.py
> +            "Поставьте галочку, чтобы показать партнёра внизу страницы"
Я бы добавил, что надо показать "логотип" партнёра.

2021-12-06 22:12 UTC, kr0t commented on static/admin/js/partnerisfooter.js
> +jQuery(document).ready(function ($) {
🔥

2021-12-06 22:13 UTC, kr0t commented on static/admin/js/partnerisfooter.js
> +jQuery(document).ready(function ($) {
Это круто!💪🏽

2021-12-06 22:15 UTC, kr0t reviewed
Есть несколько мелких комментариев.

2021-12-06 22:27 UTC, nkiryanov requested changes
Есть комментарии и некоторые замечания.
А JS код не понимаю, но класс!

2021-12-06 22:27 UTC, nkiryanov commented on apps/info/admin.py
> +    class Media:
Давай напишем тут докстринг для чего, м?
А вообще что сделал такую реализацию — круто!

2021-12-06 22:27 UTC, nkiryanov commented on apps/info/admin.py
> +    show_partner_url.short_description = "Ссылка на сайт"
Это лучше и моднее делать через декоратор admin.display
Как и в остальных местах в п проекте.

2021-12-06 22:27 UTC, nkiryanov commented on apps/info/admin.py
> +        Makes the link to the partner's website clickable
Докстринг не по PEP (Я бы в верхнюю строчку убрал + точка в конце.)

Я же правильно понимаю что тут мы возвращаем url в списке на которую можно нажать? Тогда предлагаю назвать метод просто `partner_url` или `get_partner_url `. У меня название `show_partner_url` c булевым типом ассоциируется и нужно метод прочитать, чтоб понять что возвращаем на самом деле линк.

И тогда докстринг будет `Returns ...`

2021-12-06 22:27 UTC, nkiryanov commented on apps/info/admin.py
> +                "classes": ("predefined",),
Мм.. не нашел класса `predefined` и `included` в доукментации. А что они делают и где сам нашел?

2021-12-06 22:27 UTC, nkiryanov commented on apps/info/admin.py
>      ordering = ("type",)
А она нам точно тут нужна? Почему не в модель отдать?

2021-12-06 22:27 UTC, nkiryanov commented on apps/core/management/commands/filldb.py
> +                    PartnerFactory.create(type="general", in_footer=True)
А почему эту операцию не расписать на 2 строчки?
Это же понятнее читаться будет. Сейчас нужно напрягать ум зачем мы создаем factory и в этой же операции добавляем их в список. Давай делать проще.

Что ещё не понимаю: почему `create_batch` не использовать вместо цикла?

2021-12-06 22:27 UTC, nkiryanov commented on apps/info/tests/factories.py
> +            if self.type == "general":
А почему тут если тип general, то отдаем True?
Давай докстринг небольшой напишем. м?

2021-12-06 22:27 UTC, nkiryanov commented on apps/info/views/partners.py
> +class PartnersInFooterViewSet(ListAPIView):
Тут даешь название ViewSet, а по факту это APIView и все волшебные методы вьюсета неприменимы.

Выше тоже ошибки, конечно. ХЗ как такое получилось, может я пропустил.

А ещё у меня вопрос — мне кажется нам не нужно сразу два эндпоинта для этого. Мы можем отдавать в одном PartnersViewSet.

Наверное лучше уточнить у фронта, как им будет удобнее: возможно в эндпонинтах оставить. А может быть просто хватит типа (сами будут понимать кого выводить, кого нет), а может быть сделать 2 блоками как отдаем main

Как тебе такая идея?

2021-12-06 22:27 UTC, nkiryanov commented on config/settings/base.py
> +STATICFILES_DIRS = ("static",)
Зачем? Она и так есть в папках по умолчанию

2021-12-06 22:27 UTC, nkiryanov commented on static/admin/js/partnerisfooter.js
> +jQuery(document).ready(function ($) {
Давай и тут докстринг напишем, м?
Нафига эта штука и зачем применяется.

2021-12-07 10:59 UTC, KonstantinRaikhert commented on apps/info/models.py
> +    in_footer = models.BooleanField(
Можно, в принципе.

2021-12-07 11:03 UTC, KonstantinRaikhert commented on apps/info/admin.py
> +    show_partner_url.short_description = "Ссылка на сайт"
Можно указать где именно? (Пример).
Строчка для русского значения в админке.

2021-12-07 11:04 UTC, KonstantinRaikhert commented on apps/info/admin.py
> +        Makes the link to the partner's website clickable
Да, метод даёт с админки по ссылке уйти на сайт партнера.
Поменяю название

2021-12-07 11:04 UTC, KonstantinRaikhert commented on apps/info/admin.py
> +                "classes": ("predefined",),
😅 сам придумал. Нужно сугубо для в скрипте js

2021-12-07 11:05 UTC, KonstantinRaikhert commented on apps/info/admin.py
>      ordering = ("type",)
Сортировку? Можно и в модель

2021-12-07 11:08 UTC, KonstantinRaikhert commented on apps/core/management/commands/filldb.py
> +                    PartnerFactory.create(type="general", in_footer=True)
В '''create_batch''' принимается количество необходимых объектов.
А мне нужно сделать 5 объектов с флагом True in_footer. Только для генеральных партнеров.

2021-12-07 11:10 UTC, KonstantinRaikhert commented on apps/info/views/partners.py
> +class PartnersInFooterViewSet(ListAPIView):
Как вариант, чтобы в query параметре был ещё in_footer=True. Ты это имеешь ввиду?

2021-12-07 11:11 UTC, KonstantinRaikhert commented on static/admin/js/partnerisfooter.js
> +jQuery(document).ready(function ($) {
Ок

2021-12-07 11:38 UTC, nkiryanov commented on apps/info/admin.py
> +    show_partner_url.short_description = "Ссылка на сайт"
Ну глянь как в других приложениях в админке это делаем. Просто в нескольких PR уже писал (не помню чьих)

Напрмер apps.core.admin.SettingAdmin.get_value

2021-12-07 11:40 UTC, nkiryanov commented on apps/info/admin.py
> +    show_partner_url.short_description = "Ссылка на сайт"
@admin.display(description="Значение")

2021-12-07 11:41 UTC, nkiryanov commented on apps/info/admin.py
> +                "classes": ("predefined",),
Ну значит это как-то нужно описать. А то иду сразу искать а документации, а такие не нахожу :(

2021-12-07 11:42 UTC, nkiryanov commented on apps/core/management/commands/filldb.py
> +                    PartnerFactory.create(type="general", in_footer=True)
И в чем проблема эти параметры передатт в create_batch?

2021-12-07 11:42 UTC, nkiryanov commented on apps/info/views/partners.py
> +class PartnersInFooterViewSet(ListAPIView):
Да, можно и так, ага

2021-12-07 11:44 UTC, nkiryanov commented on config/settings/base.py
> +STATICFILES_DIRS = ("static",)
Мм. Точно? Судя по документации он будет искать статику в папках static в папках приложений. Она у нас там же или не?

2021-12-07 12:01 UTC, KonstantinRaikhert commented on apps/core/management/commands/filldb.py
> +                    PartnerFactory.create(type="general", in_footer=True)
Оу... что то я просмотрел, что может кварги принимать.
Видимо когда в последний раз пробовал, ошибки допускал

2021-12-07 12:02 UTC, KonstantinRaikhert commented on config/settings/base.py
> +STATICFILES_DIRS = ("static",)
Статика в корне проекта static
Я посмотрю ещё

2021-12-07 23:18 UTC, nkiryanov approved these changes
Написал некоторые замечания/мысли. Но вроде все некритичные.

2021-12-07 23:18 UTC, nkiryanov commented on apps/core/management/commands/filldb.py
> +                5, type="general", in_footer_partner=True
А давай здесь тоже параметры передавать как моделях. Переносить на новую строчку, если водну все не влезают.

Необязательно.

2021-12-07 23:18 UTC, nkiryanov commented on apps/core/management/commands/filldb.py
>              notification(self, partners, "партнёров")
Это мысли вслух и просто обращаю внимание.

С одной стороны эта функция сейчас решает проблему оповещения и возвращает количество созданных объектов. Но делает то как неоптимально — созданные объекты передаем или в словарь или queryset считаем через len, а не count.

Но работает, да.
Не к тому, что нужно править сейчас в этом PR. Но если увидеть не только мне и кто-то подправит в следующем PR будет неплохо.

2021-12-07 23:18 UTC, nkiryanov commented on apps/info/admin.py
> +    """A JS script is used here.
Ну. Я бы написал комментарий, что это админка партнеров, но расширена JS.
А сейчас получается как заголовок. Странно.

2021-12-07 23:18 UTC, nkiryanov commented on apps/info/admin.py
> +    In fieldsets are used two classes: `predefined` and `included`.
Неплохо порядок слов поменять, а то тяжело понимается.
Two classes are used in fieldsets

2021-12-07 23:18 UTC, nkiryanov commented on apps/info/admin.py
> +    `predefined` - if partners are festival or info.
Тут чот не понял :(

2021-12-07 23:18 UTC, nkiryanov commented on apps/info/admin.py
> +    @admin.display(description="Ссылка на сайт")
👍

2021-12-07 23:18 UTC, nkiryanov commented on apps/info/tests/factories.py
> +    in_footer_partner = False
Ну уж тут тоже можно добавить полноценную фабрику поля

`in_footer_partner = factory.Faker("boolean")`

Ну вроде так.

2021-12-08 19:13 UTC, merged