Feature/blogs news projects factories
Studio-Yandex-Practicum/Lubimovka_backend pull request #102
Opened 2021-12-06 14:19 UTC by Omnomus

- Добавлены фабрики для Блога. 
- В команду filldb включены: создание Блога, Пьес, Программ, Изображений для контента. 
По умолчанию создание Блога идет со всеми контентными блоками, по 1 каждого. Можно настроить добавление блоков в нужном количестве (соответствующий комментарий к фабрике написан).

2021-12-06 23:37 UTC, nkiryanov requested changes
Есть рекомендации и комментарии.
Но работа видно большая и кажется от итогового варианта отдаляет не многое.

По структуре вызовов фабрик кажется ок будет проще/понятнее если будем придерживаться логики как со всеми фабриками:

1. Базовые объекты создаются отдельно (картинки, пьесы, песоны и тд)
2. Фабрики "содержимого контента - 1 элемент" создаются сейчас вроде как нужно
3. Фабрики "содержимое контента - блок элементов" рекомендую передать — чтоб в фабрике блока автоматически создавалось заданное/случайное количество OrderedBlocks
4. Блок "элемент контента блога" (BlogItemContent) реализован через 7 фабрик. Может быть сможем сделать его 1 фабрикой, но которая принимает параметр на тип создаваемого контента и будет сама создавать нужный блок контента, м?

2021-12-06 23:37 UTC, nkiryanov commented on apps/articles/tests/factories.py
> +class BlogPersonFactory(factory.django.DjangoModelFactory):
Эта factory требует чтоб в БД были объекты Person и Role. Если их нет, то свалится в ошибку.

Чтоб это правильно обрабатывать у нас есть декоратор специальный (в core лежит). Давай его использоватьб.

2021-12-06 23:37 UTC, nkiryanov commented on apps/articles/tests/factories.py
> +    co_author = factory.RelatedFactory(BlogPersonFactory, "blog")
А это что такое? Нет же такого field у модели.

2021-12-06 23:37 UTC, nkiryanov commented on apps/articles/tests/factories.py
> +    is_draft = factory.LazyFunction(lambda: random.choice([True, False]))
Для этого уже [есть Faker](https://faker.readthedocs.io/en/master/providers/faker.providers.misc.html?highlight=boolean#faker.providers.misc.Provider.boolean), в котором даже можно вероятность настроить и красивее.

И вообще там много что есть полезного.

2021-12-06 23:37 UTC, nkiryanov commented on apps/articles/tests/factories.py
> +    def add_item_preamble(self, created, extracted, **kwargs):
Метод назван так. как будто принимает булевый значения (да/нет), а по факту ожидает количество преамбул которые нужно добавить.
Давай переназавём.

Ещё — не понимаю зачем здесь цикл. Ведь есть прекрасный `create_batch`

А ещё — каждый метод однотипный и много дублирующегося кода. Может вынести их сразу с функцию?

2021-12-06 23:37 UTC, nkiryanov commented on apps/articles/tests/factories.py
> +                person_block = PersonContentFactory.create(content_page=self)
`PersonContentFactory` создается пустым и после привязываем туда персон.
Почему бы PersonContentFactory сразу не создавать с персонами. По-моему это как раз не сложно и код сразу красивее и понятнее.

2021-12-06 23:37 UTC, nkiryanov commented on apps/content_pages/tests/factories.py
> +        width=factory.LazyFunction(lambda: random.randint(10, 1000)),
А откуда такие значения? Может быть по умолчанию оставить или задать те, которые будут в реальности картинки (вряд ли они будут 10 пикселей)

2021-12-06 23:37 UTC, nkiryanov commented on apps/content_pages/tests/factories.py
> +        color=factory.LazyFunction(
Есть уже faker для этого.
Я [вот так](https://github.com/nkiryanov/foodgram-project-react/blob/9b8fd8c9e828b427892dca33cc822c99b2efbe0b/backend/foodgram/recipes/factories.py#L74) делал

2021-12-06 23:37 UTC, nkiryanov commented on apps/content_pages/tests/factories.py
> +    title = factory.Faker("text", locale="ru_RU", max_nb_chars=20)
Давай sentence возьмем, м?

2021-12-06 23:37 UTC, nkiryanov commented on apps/content_pages/tests/factories.py
> +    block = factory.SubFactory(PersonsBlockFactory)
Тут кажется нарушается логика. 
PersonsBlockFactory вызывает создание OrderedPersonFactory а OrderedPersonFactory в свою очередь вызывает создание PersonsBlockFactory

Точно ща нормально работает?

2021-12-06 23:37 UTC, nkiryanov commented on apps/content_pages/tests/factories.py
> +class ImagesBlockFactory(factory.django.DjangoModelFactory):
Мне кажется будет понятнее (и легче дебажить в том числе), если наполнение содержимым будет происходить здесь. То есть в сразу тут будем добавлять картинки и их порядок.

А вот картинки можно не создавать новые, а выбирать из имеющихся. Ну или создавать новые. Тут как решишь сама.

2021-12-06 23:37 UTC, nkiryanov commented on apps/core/management/commands/filldb.py
> +            images_content = ImageForContentFactory.create_batch(5)
Вообще мы в этом PR как бы фабрики для блогов пишем, а вдруг добавляем в наполнение базы данных наполнение картинками + программами и пьесами. Это не относится к этому PR и мне кажется что будет проще эти изменения в отдельном PR делать. Вообще независимым. Он будет меньше, его быстрее отревьвим и будет понятна логика.

2021-12-07 15:50 UTC, Omnomus commented on apps/articles/tests/factories.py
> +import random
урезала сильно, тут остались только функция + 3 фабрики, оставлю

2021-12-07 15:55 UTC, Omnomus commented on apps/articles/tests/factories.py
> +        lambda o: ContentType.objects.get_for_model(o.item)
o.item - это поле item из модели AbstractContent (который Generic). То есть тут находим его тип. Взяла здесь: https://factoryboy.readthedocs.io/en/latest/recipes.html#django-models-with-genericforeignkeys

2021-12-07 16:09 UTC, Omnomus commented on apps/articles/tests/factories.py
> +class BlogPersonFactory(factory.django.DjangoModelFactory):
done

2021-12-07 16:15 UTC, Omnomus commented on apps/articles/tests/factories.py
> +    co_author = factory.RelatedFactory(BlogPersonFactory, "blog")
соавтор. Действительно, он добавляется по типу блоков, перенесла в методы пост-генерации

2021-12-07 16:18 UTC, Omnomus commented on apps/articles/tests/factories.py
> +    is_draft = factory.LazyFunction(lambda: random.choice([True, False]))
done

2021-12-07 16:19 UTC, Omnomus commented on apps/articles/tests/factories.py
> +    def add_item_preamble(self, created, extracted, **kwargs):
исправила

2021-12-07 16:19 UTC, Omnomus commented on apps/articles/tests/factories.py
> +                person_block = PersonContentFactory.create(content_page=self)
вынесла создание в PersonsBlockFactory (PersonContentFactory вообще убрала)

2021-12-07 16:26 UTC, Omnomus commented on apps/content_pages/tests/factories.py
> +        width=factory.LazyFunction(lambda: random.randint(10, 1000)),
взяла из соседних фабрик) (из core). выставлю 300

2021-12-07 16:27 UTC, Omnomus commented on apps/content_pages/tests/factories.py
> +        color=factory.LazyFunction(
исправила

2021-12-07 16:30 UTC, Omnomus commented on apps/content_pages/tests/factories.py
> +    title = factory.Faker("text", locale="ru_RU", max_nb_chars=20)
ok

2021-12-07 16:31 UTC, Omnomus commented on apps/content_pages/tests/factories.py
> +    block = factory.SubFactory(PersonsBlockFactory)
Нет, PersonsBlockFactory не вызывает ничего, там только title объявляется. Но сейчас я поменяла, и Block будет вызывать Ordered. В свою очередь, из Ordered убрала упоминание Block'а, чтоб не зациклить.

2021-12-07 16:38 UTC, Omnomus commented on apps/content_pages/tests/factories.py
> +class ImagesBlockFactory(factory.django.DjangoModelFactory):
да, добавление вынесла в BlockFactories

2021-12-07 16:38 UTC, Omnomus commented on apps/core/management/commands/filldb.py
> +            images_content = ImageForContentFactory.create_batch(5)
OK. для тестирования было необходимо, но все уберу.

2021-12-07 18:06 UTC, Omnomus commented on apps/content_pages/tests/factories.py
> +        width=factory.LazyFunction(lambda: random.randint(10, 1000)),
убрала совсем в итоге

2021-12-07 21:23 UTC, nkiryanov requested changes
Комментариев написал много, но на самом деле правок не много.
Уже нравится как получается 👍

2021-12-07 21:23 UTC, nkiryanov commented on apps/articles/tests/blog_factory.py
> +    def add_block_image(self, created, count, **kwargs):
`imagesblock`
Тут и в других подобных методах:
Лучше давать такие же названия как в моделях используем. Так не будет разночтений (block_person — это одна персона? Ведь персон много, а блок 1) + похоже на модели и проще разобраться что есть что.

2021-12-07 21:23 UTC, nkiryanov commented on apps/content_pages/tests/factories.py
> +class ImageForContentFactory(factory.django.DjangoModelFactory):
👍

2021-12-07 21:23 UTC, nkiryanov commented on apps/content_pages/tests/factories.py
> +    order = factory.Sequence(lambda n: (n % 3 + 1))
что-то не понимаю а зачем вот это?
(n % 3 + 1) Что не больше 3 элементов? Кажется лишнее. Персон в блоке может быть до 8 (таких ограничений пока нет в моделях, ещё предстоит делать)

2021-12-07 21:23 UTC, nkiryanov commented on apps/content_pages/tests/factories.py
> +class OrderedPersonFactory(factory.django.DjangoModelFactory):
OrderedPersonFactory зависит от Person. Тоже декоратор ждёт.

2021-12-07 21:23 UTC, nkiryanov commented on apps/core/management/commands/filldb.py
> +                blogs.append(BlogFactory.complex_create())
Тут тоже давай в 2 строчки напишем.
Сложно же понять, что происходит вот здесь — blogs.append(BlogFactory.complex_create())

Так наверное уже выше/ниже сделано, но это видать мимо меня прошло, либо пропустил (что тоже бывает)

2021-12-08 14:05 UTC, Omnomus commented on apps/articles/tests/blog_factory.py
> +    is_draft = fake.boolean(chance_of_getting_true=25)
поправила

2021-12-08 16:54 UTC, Omnomus commented on apps/content_pages/tests/factories.py
> +    order = factory.Sequence(lambda n: (n % 3 + 1))
Нет. Смотри, количество персон в блоке я задаю хардкорно в PersonsBlockFactory = 3. Если я оставляю lambda n :n - то при создании в одном Блоге двух и более блоков с персонами я получаю сквозную нумерацию  от 0 до 5. Этой формулой (остаток от деления n на 3 плюс 1) - я присваиваю всем правильные номера от 1 до 3 в блоке.

2021-12-08 17:01 UTC, nkiryanov commented on apps/content_pages/tests/factories.py
> +    order = factory.Sequence(lambda n: (n % 3 + 1))
Понял. Вроде и так бы работало, но лучше чем вообще ничего, согласен.
Давай добавим что не более 3 персон в блоке создаем в докстринг и тогда у "будущего код-ревьювера" вопрос что такое пропадет.

2021-12-08 17:11 UTC, Omnomus commented on apps/articles/tests/blog_factory.py
> +    def add_co_author(self, created, count, **kwargs):
ok

2021-12-08 17:12 UTC, Omnomus commented on apps/articles/tests/blog_factory.py
> +def add_item_to_blog(blog, created, count, factory):
ok

2021-12-08 17:27 UTC, Omnomus commented on apps/articles/tests/blog_factory.py
> +        add_item_to_blog(self, created, count, factory.SubFactory(TextFactory))
ok

2021-12-08 17:28 UTC, Omnomus commented on apps/articles/tests/blog_factory.py
> +        lambda o: ContentType.objects.get_for_model(o.item)
сделала obj)

2021-12-08 17:29 UTC, Omnomus commented on apps/articles/tests/blog_factory.py
> +@restrict_factory({"add_block_image": [Image], "add_block_play": [Play]})
так в декораторе самом в докстринг указан list и пример со списком...

2021-12-08 17:33 UTC, Omnomus commented on apps/articles/tests/blog_factory.py
> +    order = factory.Sequence(lambda n: n)
вот тут интересно то, что нигде в админке я эту нумерацию не вижу. допускаю, что плохо смотрю. оставила, чтоб не тормозить

2021-12-08 17:36 UTC, Omnomus commented on apps/articles/tests/blog_factory.py
> +    def complex_create(cls):
ок

2021-12-08 17:42 UTC, Omnomus commented on apps/core/management/commands/filldb.py
> +                blogs.append(BlogFactory.complex_create())
ok

2021-12-08 19:10 UTC, nkiryanov commented on apps/articles/tests/blog_factory.py
> +    order = factory.Sequence(lambda n: n)
Это поле в админке обслуживает пакет что-то там про sortable.

Посмотри у моделей есть миксин соответствующий.

Он скрывает это поле и на основе нумерации рисует/назначает номерочки. Но сам номер для ввода пользователем не выводится, это верно

2021-12-08 19:31 UTC, Omnomus commented on apps/articles/tests/blog_factory.py
> +    def add_block_image(self, created, count, **kwargs):
ok

2021-12-08 19:36 UTC, Omnomus commented on apps/content_pages/tests/factories.py
> +class OrderedPersonFactory(factory.django.DjangoModelFactory):
done

2021-12-08 19:41 UTC, Omnomus commented on apps/content_pages/tests/factories.py
> +class OrderedPersonFactory(factory.django.DjangoModelFactory):
для единообразия добавила в декоратор к основной BlogFactory

2021-12-08 21:46 UTC, nkiryanov approved these changes
Оставил ещё пару комментариев (или ответил в старых, unresolved converstations).
Но какие-то правки незначительные.

Большая работа 👍

2021-12-08 21:46 UTC, nkiryanov commented on README.md
> +- пользователи-админы и редакторы (для входа используем ник admin_X или editor_X, где Х - число от 1 до 5 и дефолтный пароль "pass")
👍

2021-12-08 21:46 UTC, nkiryanov commented on apps/articles/tests/blog_factory.py
> +        "date_time", tzinfo=timezone.get_current_timezone()
Да можно просто было utc. Только проще. А так у разных людей могут разные данные генерироваться. И вдруг это как-то на тесты повлияет.

Касательно стиля: давай тут тоже [такого правила](https://github.com/Studio-Yandex-Practicum/Lubimovka_backend/blob/develop/docs/codestyle.md#правила-для-моделей) придерживаться

2021-12-08 21:46 UTC, nkiryanov commented on apps/articles/tests/blog_factory.py
> +        add_content_item_to_blog(self, created, count, subfactory)
Бесспорно я зануда. Но мне такое читать гораздо приятнее. Ещё потому как выглядит.
👍

2021-12-08 21:46 UTC, nkiryanov commented on apps/content_pages/tests/factories.py
> +class OrderedPersonFactory(factory.django.DjangoModelFactory):
Но ведь мы можем вызывать эту фабрику отдельно. И по хорошему это сделать, написав тесты (вот я очень хочу, но не успеваю).

В общем сюда тоже нужно. И всем фабрикам, которые отдельно создают контент.

2021-12-08 21:46 UTC, nkiryanov commented on apps/articles/tests/blog_factory.py
> +    def complex_create(cls):
Насколько вижу не стали реализовывать. Ну ладно :(

2021-12-08 21:46 UTC, nkiryanov commented on apps/articles/tests/blog_factory.py
> +    def complex_create(cls):
Да нет же, сделали!
Класс!

2021-12-08 21:46 UTC, nkiryanov commented on apps/articles/tests/blog_factory.py
> +@restrict_factory({"add_block_image": [Image], "add_block_play": [Play]})
>так в декораторе самом в докстринг указан list и пример со списком...

Ну мы становимся лучше и в декортаторе эти правила появились ещё до того, как перешли на кортежи.
В общем там уже легаси код :)

2021-12-08 21:46 UTC, nkiryanov commented on apps/articles/tests/blog_factory.py
> +@restrict_factory({"add_block_image": [Image], "add_block_play": [Play]})
В общем неплохо использовать всё же кортежи. Но не очень критично.

2021-12-08 22:43 UTC, AntonZelinsky approved these changes

2021-12-09 12:37 UTC, Omnomus commented on apps/articles/tests/blog_factory.py
> +        "date_time", tzinfo=timezone.get_current_timezone()
ok

2021-12-09 12:37 UTC, Omnomus commented on apps/articles/tests/blog_factory.py
> +        "date_time", tzinfo=timezone.get_current_timezone()
По стилю: мне pre-commit все правит обратно))

2021-12-09 12:43 UTC, merged

2021-12-09 12:44 UTC, Omnomus commented
Factories fo Blog added.

2021-12-09 12:59 UTC, nkiryanov commented
Поставь запятую после последнего элемента. И станет ок

> 9 дек. 2021 г., в 15:38, Ksenia Bondar ***@***.***> написал(а):
> 
> ﻿
> @Omnomus commented on this pull request.
> 
> In apps/articles/tests/blog_factory.py:
> 
> > +    """
> +
> +    class Meta:
> +        model = BlogItem
> +
> +    author_url = factory.Faker("url")
> +    author_url_title = factory.Faker("name", locale="ru_RU")
> +    description = factory.Faker(
> +        "paragraph",
> +        locale="ru_RU",
> +        nb_sentences=5,
> +        variable_nb_sentences=False,
> +    )
> +    is_draft = factory.Faker("boolean", chance_of_getting_true=25)
> +    pub_date = factory.Faker(
> +        "date_time", tzinfo=timezone.get_current_timezone()
> По стилю: мне pre-commit все правит обратно))
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.