add flake8-docstrings checker
Studio-Yandex-Practicum/Lubimovka_backend pull request #105
Opened 2021-12-07 18:33 UTC by kr0t

В PR добавлена проверка на докстринги. Отключены правила D100-D107.

Когда создаёте PR, убедитесь, что:

- [x] вы проверили обновления в [брифе](https://www.notion.so/00f5d5a6d39e426fa1ea7ab69b694f07)
- [x] синхронизировали изменения кода с [ER-диаграммой базы данных](https://drive.google.com/file/d/1RCIPaEgaLUSqek3znd38VPCKSzOlmJFy/view) связей моделей
- [x] тесты все пройдены и нет конфликтов
- [x] созданы необходимые миграции

Когда ваш PR смержен:

- [ ] если у вас были изменения в API, сообщите об этом команде Фронта, им это важно знать!

2021-12-07 18:40 UTC, AntonZelinsky approved these changes

2021-12-07 18:43 UTC, KonstantinRaikhert commented on pyproject.toml
> +flake8-docstrings = "^1.6.0"
А его можно добавить в pre-commit?
И по хорошему в github-actions

2021-12-07 19:46 UTC, nkiryanov requested changes
Всё класс, но поправить бы сразу все докстринги, чтоб тесты проходил. Кому-то же всё равно это нужно делать и тут кажется не очень много работы.

Поправишь?

2021-12-12 16:00 UTC, AntonZelinsky approved these changes
Нужно этот ПР мержить, так как уже есть пачка конфликтов, а будет ещё больше, так как очень много файлов затрагивает этот ПР. 

P.S.: если теперь импорты будут в одну строку делаться, а не в столбик, то нужно добавить в гайдлайны и как минимум написать об этом пост в общем чатике, потому что раньше всё делалось в столбик, а сейчас конфузит

2021-12-12 22:09 UTC, kr0t commented
> Нужно этот ПР мержить, так как уже есть пачка конфликтов, а будет ещё больше, так как очень много файлов затрагивает этот ПР.
> 
> P.S.: если теперь импорты будут в одну строку делаться, а не в столбик, то нужно добавить в гайдлайны и как минимум написать об этом пост в общем чатике, потому что раньше всё делалось в столбик, а сейчас конфузит

Я импорты не трогал, только докстринги, что именно их поменяло я пока не знаю.

2021-12-12 22:57 UTC, nkiryanov approved these changes

2021-12-13 07:32 UTC, merged