Fix/playfilters
Studio-Yandex-Practicum/Lubimovka_backend pull request #106
Opened 2021-12-07 20:03 UTC by MarselMulyukov

Когда создаёте PR, убедитесь, что:

- [ ] вы проверили обновления в [брифе](https://www.notion.so/00f5d5a6d39e426fa1ea7ab69b694f07)
- [ ] синхронизировали изменения кода с [ER-диаграммой базы данных](https://drive.google.com/file/d/1RCIPaEgaLUSqek3znd38VPCKSzOlmJFy/view) связей моделей
- [ ] тесты все пройдены и нет конфликтов
- [ ] созданы необходимые миграции

Когда ваш PR смержен:

- [ ] если у вас были изменения в API, сообщите об этом команде Фронта, им это важно знать!

2021-12-07 21:42 UTC, nkiryanov requested changes
Есть чуть комментариев 🤷‍♂️

2021-12-07 21:42 UTC, nkiryanov commented on apps/library/filters/play.py
> +    program = filters.BaseInFilter(
Если правильно помню так работать не должно. Этот фильтр должен использоваться **только** в паре с другим фильтром.

[Вот пример ](https://django-filter.readthedocs.io/en/stable/ref/filters.html?highlight=BaseInFilter#baseinfilter)в документации.

Неужели работает?

2021-12-07 21:42 UTC, nkiryanov commented on apps/library/views/playfilters.py
> +        years = Festival.objects.all()
А давай сделаем так же как в festivals/years сделал
Так мы будем в queryset забирать из БД не все объекты, а только года/программы. Это быстрее. Сразу от 2 сериалайзеров сможем избавиться.

2021-12-10 15:22 UTC, elisey approved these changes

2021-12-10 22:01 UTC, nkiryanov approved these changes
Ну отлично всё! 👍

2021-12-10 22:01 UTC, merged