Bugfix/library preformance
Studio-Yandex-Practicum/Lubimovka_backend pull request #123
Opened 2021-12-15 19:38 UTC by DRAGANmik

Когда создаёте PR, убедитесь, что:

- [ ] вы проверили обновления в [брифе](https://www.notion.so/00f5d5a6d39e426fa1ea7ab69b694f07)
- [ ] синхронизировали изменения кода с [ER-диаграммой базы данных](https://drive.google.com/file/d/1RCIPaEgaLUSqek3znd38VPCKSzOlmJFy/view) связей моделей
- [ ] убедились, что модель OpenAPI проверена (в Swagger отображаются изменения)
- [ ] тесты все пройдены и нет конфликтов
- [ ] созданы необходимые миграции

Когда ваш PR смержен:

- [ ] если у вас были изменения в API, сообщите об этом команде Фронта, им это важно знать!

2021-12-20 20:49 UTC, AntonZelinsky requested changes

2021-12-21 17:17 UTC, DRAGANmik commented on apps/library/views/performance.py
> +        query = PerformanceMediaReview.objects.filter(performance=pk)
Везде где смотрел, было ViewSet

2021-12-21 17:17 UTC, DRAGANmik commented on apps/library/serializers/performance.py
> +        event = Event.objects.filter(common_event=obj.events)
Немного переделал, может быть пройдет

2021-12-21 22:35 UTC, AntonZelinsky approved these changes

2021-12-21 22:35 UTC, AntonZelinsky commented on apps/library/serializers/performance.py
> +        return EventSerializer(obj.events.body.first()).data
А почему бы не определить сериализатор напрямую задать, как это было сделано тут: `images_in_block = ImageSerializer(many=True)`

2021-12-22 10:57 UTC, merged