Feature/pdf for press
Studio-Yandex-Practicum/Lubimovka_backend pull request #124
Opened 2021-12-15 23:26 UTC by evi1ghost

Добавлен эндпоинт для перссы скачивания пресс-релизов - api/v1/info/press-releases/<id>/download
Выгрузка в pdf осуществляется через библиотеку xhtml2pdf - преобразует html в размеченный текст.

Когда создаёте PR, убедитесь, что:

- [ ] вы проверили обновления в [брифе](https://www.notion.so/00f5d5a6d39e426fa1ea7ab69b694f07)
- [ ] синхронизировали изменения кода с [ER-диаграммой базы данных](https://drive.google.com/file/d/1RCIPaEgaLUSqek3znd38VPCKSzOlmJFy/view) связей моделей
- [ ] убедились, что модель OpenAPI проверена (в Swagger отображаются изменения)
- [ ] тесты все пройдены и нет конфликтов
- [ ] созданы необходимые миграции

Когда ваш PR смержен:

- [ ] если у вас были изменения в API, сообщите об этом команде Фронта, им это важно знать!

2021-12-16 13:35 UTC, nkiryanov requested changes
В целом класс. Есть только одно пожелание не хардкодить путь к статике, а передавать как переменную в шаблон.

2021-12-16 13:35 UTC, nkiryanov commented on apps/info/templates/press_release.html
> +            src: url('staticfiles/fonts/NeueMachinaRegular/PPNeueMachina-Regular.ttf');
Тут ок, но путь к шрифту захардкоден. Нужно передавать в шаблон переменную пути к статике.

2021-12-16 13:35 UTC, nkiryanov commented on apps/info/views/press_release.py
> +        url_path=r"(?P<id>[\d]+)/download",
Как понимаю используем, так как используем ListModelMixin.
Думаю неплохо отрефакторить, но в след. итерации. Создал карточку на борде.

2021-12-16 13:35 UTC, nkiryanov commented on apps/info/views/press_release.py
> +        pisa_status = pisa.CreatePDF(
Вот тут нужно добавить переменную где у нас лежит статика и передавать в контекст и будет работать.

2021-12-20 08:34 UTC, nkiryanov approved these changes
Написал комментарий.
Прямо сейчас перестал активно ревьювить, потому апрувлю, чтоб мои мои ревью не тормозили процесс.

2021-12-20 08:34 UTC, nkiryanov commented on apps/info/views/press_release.py
> +        path_to_font = "staticfiles/fonts/NeueMachinaRegular/PPNeueMachina-Regular.ttf"
Теперь url к статике захардкодено в view. Наверное это лучше, чем в шаблоне, но всё сломается если расположение статики поменяется.

Имел в виду что-то такое:

```python
from django.conf import settings
context["STATIC_ROOT"] = settings.STATIC_ROOT
```

и в шаблоне:

```html
 @font-face {
        font-family: "NeueMachinaRegular";
        src: url("{{STATIC_ROOT}}/fonts/NeueMachinaRegular.ttf");
    }
```

2021-12-20 22:34 UTC, kr0t commented on .github/workflows/check_vulnerabilities.yaml
> +          safety_args: '-i 39642'
А почему мы игнорируем эту CVE?

2021-12-20 22:38 UTC, kr0t commented on apps/info/utils.py
> +    pisa_status = pisa.CreatePDF(
А это статус чего?

2021-12-20 22:41 UTC, kr0t reviewed
Есть пара вопросов.

2021-12-29 14:49 UTC, merged