added_question_model
Studio-Yandex-Practicum/Lubimovka_backend pull request #13
Opened 2021-09-26 19:52 UTC by MarselMulyukov

2021-09-26 22:15 UTC, nkiryanov requested changes
Небольшие правки

2021-09-26 22:15 UTC, nkiryanov commented on apps/info/models.py
>      class Meta:
Добавить метод __str__

2021-09-26 22:15 UTC, nkiryanov commented on apps/info/models.py
>          unique=True,
Вопрос не должен быть уникальным. Ведь 2 разных товарища могут написать одинаковые вопросы.

+ это было задано раньше, но модель была как заглушка: по-моему 200 символов может не хватить для вопроса письмом. Давай расширим до 500?

2021-09-28 17:09 UTC, kr0t approved these changes

2021-09-29 20:42 UTC, nkiryanov requested changes
Есть правки 🤷‍♂️

2021-09-29 20:42 UTC, nkiryanov commented on apps/info/models.py
> +    name = models.CharField(max_length=50, verbose_name="Имя")
Блин, мне дико неловко, но вот тут и у метода `__str__` нужно привести всё к виду по styleguide

https://github.com/Studio-Yandex-Practicum/Lubimovka_backend/blob/develop/docs/codestyle.md

Если что для fields достаточно запятую поставить после последнего элемента и black сам всё переформатирует

2021-09-29 20:42 UTC, nkiryanov commented on apps/info/models.py
> +    def __str__(self):
Смотри по sytleguide выше.

2021-09-29 21:57 UTC, DRAGANmik approved these changes

2021-09-30 21:49 UTC, nkiryanov requested changes

2021-09-30 21:49 UTC, nkiryanov commented on apps/info/migrations/0004_added_question_model.py
> +from django.db import migrations, models
Вот эта миграция ща ссылкатеся на 003, а такой ща нет в проекте. Их пересоздали.
Ну ща сам поправлю, чтоб побыстрее всё получилось.

2021-09-30 21:52 UTC, nkiryanov commented on apps/info/migrations/0004_added_question_model.py
> +from django.db import migrations, models
Подправил.

2021-09-30 21:53 UTC, nkiryanov approved these changes
Постараемся новые PR принимать быстрее.
Ура!

2021-09-30 21:53 UTC, merged