Feature/admin logo
Studio-Yandex-Practicum/Lubimovka_backend pull request #132
Opened 2021-12-22 09:44 UTC by Polinavas95

Логотип в панели админки

Когда создаёте PR, убедитесь, что:

- [ ] вы проверили обновления в [брифе](https://www.notion.so/00f5d5a6d39e426fa1ea7ab69b694f07)
- [ ] синхронизировали изменения кода с [ER-диаграммой базы данных](https://drive.google.com/file/d/1RCIPaEgaLUSqek3znd38VPCKSzOlmJFy/view) связей моделей
- [ ] убедились, что модель OpenAPI проверена (в Swagger отображаются изменения)
- [ ] тесты все пройдены и нет конфликтов
- [ ] созданы необходимые миграции

Когда ваш PR смержен:

- [ ] если у вас были изменения в API, сообщите об этом команде Фронта, им это важно знать!

2021-12-22 13:06 UTC, AntonZelinsky reviewed
@kr0t посмотри, пожалуйста, этот ПР, Почему тут так много переформатировалось импортов? Ты же всё это делал раньше? Этот кусочек забыл или тут что-то не так?

2021-12-22 13:06 UTC, AntonZelinsky commented on templates/admin/base_site.html
> +     <img src="staticfiles/admin/img/logo.png" alt="logo">
Хардкодить путь нельзя! Нужно всегда отдавать джанго генерацию пути `https://docs.djangoproject.com/en/4.0/ref/templates/builtins/#std:templatetag-static`

2021-12-22 13:58 UTC, Polinavas95 commented on templates/admin/base_site.html
> +     <img src="staticfiles/admin/img/logo.png" alt="logo">
я не совсем поняла, что нужно сделать. Где можно почитать об этом? Нужно изменить src?

2021-12-22 15:15 UTC, KorsakovPV commented on templates/admin/base_site.html
> +     <img src="staticfiles/admin/img/logo.png" alt="logo">
```{% load static %}
<img src="{% static 'images/hi.jpg' %}" alt="Hi!">```

2021-12-25 20:35 UTC, nkiryanov requested changes
PR на самом деле небольшой, это отлично.

Мысли свои написал. Может быть где-то ошибся. На вопрос что делать с измененными импортами отписал тоже.

Из важных изменений: как меняем админку — в целом всё правильно. Только в другом месте разместить бы.

2021-12-25 20:35 UTC, nkiryanov commented on config/settings/base.py
> +        "DIRS": [TEMPLATES_DIR, "templates/"],
`templates/` вроде как можно (нужно) не добавлять. Они явно перечислены в `TEMPLATES_DIR` выше.

2021-12-25 20:35 UTC, nkiryanov commented on apps/afisha/serializers/event.py
> +from apps.library.serializers import EventMasterClassSerializer, EventPerformanceSerializer, EventReadingSerializer
Вот тут (и далее везде) в подобных исправлениях:

> Вот это всё можно просто исключить из коммита.
> Если правильно понимаю pre-commit пропустит ок.
> 
> Это следствия увеличенной длины строки в 120 символов и что black переформатирует.
> Я правлю только в тех файлах которые редактирую.

2021-12-25 20:35 UTC, nkiryanov commented on apps/users/admin.py
> +admin.site.index_template = "admin/base_site.html"
Не знал, что `admin.site.site_header` вообще сработает. Любопытно 👍 

Мне кажется `admin.site.site_header` нужно как минимум в core перенести, а максимум [сделать по гайду](https://docs.djangoproject.com/en/4.0/ref/contrib/admin/#overriding-the-default-admin-site). По это логике у нас должен быть отдельный файлик admin.py в папке config

`admin.site.index_template` нужен ли вообще?
Если правильно понимаю наличие этого файла в папке templates уже переопределяет его для админки. Нет необходимости явно указывать. Но могу ошибаться.

P.S.
Видать пропустил как у нас ProxyUsers появились. Думаю что они лишние. Но это к рефакторингу относится. Если работают, то класс. Создам карточку, на будушее.

2021-12-25 20:35 UTC, nkiryanov commented on templates/admin/base_site.html
> +     <img  src="{% static 'logo.png' %}" alt="logo" width="70px" height="58px">
👍

2021-12-26 16:31 UTC, Polinavas95 commented on config/settings/base.py
> +        "DIRS": [TEMPLATES_DIR, "templates/"],
хорошо, я уберу

2021-12-26 17:41 UTC, Polinavas95 commented on apps/users/admin.py
> +admin.site.index_template = "admin/base_site.html"
Все перенесла. Без index_template работает, просто немного изображение меняется. Но я перенесла в core

2021-12-27 19:40 UTC, AntonZelinsky approved these changes

2021-12-27 19:42 UTC, AntonZelinsky approved these changes
Меня немного смутило то, что файл с логотипом лежит в приложении юзеров, лучше в кор мереместить 
apps/users/static/logo.png

2021-12-28 05:49 UTC, nkiryanov commented
Вроде нужно забрать изменения из develop ещё.


Логотип сохранен в статике приложения пользователей. Он там найдется, но он относится к другому приложению. Нужно переместить же.

2021-12-28 18:16 UTC, nkiryanov approved these changes

2021-12-29 09:03 UTC, merged