Feature/add more info to authors
Studio-Yandex-Practicum/Lubimovka_backend pull request #140
Opened 2021-12-28 17:00 UTC by Omnomus

В фабрику авторов внесены изменения - теперь авторы создаются с бОльшим количеством информации - связанных ссылок, ссылок на социальные сети, пьес и прочих пьес.

2021-12-28 18:14 UTC, nkiryanov requested changes
Есть небольшие замечания.

В целом же то, что нужно, класс!
Теперь понятно на что увлеклась и на созвон попозже подключилась ;)

2021-12-28 18:14 UTC, nkiryanov commented on apps/library/tests/factories/author.py
> +SocialNetwork_choices = [x[0] for x in SocialNetworkLink.SocialNetwork.choices]
Нравится, что позаботилась чтоб стало понятнее ;) 👍 
Что кажется нужно тут подправить:
1. Думаю этой конструкции лучше жить в класс фабрики. Так понятнее к чему она относится. Если думаешь иначе напиши plz
2. Если это константа, то должна быть капсом написана, если переменная, то snake_case
3. А нам случае варианты из .choices, .labels, .values, and .names не подходят? Может быть красивее можно и проще сделать?

2021-12-28 18:14 UTC, nkiryanov commented on apps/library/tests/factories/author.py
> +            achievement_count = extracted
Если меняем поведение атрибута, то и называть бы атрибут по другому. add_achievement звучит так, что ждет только True или False, а на самом деле int.

Где-то такое уже правили.

2021-12-28 18:14 UTC, nkiryanov commented on apps/library/tests/factories/author.py
> +            add_achievement=3, add_social_network_link=3, add_other_link=3, add_other_play=3, plays__num=3
Вот тут переносишь на новую строку (в строку с return не помещается) и лучше сделать в виде как было. Чтоб так случилось нужно запятую добавить если что (и black сам подправит).

2021-12-28 18:39 UTC, Omnomus commented on apps/library/tests/factories/author.py
> +SocialNetwork_choices = [x[0] for x in SocialNetworkLink.SocialNetwork.choices]
1.  В фабрику не надо - фабрика будет ругаться, что у модели такого поля нет, лучше прям над ней оставить
2. Поменяла на снэйк)
3.  Я тут немного растерялась вот с этим: FACEBOOK = "fb", _("Facebook") - я его как тюпл восприняла. Не совсем поняла, как варианты из .choices, .labels, .values, and .names использовать?

2021-12-28 18:39 UTC, Omnomus commented on apps/library/tests/factories/author.py
> +            achievement_count = extracted
Да, согласна, поменяла везде

2021-12-28 18:44 UTC, Omnomus commented on apps/library/tests/factories/author.py
> +            add_achievement=3, add_social_network_link=3, add_other_link=3, add_other_play=3, plays__num=3
сделано

2021-12-28 21:54 UTC, elisey approved these changes

2021-12-29 09:18 UTC, AntonZelinsky approved these changes

2021-12-29 09:18 UTC, AntonZelinsky commented on apps/library/tests/factories/author.py
> +    def add_several_achievement(self, created, count, **kwargs):
Можно было several не передавать, оно и так из логики следует, если туда count передаётся. И если уже есть several, то должно быть не achievement, а achievements

2021-12-29 09:18 UTC, AntonZelinsky commented on apps/library/tests/factories/author.py
> +social_links_choices = [x[0] for x in SocialNetworkLink.SocialNetwork.choices]
Называть переменные x, в 99% случаев не стоит. Я понимаю, что тут генератор и можно догадаться, если посмотреть на то, что перебирается, но всё же — это плохой стиль кода

2021-12-29 09:36 UTC, nkiryanov commented on apps/library/tests/factories/author.py
> +SocialNetwork_choices = [x[0] for x in SocialNetworkLink.SocialNetwork.choices]
По 3. [вот описание](https://docs.djangoproject.com/en/4.0/ref/models/fields/#enumeration-types) в документации

enum типы это класс в Python со своим удобным API. То есть мы получаем кортежи с помощью .SocialNetwork.choices, но по-моему то что хотим в x[0] можем получить с names/labels/ или values

Тогда вот это SocialNetwork_choices = [x[0] for x in SocialNetworkLink.SocialNetwork.choices] - не нужно будет

2021-12-29 09:47 UTC, Omnomus commented on apps/library/tests/factories/author.py
> +    def add_several_achievement(self, created, count, **kwargs):
убрала several

2021-12-29 09:48 UTC, Omnomus commented on apps/library/tests/factories/author.py
> +social_links_choices = [x[0] for x in SocialNetworkLink.SocialNetwork.choices]
поменяла на link

2021-12-29 14:09 UTC, Omnomus commented on apps/library/tests/factories/author.py
> +SocialNetwork_choices = [x[0] for x in SocialNetworkLink.SocialNetwork.choices]
спасибо))

2021-12-29 21:34 UTC, nkiryanov approved these changes
Оставшиеся мои пожелания будут только из разряда вкусовщины и не пишу.

В целом же общее впечатления от того что получилось **сильно** выше среднего. Класс! Спасибо 👍

2021-12-29 23:12 UTC, merged