Bugfix/festival end date before start date
Studio-Yandex-Practicum/Lubimovka_backend pull request #148
Opened 2022-01-12 08:58 UTC by Omnomus

Добавила clean() в модель Фестиваля - проверяем, что дата окончания больше даты начала фестиваля (при их наличии)

2022-01-12 09:34 UTC, nkiryanov requested changes
Ок. Написал как решить задачу в более полном объёме/системнее. Это не сложно, давай сразу сделаем.

2022-01-12 09:34 UTC, nkiryanov commented on apps/info/models.py
> +    def clean(self):
Это ок. Но метод clean вызывается только при работе в формах.
То есть ничто не помешает мне создать объект руками / в коде.

Этот недостаток устраняется через constraints. Давай добавим.
+ вызывать clean при методе save().

Про обе эти штуки в [стайлгайде](https://github.com/HackSoftware/Django-Styleguide#validation---clean-and-full_clean) хорошо и понятно написано.

2022-01-12 10:13 UTC, Omnomus commented on apps/info/models.py
> +    def clean(self):
стайлгайд преладагает -вызывать clean при методе save().- выносить в сервис (во вью?..), а у нас вообще RetrieveAPIView. Нужно это вообще?

2022-01-12 10:47 UTC, nkiryanov commented on apps/info/models.py
> +    def clean(self):
Как связаны RetrieveAPIView и сохранение объектов? Retrieve никак на объекты не влияет. У нас форма в админке, а это не RetrieveAPIView

Нужно прочитать, усвоить, переварить и скомпелировать лучшее решение на основе того, что есть у нас, что предлагают и что хотим получить 😅

2022-01-12 21:21 UTC, nkiryanov approved these changes
Вроде ок. Только не понял почему при сохранении вызываем clean, а не full_clean 🤔

2022-01-12 21:21 UTC, nkiryanov commented on apps/info/models.py
> +        self.clean()
Это сработает, но почему не full_clean()? Так в стайлгайде (вроде), да и по логике он должен быть.

2022-01-13 09:02 UTC, Omnomus commented on apps/info/models.py
> +        self.clean()
из док-и:  https://docs.djangoproject.com/en/4.0/ref/models/instances/#validating-objects  - full_clean() вызывает clean_fields(), clean(), и validate_unique(). Так как мы не переопределили clean_fields() и validate_unique(), посчитала, что будет избыточно и не так наглядно. 
Хотела написать, что разницы не будет, но при запуске фабрик на чистой базе full_clen() нашел баг в фабриках)) меняю, тестирую и делаю мерж.

2022-01-13 15:33 UTC, Omnomus commented on apps/info/models.py
> +        self.clean()
need help)) суть вопроса - full_clean() вызывает в том числе clean_fields(). и он валидируя поля start_date, end_date вызывает такую вот ошибку (см. скрин). 
можно вызывать clean_field c exclude=[start_date, end_date], но такое решение кажется обходом теста. 
предлагаю оставить только clean()
<img width="867" alt="Снимок экрана 2022-01-13 в 12 20 53" src="https://user-images.githubusercontent.com/78786450/149359978-48862d3f-d974-46a5-829d-3169edbbc471.png">

2022-01-13 18:51 UTC, nkiryanov commented on apps/info/models.py
> +        self.clean()
Так это тесты скорее поправить нужно или фабрику подправить. По-моему в там проблема. В базе данных хранится всё верно — отдается объект datetime.

Сможешь сама посмотреть или мне подробнее посмотреть?

2022-01-13 19:18 UTC, Omnomus commented on apps/info/models.py
> +        self.clean()
дай мне день, завтра если не разберусь, призову на помощь

2022-01-14 12:09 UTC, Omnomus commented on apps/info/models.py
> +        self.clean()
в тесте с датами немного подкрутила

2022-01-14 17:32 UTC, nkiryanov approved these changes
👍

2022-01-14 18:21 UTC, merged