create: PerformanceMediaReview, PerformanceReview
Studio-Yandex-Practicum/Lubimovka_backend pull request #16
Opened 2021-09-28 21:00 UTC by AnnaKPolyakova

1) PerformanceMediaReview
2) PerformanceReview
3) add models to admin

2021-09-28 22:14 UTC, nkiryanov requested changes
Есть небольшие штрихи

2021-09-28 22:14 UTC, nkiryanov commented on apps/library/models.py
>          verbose_name_plural = "Медиа отзывы на спектакль"
- [ ] Не хватает проверки на уникальность.
- [ ] Метод `__str__` нужная штука

2021-09-28 22:14 UTC, nkiryanov commented on apps/library/models.py
> +    url = models.URLField(
Думаю ссылка должна быть уникальной для отзывов

2021-09-28 22:14 UTC, nkiryanov commented on apps/library/models.py
>          verbose_name_plural = "Отзывы зрителей на спектакль"
Не вижу `__str__`, давай добавим?

2021-09-28 22:14 UTC, nkiryanov commented on apps/library/models.py
> +    name = models.CharField(
В целом ок и оставлю решение за тобой.
Мне не оч нравится name, так как будто это название отзыва, а не зрителя который его оставил.

Может быт reviewer_name ?
Но не наставиваю

2021-09-28 22:14 UTC, nkiryanov commented on apps/library/models.py
> +    def __str__(self):
👍

2021-09-29 12:32 UTC, nkiryanov approved these changes
Замечаний нет, думаю можем мерджить.

2021-09-29 13:03 UTC, DRAGANmik approved these changes

2021-09-29 15:22 UTC, nkiryanov commented on apps/library/models.py
> +    pub_date = models.DateTimeField(
Решили, что дата отзыва может отличаться от даты создания в системе. Оставляем поле.

2021-09-29 15:22 UTC, nkiryanov commented on apps/library/models.py
> +    pub_date = models.DateTimeField(
Решили, что дата отзыва может отличаться от даты создания в системе. Оставляем поле.

2021-09-29 15:22 UTC, merged