hide models from admin page
Studio-Yandex-Practicum/Lubimovka_backend pull request #160
Opened 2022-01-18 09:45 UTC by DRAGANmik

___

**Было(присутствуют блоки и элементы конструктора)**
___

![Администрирование_сайта___Административный_сайт_Django_-_Google_Chrome_2022-01-18_12-32-00](https://user-images.githubusercontent.com/75855531/149911675-68a8c9a1-c33d-4ed3-bbde-f253adbb3141.gif)
___
___
___

**Стало**
___

![Администрирование_сайта___Административный_сайт_Django_-_Google_Chrome_2022-01-18_12-32-32](https://user-images.githubusercontent.com/75855531/149911904-104d7b48-6935-49ea-ad6b-74eff39a5367.gif)

Когда создаёте PR, убедитесь, что:

- [ ] вы проверили обновления в [брифе](https://www.notion.so/00f5d5a6d39e426fa1ea7ab69b694f07)
- [ ] синхронизировали изменения кода с [ER-диаграммой базы данных](https://drive.google.com/file/d/1RCIPaEgaLUSqek3znd38VPCKSzOlmJFy/view) связей моделей
- [ ] убедились, что модель OpenAPI проверена (в Swagger отображаются изменения)
- [ ] тесты все пройдены и нет конфликтов
- [ ] созданы необходимые миграции

Когда ваш PR смержен:

- [ ] если у вас были изменения в API, сообщите об этом команде Фронта, им это важно знать!

2022-01-18 15:12 UTC, nkiryanov requested changes
Подход ок, только давай миксином сделаем, а не кастомным классом админки.

2022-01-18 15:12 UTC, nkiryanov commented on apps/core/mixins.py
> +class ModelAdminToHide(admin.ModelAdmin):
Сейчас получился не миксин, а полноценная модель админки. Это не совсем удобно: такое сложнее расширять/коммбинировать с другими сущностями.

Давай сделаем именно миксином. Сделать так же как и любой другой миксин: не нужно наследоваться от модели админки. Просто класс с методом. Будет миксин.

Подходящим название будет "HideOnNavPannelAdminModelMixin". Как-то у этом духе.

2022-01-19 12:51 UTC, AntonZelinsky approved these changes

2022-01-19 12:53 UTC, AntonZelinsky commented
А у нас удаляются блоки и файлы при удалении их из страницы конструктора?

2022-01-22 23:15 UTC, merged