bugfix/festivalteams-validatie
Studio-Yandex-Practicum/Lubimovka_backend pull request #171
Opened 2022-01-22 21:06 UTC by BolshakovAndrey

Когда создаёте PR, убедитесь, что:

- [ ] вы проверили обновления в [брифе](https://www.notion.so/00f5d5a6d39e426fa1ea7ab69b694f07)
- [ ] синхронизировали изменения кода с [ER-диаграммой базы данных](https://drive.google.com/file/d/1RCIPaEgaLUSqek3znd38VPCKSzOlmJFy/view) связей моделей
- [ ] убедились, что модель OpenAPI проверена (в Swagger отображаются изменения)
- [ ] тесты все пройдены и нет конфликтов
- [ ] созданы необходимые миграции

Когда ваш PR смержен:

- [ ] если у вас были изменения в API, сообщите об этом команде Фронта, им это важно знать!

2022-01-22 23:36 UTC, AntonZelinsky requested changes

2022-01-22 23:36 UTC, AntonZelinsky commented on apps/info/models.py
> +        null=True,
Разве миграции не нужно создать после изменения модели?

2022-01-22 23:36 UTC, AntonZelinsky commented on apps/info/models.py
> +        null=True,
И странная комбинация из свойств, пустым не может быть, а null может быть.

2022-01-23 18:55 UTC, AntonZelinsky approved these changes

2022-01-24 15:05 UTC, kr0t approved these changes

2022-01-24 15:05 UTC, merged