Каркас приложения
Studio-Yandex-Practicum/Lubimovka_backend pull request #2
Opened 2021-09-14 22:59 UTC by nkiryanov

Каркас приложения.
Общее описание в README

2021-09-14 23:58 UTC, AntonZelinsky requested changes

2021-09-14 23:58 UTC, AntonZelinsky commented on README.md
> +Тестов нет, но есть настройки для ускорения тестов + настройки для запуска unittest через pytest (удобно в vscode)
Нужно добавить какие-то правила для внесения изменений в проект. Например, как называть ветки, что одна миграция в один ПР, как создавать ПР и что делать с фидбеками...
Подумайте, что ещё стоит добавить. Завтра на митинге обсудим.

2021-09-14 23:58 UTC, AntonZelinsky commented on apps/core/models.py
> +class TimeStampedModel(models.Model):
Назови BaseModel.
Позже, мы добавим сюда свойства кто создал и отредактировал модель. Их можно и сейчас добавить, но будет доставлять недобства, так как станет обязательной авторизация, а на начальном этапе будет удобно без её.

Так же, скорее всего сюда добавится свойства для поддержки паттерна soft delete.

2021-09-14 23:58 UTC, AntonZelinsky commented on local.yaml
> +version: '3.8'
Не самое понятное имя файла, тут явно не ожидаешь увидеть это

2021-09-15 00:10 UTC, nkiryanov commented on apps/core/models.py
> +class TimeStampedModel(models.Model):
Название поправил 👍

2021-09-15 00:19 UTC, nkiryanov commented on local.yaml
> +version: '3.8'
Согласен. Поправил на **postgres-local.yaml**. Название не оч нравится, если будут идеи лучше готов поддержать 😀

Есть ещё идея убрать в отдельную папку compose, но получается слишком сложно. Лучше так сделать, если будет много docker-compose файлов.

2021-09-15 00:20 UTC, nkiryanov commented on README.md
> +Тестов нет, но есть настройки для ускорения тестов + настройки для запуска unittest через pytest (удобно в vscode)
Согласен, но до завтрашней встречи сам не успею сформулировать.
Предлагаю добавить после митинга.

2021-09-15 18:49 UTC, nkiryanov commented on README.md
> +Тестов нет, но есть настройки для ускорения тестов + настройки для запуска unittest через pytest (удобно в vscode)
@AntonZelinsky вот это пока закрыть не могу. Хотел выделить в отдельную задачу в notion, но пока не могу (нет прав). Предлагаю пометить как resolved и закрыть PR, чтоб ребята могли клонировать и с чем-то работать.

Заглушку в README добавил.

2021-09-15 22:17 UTC, AntonZelinsky approved these changes

2021-09-15 22:18 UTC, merged