Добавлена модель автора и связанные с ней модели: …
Studio-Yandex-Practicum/Lubimovka_backend pull request #21
Opened 2021-10-02 12:35 UTC by nicefme

ссылки, другие пьесы, достижения

2021-10-02 14:14 UTC, nkiryanov requested changes
Есть, что поправить, но многое выглядит хорошо проработанным 👍

2021-10-02 14:14 UTC, nkiryanov commented on apps/library/models.py
>          verbose_name_plural = "Авторы"
В целом PR приму из без этого, но сейчас есть проблема — можно сохранить автора с персоной у которой не будет email, фото и прочее (поля необязательные для заполнения). По хорошему это тоже решить.

Ну или оставить когда будем писать API. Предполагаю что станет нагляднее почему это нужно и в каком слое реализовывать.

2021-10-02 14:14 UTC, nkiryanov commented on apps/library/models.py
> +        Person, on_delete=models.CASCADE, verbose_name="Автор"
Может быть несколько авторов с одной персоной?

2021-10-02 14:14 UTC, nkiryanov commented on apps/library/models.py
> +        related_name="author_otherplayslinks",
См. выше

2021-10-02 14:14 UTC, nkiryanov commented on apps/library/models.py
> +        related_name="author_authorsplayslinks",
related_name удобнее использовать другой. Это имя будешь использовать когда из другой модели выбираешь всех авторов. Достаточно просто authors

Что понятнее и удобнее?

`some_play.author_authorsplayslinks.all()` или `some_play.authors.all()`?

2021-10-02 14:14 UTC, nkiryanov commented on apps/library/models.py
> +    author = models.ForeignKey(
Уникальность

2021-10-02 14:14 UTC, nkiryanov commented on apps/library/models.py
> +    anchored = models.BooleanField(
is_pinned — закрепить вверху страницы обычно "pin" называют. Так в TG и Slack

2021-10-02 14:14 UTC, nkiryanov commented on apps/library/models.py
> +        help_text="Не более 40 символов",
👍

2021-10-02 14:14 UTC, nkiryanov commented on apps/library/models.py
> +        related_name="author_socialnetworklinks",
См. про related_name ниже

2021-10-02 16:16 UTC, nkiryanov requested changes
Не все правки из прошлого ревью отработаны. Буду признателен, если будешь им всем внимание уделять.

+ сделал доп. правки. Урок для себя усвоил — в следующий раз буду отдельно помечать, если одну штуку везде проверить :)

2021-10-02 16:16 UTC, nkiryanov commented on apps/library/admin.py
> +    list_display = ("id", "person", "quote", "biography")
Актуально!

2021-10-02 16:16 UTC, nkiryanov commented on apps/library/models.py
> +    author = models.ForeignKey(
Исправлено ниже, отлично!

2021-10-02 16:16 UTC, nkiryanov commented on apps/library/models.py
> +    serial_number = models.PositiveSmallIntegerField(
Актуально

2021-10-02 16:16 UTC, nkiryanov commented on apps/library/models.py
>          verbose_name_plural = "Ссылки на стороннии ресурсы"
Ссылка на соц. сеть проверяется на уникальность, а тут?

2021-10-02 16:16 UTC, nkiryanov commented on apps/library/models.py
> +        constraints = [
👍

2021-10-02 16:16 UTC, nkiryanov commented on apps/library/models.py
> +    person = models.ForeignKey(
Актуально

2021-10-02 16:16 UTC, nkiryanov commented on apps/library/models.py
>      person = models.ForeignKey(
Могут ли быть два автора с одной персоной?

2021-10-02 16:16 UTC, nkiryanov commented on apps/library/models.py
>          verbose_name_plural = "Авторы"
Не стал делать, ок.
Было бы здовро чтоб о решении в комментарии написал.

2021-10-02 17:28 UTC, nicefme commented on apps/library/admin.py
> +    LinkSocialNetwork,
Скорректировал

2021-10-02 17:28 UTC, nicefme commented on apps/library/admin.py
> +    list_display = ("id", "person", "quote", "biography")
Скорректировал

2021-10-02 17:28 UTC, nicefme commented on apps/library/models.py
> +LINK_CHOICES = (
Скорректировал

2021-10-02 17:29 UTC, nicefme commented on apps/library/models.py
> +    class Meta:
Скорректировал

2021-10-02 17:29 UTC, nicefme commented on apps/library/models.py
> +    person = models.ForeignKey(
Скорректировал

2021-10-02 17:30 UTC, nicefme commented on apps/library/models.py
> +        related_name="author_authorsplayslinks",
Скорректировал

2021-10-02 17:30 UTC, nicefme commented on apps/library/models.py
> +    anchored = models.BooleanField(
Скорректировал

2021-10-02 17:30 UTC, nicefme commented on apps/library/models.py
> +        help_text="Не более 40 символов",
👍

2021-10-02 17:33 UTC, nicefme commented on apps/library/models.py
>          verbose_name_plural = "Ссылки на стороннии ресурсы"
Добавил

2021-10-02 17:34 UTC, nicefme commented on apps/library/models.py
> +        constraints = [
👍

2021-10-02 17:36 UTC, nicefme commented on apps/library/models.py
>      person = models.ForeignKey(
Сделал персону уникальной

2021-10-02 19:42 UTC, nicefme commented on apps/library/models.py
>          verbose_name_plural = "Авторы"
Пока не придумал, как сделать поля Person обязательными в моделе Author, в сериализаторе будет проще реализовать, как мне кажется.

2021-10-02 20:05 UTC, nicefme commented on apps/library/models.py
> +        related_name="author_socialnetworklinks",
готово

2021-10-02 20:23 UTC, nkiryanov requested changes
Осталось совсем чуть-чуть.

2021-10-02 20:23 UTC, nkiryanov commented on apps/library/migrations/0003_otherplay_unique_play.py
> +        migrations.AddConstraint(
Миграции все нужно пересоздать. Чтоб они отражали все последние изменения в одной миграции, а не нескольких

Имею в виду не те которые были уже в репозитории (их трогать не нужно), а те, которые тобой создаются. Чтоб вместо 2-3 миграций была одна.

2021-10-02 20:23 UTC, nkiryanov commented on apps/library/models.py
> +    person = models.OneToOneField(
👍 

Сначала хотел сказать, что нужно unique=True, но согласен, что здесь связь 1 к 1
Класс!

2021-10-02 20:23 UTC, nkiryanov commented on apps/library/models.py
> +                name="unique_social_networ",
Орф. ошибочка.
У меня в vscode есть code spell checker — он проверят в том числе слова в таких переменных и подчеркивает, если что-то не так. Удобно. Рекомендую.

А вообще скорее всего есть какое-то расширение к flake которое будет такое проверять. Нужно поискать.

2021-10-02 20:43 UTC, AntonZelinsky commented on apps/library/models.py
> +        YOUTUBE = "ytube", _("YouTube")
Сокращения ytube, inst, tlgrm место экономят, но выглядят очень ломано. Если это не общепринятые сокращения, то смысла в них нет.

2021-10-02 20:46 UTC, nkiryanov commented on apps/library/models.py
>          verbose_name_plural = "Авторы"
Я закрою и сделаем позже. Но такие вещи как раз выносить в сериализатор плохая практика. Это относится к бизнес логике, а задача сериализатора в названии — сериализовывать и десериализировать объекты. + возможно в каком-то другом месте будем создавать объекты, минуя сериализтор и столкнемся с проблемами.

В общем такие вещи нужно выносить в модель или отдельный блок с бизнес правилами.

2021-10-02 21:09 UTC, AntonZelinsky requested changes

2021-10-03 08:50 UTC, nicefme commented on apps/library/migrations/0003_otherplay_unique_play.py
> +        migrations.AddConstraint(
ок 👍

2021-10-03 08:53 UTC, nicefme commented on apps/library/models.py
> +    person = models.OneToOneField(
Также думал и изначально сделал, но при миграциях вышла подсказка, что лучше OneToOneField))

2021-10-03 08:54 UTC, nicefme commented on apps/library/models.py
> +                name="unique_social_networ",
+

2021-10-03 08:56 UTC, nicefme commented on apps/library/models.py
> +        YOUTUBE = "ytube", _("YouTube")
![image](https://user-images.githubusercontent.com/75689966/135746719-e4825c62-67f9-40e9-a3cc-2f5440a3389d.png)

2021-10-03 10:57 UTC, nicefme commented on apps/library/models.py
>          verbose_name_plural = "Авторы"
Добавил метод clean в модель, для проверки полей email, image и city

2021-10-03 13:29 UTC, AntonZelinsky commented on apps/library/models.py
> +        YOUTUBE = "ytube", _("YouTube")
понял, окей, на твоё усмотрение

2021-10-03 13:29 UTC, nicefme commented on apps/library/admin.py
> +class SocialNetworkLinkAdmin(admin.ModelAdmin):
Скорректировал

2021-10-03 13:29 UTC, nicefme commented on apps/library/admin.py
> +class OtherLinkAdmin(admin.ModelAdmin):
Скорректировал

2021-10-03 13:35 UTC, AntonZelinsky commented on apps/library/admin.py
> +class SocialNetworkLinkAdmin(admin.ModelAdmin):
Посмотри на ПР Кости, он там уже исопльзовал инлайны в админке https://github.com/Studio-Yandex-Practicum/Lubimovka_backend/pull/23/files

2021-10-03 13:47 UTC, AntonZelinsky commented
@nicefme смержи себе ветку дев, чтобы исправить конфликты. А так же, в чат пришли скрины как теперь выглядят эти страницы админки

2021-10-03 13:51 UTC, AntonZelinsky approved these changes

2021-10-03 16:35 UTC, nkiryanov approved these changes

2021-10-04 17:45 UTC, merged