add pr-manager
Studio-Yandex-Practicum/Lubimovka_backend pull request #221
Opened 2022-02-03 04:47 UTC by stepakiselev

Когда создаёте PR, убедитесь, что:

- [ ] вы проверили обновления в [брифе](https://www.notion.so/00f5d5a6d39e426fa1ea7ab69b694f07)
- [ ] синхронизировали изменения кода с [ER-диаграммой базы данных](https://drive.google.com/file/d/1RCIPaEgaLUSqek3znd38VPCKSzOlmJFy/view) связей моделей
- [ ] убедились, что модель OpenAPI проверена (в Swagger отображаются изменения)
- [ ] тесты все пройдены и нет конфликтов
- [ ] созданы необходимые миграции

Когда ваш PR смержен:

- [ ] если у вас были изменения в API, сообщите об этом команде Фронта, им это важно знать!

2022-02-03 05:56 UTC, stepakiselev commented
Решил создать PR чтобы визуально видеть ошибки и продвинуться дальше. Вопрос: создавать галочку в модели FestivalTeam только для команды "art"? Если да. Можно это добавить в валидацию, но красивее наверно если галочка будет видна только у категории "art". Еще вопрос про ссылку на фейсбук, эту ссылку создать в модели setting? если да то тогда такие данные добавляю через миграции?

2022-02-03 11:01 UTC, KonstantinRaikhert commented on apps/info/serializers/press_release.py
> +            return "Нет PR-менеджера"
А вот тут странно. То есть в ключе pr_manager отобразится: нет PR-менеджера. Не уверен, что фронт сможет правильно обработать. Может убирать ключ, если нет такового? Может стоит у них спросить

2022-02-03 11:06 UTC, KonstantinRaikhert commented
Было бы хорошо, если карточка будет видна только в art. И это легко сделать через jquery. Можно посмотреть как реализовано в partners. По фейсбуку немного не в контексте. Нужно мне посмотреть

2022-02-03 11:51 UTC, kr0t commented
> Решил создать PR чтобы визуально видеть ошибки и продвинуться дальше. Вопрос: создавать галочку в модели FestivalTeam только для команды "art"? Если да. Можно это добавить в валидацию, но красивее наверно если галочка будет видна только у категории "art". Еще вопрос про ссылку на фейсбук, эту ссылку создать в модели setting? если да то тогда такие данные добавляю через миграции?

Для ссылки на фотогалерею на фейсбуке, я сделал отдельный ПР, он сейчас висит на ревью. Делать это не надо.

2022-02-03 16:09 UTC, AntonZelinsky requested changes

2022-02-11 18:11 UTC, KonstantinRaikhert commented on apps/info/serializers/press_release.py
> +        return PhotoGalleryLinkSerializer(items[0]).data
Лучше использовать вместо items[0] first() 
item = Setting.objects.filter(settings_key="photo_gallery_facebook").values("url").first()

2022-02-11 18:11 UTC, KonstantinRaikhert commented on apps/info/serializers/press_release.py
> +        items = Setting.objects.filter(settings_key="press_release_data").values("text")
В трех методах обнаружил item, items 
Может как то более информативные дать названия переменным?

2022-02-11 18:11 UTC, KonstantinRaikhert commented on apps/info/models.py
> +            manager = Person.objects.filter(festivalteam__is_pr_manager=True)
тут тоже лучше first

2022-02-11 18:11 UTC, KonstantinRaikhert commented on apps/info/models.py
> +        # self.full_clean()
закоменченый код)

2022-02-11 18:11 UTC, KonstantinRaikhert commented on apps/info/models.py
> +            new_data = data[0]
first?

2022-02-11 18:11 UTC, KonstantinRaikhert commented on apps/info/admin.py
> +            {  # всплывают два этих поля, если выбирается поле "team" = "art"
Я думаю сейчас твою ветку в тестовый стэйджинг отправим и посмотрим как это работает. Надеюсь стянул последние обновления с develop?)

2022-02-11 18:11 UTC, KonstantinRaikhert commented on apps/info/admin.py
> +                # где и как лучше сделать проверку на пустую строку?
Тебя смущает что в методе save?

2022-02-11 18:11 UTC, KonstantinRaikhert commented on apps/info/admin.py
> +    # добавил новую форму, где добавил одно поле
Перед мерджем все комментарии убрать)

2022-02-12 07:13 UTC, stepakiselev commented on apps/info/admin.py
> +                # где и как лучше сделать проверку на пустую строку?
да, тут я думал может есть способ эту проверку делать в методе clean чтобы ошибка показывалась в админке

2022-02-12 19:46 UTC, stepakiselev commented on apps/info/serializers/press_release.py
>          model = PressRelease
полностью переделать?

2022-02-12 19:55 UTC, stepakiselev commented
я добавил метод clean где при сохранение без изменений показывает: поле с данными о менеджере не заполнено. Ищу вариант как добавить в поле исходные данные initial, но не выходит так как поле из другой модели.

2022-02-13 11:13 UTC, KonstantinRaikhert commented
По поводу исходных данных в поле. Думаю тут должен помочь AJAX запрос в JS скрипте. Но для ajax еще необходимо написать вьюху с ендоинтом, куда он будет стучаться и получать данные, чем заполнить поле

2022-02-14 14:19 UTC, AntonZelinsky requested changes
Я ещё к сериализаторам и вьюшке вернусь, но чуть позже, там точно есть что улучшить!

2022-02-14 14:19 UTC, AntonZelinsky commented on apps/info/admin.py
> +            if form.is_valid():
Ты валидируешь формы только если  выбран ПР менеджер, если же нет, то сохраняешь сразу! Так точно быть не должно!!

2022-02-14 14:19 UTC, AntonZelinsky commented on apps/info/admin.py
> +        obj.save()
Логика размазана по всему приложению! Половину сохраняешь в моделях, половину в админке! Либо там, либо там! 
Поправь все фидбеки из модели и перенеси код сюда!

2022-02-14 14:19 UTC, AntonZelinsky commented on apps/info/form.py
> +    """Форма для команды-фестиваля."""
Не нравятся мне такие формы, уверен, что омжно сделать напрямую в модели админки, но переделка может ещё затянуть релиз ПРа. 
Удали ManagerForm и его свойство просто добавь в этот класс. Не стоит ещё больше усложнять!

2022-02-16 23:33 UTC, AntonZelinsky requested changes
Оказалось, что логика отдачи данных о ПР менеджере находится не в той АПИ!!! в фидбеках хорошо описано.

Когда будешь переделывать сериализатор, то поля касающиеся страницы пьесы и вложеного ПР менеджера вынеси в отдельный блок, чтобы три поля были объеденины в отдельный объект и сразу было понятно, к чему он относится. _Пример будет ниже._
Зелёной же стрелочкой я выделил свойство, которое тебе нужно будет внести в тот же эндпоинт, на уровне for_press с именем photo_gallery_facebook_link. У нас уже есть [вьюшка ](https://github.com/Studio-Yandex-Practicum/Lubimovka_backend/blob/develop/apps/info/views/press_release.py#L38) которая отдаёт его, но её нужно будет удалить. Скорее всего и сериализатор. Об этом тоже нужно будет сообщить команде фронта.
```
{
        ...
	"for_press": {
		"pr_manager": {
			"name": "Аня",
                        "email": ".@..",
                        "photo_link":"http"
		},
		"photo_gallery_facebook_link": "https:"
	}
}
```
![image](https://user-images.githubusercontent.com/1431279/154373187-8bafb79d-c2b2-4808-b5f2-b7281f913731.png)

2022-02-16 23:33 UTC, AntonZelinsky commented on apps/info/serializers/press_release.py
> +    url = serializers.URLField()
И между прочим, ты очень нагло поменял сериализатор, который уже используется в [другом апи](https://github.com/Studio-Yandex-Practicum/Lubimovka_backend/blob/develop/apps/info/views/press_release.py#L38). 
Если ты это умышлено сделал и собирался сказать команде фронта, что поменялось поле в таком-то месте, то вопросов нет. Но поскольку ты просто поменял поле и использовал у себя этот сериализатор, то полагаю, что этого ты не планировал сделать.(

В какой-то момент, мог бы быть скандал с фронтом из-за этого!

2022-02-16 23:33 UTC, AntonZelinsky commented on apps/info/serializers/press_release.py
> +        return ManagerDataSerializer(text).data
Я даже боюсь представить вложенность всех этих структур 0_о. Нужно было просто возвращать значения

2022-02-16 23:33 UTC, AntonZelinsky commented on apps/info/serializers/press_release.py
> +    name_manager = serializers.SerializerMethodField()
Использование SerializerMethodField это плохая идея! Они используются в качестве редчайшего исключения, когда нужна какая-то вариация данных. Старайся их вообще не использовать

2022-02-16 23:33 UTC, AntonZelinsky commented on apps/info/serializers/press_release.py
>  class PressReleaseSerializer(serializers.ModelSerializer):
Дошли у меня руки и до сериализаторов, держись!) Ты немного попадаешь под удар граблей, которые положил перед тобой другой разработчик), но тут ничего не сделаешь, раз ты влез в этот код, то прийдётся поправить!

Задача сериализаторов, как глупо это бы не звучала, сераилизировать модели! И всё! А вот вьюшки или сервисы вызываемые этими вьюшками должны получать данные и отдавать в сериализаторы.
Если посмотреть на этот сериализатор, то он делает огромное количество раобты, которую не должен делать. Тому что происходит в этом файле, есть очень много нарицательных названий в программировании поэтому мы попробуем всё переделать.

Для начала, необходимо всю логику вынести [во вью класс](https://github.com/Studio-Yandex-Practicum/Lubimovka_backend/blob/develop/apps/info/views/press_release.py#L14). Сейчас, он наследуется от GenericViewSet и RetrieveModelMixin, что не позволяет написать код хорошо поэтому прийдётся поменять родителей класса. Как пример, классы ниже. Тебе нужно переопределить метод гет и в нём получать все данные, а потом их собрать в объект и отправить в сериализатор. 

**А вообще, стоп!!**
Почему у тебя пресс-релиз начал отвечать за получение информации о контактном лице?
Потому что на одной странице? И что? Так пользователь может просмотреть 10 различных пресс-релизов и что, нужно все 10 раз обновить данные о контактном лице? нет! Для этого делается отдельный АПИ, который будет загружаться один раз. 

Мы как-то обсуждали, что всю эту информацию будем сохранять в [feedback api](https://github.com/Studio-Yandex-Practicum/Lubimovka_backend/blob/develop/apps/info/views/feedback.py), поэтому, тебе нужно только там добавить загрузку необходимых тебе полей и добавить их в сериализатор и всё!

![image](https://user-images.githubusercontent.com/1431279/154371262-eec3c5af-6d69-42a0-9871-42470762d161.png)

Если посмотреть на код вью и сериализатора до твоих изменений и той задачи которую он выполнял, то в целом, это хороший код, я не на то наговаривал, но решил не удалять сообщение, так как может быть, какой-то урок да будет вынесен..

2022-02-16 23:33 UTC, AntonZelinsky commented on apps/info/serializers/press_release.py
> +        model = Person
Это очень плохой сериализатор! он наследуется не понятно от чего и зачем!
```
        return ManagerSerializer(
            item,
            fields=(
                "image",
                "email",
            ),
        ).data
```
Этим кодом ты вызываешь этот сериализатор и сообщаешь ему, что нужно взять только эти два поля из модели. Спрашивается, зачем нужно наследоваться от ModelSerializer? сделать обычный Serializer, задай руками необходимые поля и всё, и твой код и код выполняемый джанго станет в разы проще. 
А насчёт DynamicFieldsModelSerializer это отдельная история. Если добавляешь такой сложный код, то нужно сделать развёрнутый комментарий зачем это делать. Может я и не прав и он нужен тут, но я в это не уверен и буду услышать твоё мнение

2022-02-17 20:28 UTC, stepakiselev commented
@AntonZelinsky правки внес, но не совсем уверен что все верно. Будьте добры проверьте еще раз)))

2022-02-18 15:54 UTC, AntonZelinsky reviewed
Молодец, вот сейчас красивые сериализаторы.

По коду вопросов нет, но есть вопросы по логике работы, которые вылезли при тестировании твоей задачи.

1. Снять ПР менеджера с должности не назначив другого нельзя, всё верно, но можно удалить его и должность будет освобождена. Как следствие, эндпоинт с фидбеком упадёт!
2. Можно так же снять с должности менеджера, поменяв тип команды на команду фестиваля и заменив человека. Но это очень сложный кейс и его будет сложно отловить и воспроизвести, хотя и возможно. Думаю, наши QA его быстро найдут.
3. При правильно заполненных данных, в апи не приходит ссылка на фото. _Ты проверял работоспособность АПИ?_
4. После сохранения ПР-менеджера, не подгружается имя в дательном падеже и сохранить запись не получается, нужно заново вводить имя.
5. Настройка **Данные о PR-менеджере на странице для прессы** выглядит белой вороной в списке настроек, её нужно переименовать в **Имя PR менеджера на странице для прессы (в дательном падеже)**. Хочется дать чуть больше информации, но она не будет влазить на страницу проекта.( А я говорил, что нужно поле Имя и описание, чтобы в описание давать больше информации в случае необходимости.

2022-02-18 15:54 UTC, AntonZelinsky commented on apps/info/serializers/feedback.py
> +    photo_link = serializers.ImageField(max_length=None, use_url=True, source="image")
Ссылку.

2022-02-18 15:54 UTC, AntonZelinsky commented on apps/info/serializers/feedback.py
> +    name = serializers.CharField(max_length=100)
В форме максимальная длинна 60, тут 100. Нужно какое-то однообразие. Думаю, 60 должно быть достаточно

2022-02-18 15:54 UTC, AntonZelinsky commented on apps/info/serializers/feedback.py
> +    photo_link = serializers.ImageField(max_length=None, use_url=True, source="image")
Комент не забудь удалить и в коде лучше ничего не спрашивать, всегда пиши в чате. Ведь если этот комент не заметят и вмержут, то потом, через год, какой-нибудь разработчик найдёт такой артефакт и будет гадать, что это значит и зачем оно нужно!

2022-02-18 15:54 UTC, AntonZelinsky commented on apps/info/views/feedback.py
> +                "photo_gallery_facebook_link": photo_gallery_facebook_link,
Тут, конечно, лучше сделать более прямую структуру объектов, чтобы было видно какие поля куда записываются и было без `pr_manager["name"] = pr_manager_name`

2022-02-19 16:56 UTC, stepakiselev commented on apps/info/serializers/feedback.py
> +class PhotoManagerSerializer(serializers.ModelSerializer):
Не могу разобраться как вывести абсолютный урл картинки.
 Делаю в сериализоторе поле: pr_manager_photo_link = serializers.URLField() 
выдает:"pr_manager_photo_link": "images/person_avatars/DSC_1439.JPG”, 
Пробую через serializers.ImageField()
Выдает: "pr_manager_photo_link": null,

2022-02-19 16:58 UTC, stepakiselev commented on apps/info/serializers/feedback.py
>  class FeedbackSerializer(serializers.Serializer):
Слова с прошлого ревью ("сделать более прямую структуру объектов") воспринял как убрать вложенность в объект “for_press”.

2022-02-19 17:02 UTC, stepakiselev commented
@AntonZelinsky 
По замечанию: "После сохранения ПР-менеджера, не подгружается имя в дательном падеже и сохранить запись не получается, нужно заново вводить имя.”

Для этого надо как-то подгружать в форму данные из модели Setting где хронятся данные в дательном падеже. Честно нужно время чтобы разобраться как это сделать. Тревожусь что мой ПР задерживает проект. сколько у меня есть времени разобраться в этом?

2022-02-19 18:41 UTC, AntonZelinsky commented
Всё нормально, время есть, но если есть возможность уделить чуть больше времени, то будет круто.
Добавить значения форму не сложно, и гуглится очень быстро

2022-02-19 18:47 UTC, AntonZelinsky commented on apps/info/serializers/feedback.py
>  class FeedbackSerializer(serializers.Serializer):
Не, с сериализаторами было всё норм. Мне не очень нравилась такая структура и я криво описал что хотел)
 ```
     pr_manager = Person.objects.filter(festivalteam__is_pr_manager=True).values("image", "email").first()
        pr_manager["name"] = pr_manager_name
```
Я хотел так поменять структуру json

   ```
         "photo_gallery_facebook_link": photo_gallery_facebook_link,
            "for_press": {
                "pr_manager": {"pr_manager_name": pr_manager_name, "pr_manager_image": pr_manager["image"] ...},
                "photo_gallery_facebook_link": photo_gallery_facebook_link,
```

2022-02-19 23:26 UTC, AntonZelinsky commented on apps/info/serializers/feedback.py
> +class PhotoManagerSerializer(serializers.ModelSerializer):
У нас огромное количество апи отдающих полный урл, пощёлкай [апишку ](https://stage.dev.lubimovka.ru/api/v1/schema/swagger-ui/)и посмотри кто и что отдаёт

2022-02-19 23:29 UTC, AntonZelinsky commented
P.S.: Я писал про удаление [этого апи](https://github.com/Studio-Yandex-Practicum/Lubimovka_backend/blob/develop/apps/info/views/press_release.py#L38), ты забыл

2022-02-20 01:07 UTC, nkiryanov commented on apps/info/serializers/feedback.py
> +class PhotoManagerSerializer(serializers.ModelSerializer):
90% не передал контекст в сериализатор. Пример в main или [вот тут](https://github.com/Studio-Yandex-Practicum/Lubimovka_backend/blob/66eb708a41c30fecc9739223e946d923d2b80ff7/apps/articles/views/blog_items.py#L82)

2022-02-23 20:14 UTC, AntonZelinsky approved these changes
Если ПР-менеджеру поменять тип команды на просто «Команда фестиваля», то член команды фестиваля останется ПР-менеджером. 
Это баг, но я предлагаю пустить ПР без него, так как он очень долго ждёт мержа. QA в первой итерации обнаружат его и тогда будем думать.)
![image](https://user-images.githubusercontent.com/1431279/155400010-762b2062-835f-4d26-a3e0-68dae469c2fd.png)

2022-02-24 22:24 UTC, AntonZelinsky approved these changes

2022-02-24 22:24 UTC, AntonZelinsky commented on apps/info/form.py
> +            pr_manager_name = Setting.objects.filter(settings_key="pr_manager_name").first()
У нас для этого есть специальный метод **Setting.get_setting**

2022-02-24 22:24 UTC, merged