Feature/google sheets
Studio-Yandex-Practicum/Lubimovka_backend pull request #225
Opened 2022-02-05 15:30 UTC by Omnomus

Экспорт новых заявок на участие в Гугл-таблицу + добавлено поле Год фестиваля у модели Заявки. Примерный вид таблицы:
<img width="1230" alt="Снимок экрана 2022-02-05 в 18 21 53" src="https://user-images.githubusercontent.com/78786450/152647792-e62acafe-c05e-42b8-beb9-91654e5e8b4e.png">

2022-02-05 17:21 UTC, KonstantinRaikhert approved these changes
Я думал будет очень сложно. Но смотришь вроде все легко) Классно. Не забыть бы переменные добавить. А еще, может потестим? На тестовом пайплайне. Посмотрим как работает

2022-02-05 17:21 UTC, KonstantinRaikhert commented on apps/library/utilities.py
> +    scopes = ["https://www.googleapis.com/auth/spreadsheets"]
Это может тоже в константы?

2022-02-06 12:28 UTC, AntonZelinsky requested changes

2022-02-06 12:28 UTC, AntonZelinsky commented on apps/library/utilities.py
> +def export_new_object(obj):
Вынести в отдельный файл и назвать его соответствующе, чтобы было понятно что это относится к экспорту в гугл таблицы.

2022-02-06 12:28 UTC, AntonZelinsky commented on apps/library/utilities.py
> +    range = "Лист1"
Лучше назвать «Заявки » + year или как-то похоже, год кстати, появился у модели, поэтому от туда его нужно брать.

2022-02-06 12:28 UTC, AntonZelinsky commented on apps/library/utilities.py
> +                obj.festival_year,
А тут можно не указывать, так как будет указан в листе, а на новый фестиваль будет в новом листе.

2022-02-06 12:28 UTC, AntonZelinsky commented on apps/library/utilities.py
> +                obj.festival_year,
А можно сделать так, чтобы задать любой документ в настройках? Этого делать пока не нужно, но хочу понимать возможности библиотеки. То есть, можно ли просто подменить документ, а программа будет сама туда пистаь?

2022-02-06 12:28 UTC, AntonZelinsky commented on config/settings/base.py
> +environ.Env.read_env(os.path.join(ROOT_DIR, '.env'))
В начале этого файла происходит создание env, потом он много где используется и только в конце подключается файл, файл нужно перенести в начало файла

2022-02-06 12:28 UTC, AntonZelinsky commented on config/settings/base.py
> +    "client_x509_cert_url": env("GOOGLE_CLIENT_X509_CERT_URL", default="client_cert"),
Тут добавилось столько настроек, список переменных для запуска локально нужно добавлять в инвайрмент файл. Создай файл `.env.example` и добавь туда переменные, желательно с уже установленными данными для запуска.

2022-02-06 12:28 UTC, AntonZelinsky commented on config/settings/base.py
> +PARTICIPATION_FILE_PATH = env("PARTICIPATION_FILE_PATH", default="file_path")
Если это путь к файлам с заявками, то у нас он динамически рассчитывается, и вообще, он есть в моделе, хотя, может быть это к файлу на диске. 
Хорошо бы, если у неочевидных полей были бы минимальные комментарии

2022-02-06 12:29 UTC, AntonZelinsky commented
А как первая строка в таблице генерируется?

2022-02-06 15:12 UTC, Omnomus commented on apps/library/models/participation_application.py
> +        """Save generated filename.
тут не поняла, почему. Поясни, пожалуйста. https://www.python.org/dev/peps/pep-0008/#documentation-strings
<img width="824" alt="Снимок экрана 2022-02-06 в 18 12 02" src="https://user-images.githubusercontent.com/78786450/152687470-e8822cd5-1d09-4e1b-9660-572b9e7794b4.png">

2022-02-06 15:15 UTC, Omnomus commented on apps/library/utilities.py
> +    obj_number = "-укажите номер заявки-"
тут немного логика добавления завязана - данные вставляются, начиная с первого столбца. У них первый столбец это номер, поэтому я "забила" для него место. Можно просто вставлять пустую строку, но что-то я вставлять должна. А вообще порядок столбцов захардкодила (тут не вижу других простых вариантов).

2022-02-06 15:20 UTC, Omnomus commented on apps/library/utilities.py
> +                obj.festival_year,
У каждой таблицы уникальный ID, он в константах. Можно еще с листом уточнить, можно ли не по имени, а по порядковому номеру обращаться и тогда и его в константы вынести - в этом случае да, меняем константы и пишем в совсем другое место.

2022-02-06 17:47 UTC, Omnomus commented on apps/library/utilities.py
> +    range = "Лист1"
Нет, это константа, я обращаюсь к листу с указанным названием.

2022-02-06 17:53 UTC, Omnomus commented on config/settings/base.py
> +    "client_x509_cert_url": env("GOOGLE_CLIENT_X509_CERT_URL", default="client_cert"),
тут следующая ситуация. в константах в том числе ключ сервисного аккаунта от моего личного google.cloud. В целом, не проблема эту информацию расшарить на наших разработчиков. Но в какой то момент я этот ключ удалю, и тогда приложение (речь о локальном использовании неким абстрактным разработчиком) при попытке завести новую заявку упадет - нет действительного ключа. Для того, чтобы этого не происходило я сделала заглушку из Try-Except. Нет действительного ключа - ничего не произойдет. Сейчас я буду заглушку убирать, так как не тестовом сервере не работает экспорт и из-за нее даже нет логов с ошибками (хотя там дело в переменных окружения почти наверняка). Файл в любом случае есть уже, с ним я также тестировала локально.

2022-02-06 17:55 UTC, AntonZelinsky commented on apps/library/models/participation_application.py
> +        """Save generated filename.
Окей, это я уже привык к варианту с переносом. [Так тоже можно ](https://www.python.org/dev/peps/pep-0257/)
![image](https://user-images.githubusercontent.com/1431279/152694316-06da7944-4fb4-4550-b1e9-1ea0c0b95f6b.png)

2022-02-06 21:44 UTC, AntonZelinsky commented on apps/library/utilities/export_to_google.py
> +    value_input_option = "USER_ENTERED"
А ещё ссылочка со всеми аргументами принимаемыми этими функциями, тут можно сделать, наверно вообще всё https://googleapis.github.io/google-api-python-client/docs/dyn/sheets_v4.spreadsheets.html

2022-02-06 21:44 UTC, AntonZelinsky commented on config/settings/base.py
> +environ.Env.read_env(os.path.join(ROOT_DIR, '.env'))
А строка так и не переехала в верх)

2022-02-06 21:44 UTC, AntonZelinsky commented on config/settings/base.py
> +    "client_x509_cert_url": env("GOOGLE_CLIENT_X509_CERT_URL", default="client_cert"),
Ой, наверно, тут должен остаться перехват исключений логироваться с максимальным уровнем. Потом сделаем отправку писем на почту, в случае критических ошибок

2022-02-06 21:44 UTC, AntonZelinsky commented on config/settings/base.py
> +    "client_x509_cert_url": env("GOOGLE_CLIENT_X509_CERT_URL", default="client_cert"),
Скажи на какой страничке и какие ключи нужно получить, я сделаю свою пару ключей и мы положим их в .env файл

2022-02-06 21:44 UTC, AntonZelinsky commented on apps/library/utilities/export_to_google.py
> +    # return
И при неудачной добавлении записи, хорошо бы обновить в БД запись, чтобы было видно, где была проблема.

2022-02-06 21:44 UTC, AntonZelinsky commented on apps/library/utilities/export_to_google.py
> +    # return
Но это можно и отложить

2022-02-11 11:06 UTC, Omnomus commented on apps/library/utilities/export_to_google.py
> +    value_input_option = "USER_ENTERED"
Я, кстати, специально поставила user_entered, так как он тогда форматирует под настройки таблицы (например, с датой можно по-разному поставить). RAW дает запись как в базе. Но зато RAW ставит "+" перед номером телефона)) В общем, в данном конкретном случае, разницы особо и нет. А какие проблемы с инпутом? То что в str перевожу? Тут без разницы - если не cделать, ошибка 'object is not JSON serializable'.

2022-02-14 15:59 UTC, AntonZelinsky commented on apps/library/utilities/export_to_google.py
> +    value_input_option = "USER_ENTERED"
Проблем нет, я просто увидел что что конвертируешь что-то, вот я и подумал, что можно не конвертировать, а напрямую записать

2022-02-14 17:26 UTC, KonstantinRaikhert commented on config/settings/base.py
> +environ.Env.read_env(os.path.join(ROOT_DIR, '.env'))
Из base надо бы убрать. Как то переносили в local, но почему то снова снесли)

2022-02-14 17:26 UTC, KonstantinRaikhert commented on apps/library/utilities/utilities.py
> +    if 7 <= dt.now().month <= 12:
для этого метода кстати советуют использовать timezone.now() в проектах на джанге

2022-02-14 17:26 UTC, KonstantinRaikhert commented on apps/library/utilities/export_to_google.py
> +logger = logging.getLogger(__name__)
Кстати не узнавала, как работает стандартный логинг с гуникорном?

2022-02-14 17:26 UTC, KonstantinRaikhert commented on apps/library/utilities/utilities.py
> +def generate_class_name_path(instance, filename):
Мне сначала по названию непонятно было, для чего метод) Может стоит переименовать?

2022-02-14 23:02 UTC, AntonZelinsky requested changes
У нас логика сохранения немного поменяется. В общих чертах, 
* нужно сначала сохранить в нашу бд, 
* потом будет сохранение в облачное хранилище (дропбокс или яндекс.диск), 
* обновление модели в связи с этим, что сохранили файл в стороннее хранилище (может просто сохранять ссылку на новый файл, по дефолту null ), 
* потом сохранение в таблицу гугла с ссылкой на облачное хранилище, 
* ещё раз обновить запись в бд, с указанием, что таблица обновлена  
* и наконец отправка письма.

Скорее всего, будем ещё удалять файлы с хранилища нашей машины, так как файлы по паре мегабайт весят, а на фестиваль присылают под 1000 заявок. Они боятся раздувания хранилища, хотя эти файлы для них не так важны как пьесы прошедшие отбор

Только вся эта логика должна быть во вьюшке, а не в модели.

2022-02-14 23:02 UTC, AntonZelinsky commented on apps/library/utilities/export_to_google.py
> +    set_header()
Нужно проверять есть ли записи в таблице и если есть, то можно каждый раз не добавлять хидеры.

2022-02-17 00:08 UTC, AntonZelinsky approved these changes
Добавил пару фидбеков, но это скорее для того, чтобы отполировать код.
Апрувлю, но хотел бы его ещё запустить на тестовом сервере и посмотреть как оно работает.

p.s. обнови файл ридми, а я создам ещё одну задачу на то, чтобы создали файл .env.example, так как его к сожалению не осталось
![image](https://user-images.githubusercontent.com/1431279/154378506-eda95017-975c-420f-a081-7b453d5035c3.png)

2022-02-17 00:08 UTC, AntonZelinsky commented on apps/library/services/spreadsheets.py
> +            return
Если тут вылетает, то скорее всего вылетит и на следующей, и ещё на следующей функции. Проверку делать каждый раз тоже не очень хороший вариант. Выход я вижу только исключения бросать в начале и ловить во вью. Если не пошло в одном месте, то скорее всего не будет работать и в других.
И в логер очень хотелось бы добавить информацию о том, что за операция упала, например, создание сервиса или добавление ридеров в таблицу. Если сделать своё исключение, то на уровне вью, можно будет добавлять в логи информацию о том, при сохранении какой записи произошла ошибка.

2022-02-17 16:25 UTC, AntonZelinsky commented on config/settings/local.py
> +environ.Env.read_env(os.path.join(ROOT_DIR, '.env'))
Если я не ошибаюсь, то можно было сделать так
```suggestion
environ.Env.read_env(ROOT_DIR / '.env')
```

Идея Path в том, чтобы избавиться от os.path.

2022-02-17 19:02 UTC, AntonZelinsky commented
Тогда уже назвать настройки подачи пьес и сюда переместить всё касающееся подачи пьес.
![image](https://user-images.githubusercontent.com/1431279/154552082-2176028c-47d8-4ea6-ad3e-3fb24c479c10.png)

2022-02-17 19:06 UTC, AntonZelinsky commented
Обязательно время, можно в ту же колонку
![image](https://user-images.githubusercontent.com/1431279/154552706-9f846512-0fac-493a-8b41-3d3bd33767f4.png)

2022-02-21 18:15 UTC, AntonZelinsky commented
Ещё пару мелких фидбеков:

1. **Форма для отправки пьесы** переименуй в **Разрешена подача пьес** (может сможешь придумать что-то красивее, но я не смог..). 

2. Эта галочка, кстати, не работает! Я выключил подачу пьес, но приложение всё равно принимает заявки.

3. Может можно увеличить ширину колонки? А то, есть такие, что сильно обрезаются 
![image](https://user-images.githubusercontent.com/1431279/155004755-f33ed3fa-e69c-4394-8aed-12587c9b7eee.png)

2022-02-21 20:14 UTC, merged