ordering for groups amd volunteers in admin + optional image for a festival
Studio-Yandex-Practicum/Lubimovka_backend pull request #234
Opened 2022-02-08 14:49 UTC by baby-platom

Когда создаёте PR, убедитесь, что:

- [ ] вы проверили обновления в [брифе](https://www.notion.so/00f5d5a6d39e426fa1ea7ab69b694f07)
- [ ] синхронизировали изменения кода с [ER-диаграммой базы данных](https://drive.google.com/file/d/1RCIPaEgaLUSqek3znd38VPCKSzOlmJFy/view) связей моделей
- [ ] убедились, что модель OpenAPI проверена (в Swagger отображаются изменения)
- [ ] тесты все пройдены и нет конфликтов
- [ ] созданы необходимые миграции

Когда ваш PR смержен:

- [ ] если у вас были изменения в API, сообщите об этом команде Фронта, им это важно знать!

2022-02-08 19:17 UTC, AntonZelinsky requested changes

2022-02-08 23:54 UTC, nkiryanov commented on apps/info/models.py
> +    press_release_image = models.ImageField(blank=True, verbose_name="Изображение для страницы пресс-релизов")
[styleguide](https://github.com/Studio-Yandex-Practicum/Lubimovka_backend/blob/develop/docs/codestyle.md#правила-для-моделей) не игнорируйте plz

2022-02-09 16:30 UTC, baby-platom commented on apps/info/models.py
> +    press_release_image = models.ImageField(blank=True, verbose_name="Изображение для страницы пресс-релизов")
Я изначально все по стайлу сделал, при пре-коммите автоматически поменялось

2022-02-09 18:38 UTC, nkiryanov commented on apps/info/models.py
> +    press_release_image = models.ImageField(blank=True, verbose_name="Изображение для страницы пресс-релизов")
Мм. Это тоже нужно в документашку добавить, думал там это есть.
Поставь запятую после последнего объекта.

```suggestion
    press_release_image = models.ImageField(blank=True, verbose_name="Изображение для страницы пресс-релизов",)
```

И тогда black автоматически сделает как нужно.

2022-02-09 19:52 UTC, AntonZelinsky commented on apps/info/models.py
> +    press_release_image = models.ImageField(blank=True, verbose_name="Изображение для страницы пресс-релизов")
Заметил, что не указана папка при загрузке изображений. Значит, будет грузить в корень медиа. Это плохо.
Пусть будет хотя бы press_release, но парни знают лучше структуру хранения файлов на сервере и может предложат лучший путь.

2022-02-11 19:52 UTC, KonstantinRaikhert commented on apps/info/migrations/0002_alter_festival_press_release_image.py
> +from django.db import migrations, models
@baby-platom Посмотри пожалуйста. Похоже ты не стянул последние обновления develop.
В итоге у тебя тесты упали. Потому что конфликт миграций

2022-02-12 16:20 UTC, AntonZelinsky approved these changes

2022-02-12 16:20 UTC, merged