Event model implemented
Studio-Yandex-Practicum/Lubimovka_backend pull request #24
Opened 2021-10-02 23:39 UTC by evi1ghost

- Реализована модель Event;
- Добавлен метод __str__ для BaseEvent;
- Подготовлена админка для моделей афиши.

2021-10-03 00:41 UTC, AntonZelinsky commented on apps/afisha/migrations/0001_initial.py
> +# Generated by Django 3.2.7 on 2021-10-02 22:40
Ты удалил одну старую миграцию и обновил эту, существующую. Как ты думаешь, что произойдёт, если у меня накачены эти две миграции? Попадёт ли ко мне твой код? Не сломается ли вообще приложение?

2021-10-03 00:41 UTC, AntonZelinsky commented on apps/afisha/models.py
>  class BaseEvent(BaseModel):
Подскажи, а зачем нам нужны две модели события, которые даже не наследуются друг от друга. Можно кстати делать наследование в джанго через прокси модель, но тут что-то вообще не понимаю. Я посмотрел схему, но ничего ...
Я понимаю, что наверняка это обсудили, но к сожалению я того не видел.

2021-10-03 00:41 UTC, AntonZelinsky commented on apps/afisha/models.py
> +        if hasattr(self, "masterclasses"):
Я так понимаю, что эти штуки должны проверять то, что устанавливает обычный Ивент, но судя по коду и миграциям, это будут 2 таблицы. В общем, пока не понял смысла

2021-10-03 18:21 UTC, evi1ghost commented on apps/afisha/models.py
>  class BaseEvent(BaseModel):
BaseEvent земеняет

2021-10-03 18:26 UTC, evi1ghost commented on apps/afisha/migrations/0001_initial.py
> +# Generated by Django 3.2.7 on 2021-10-02 22:40
Вернул миграции на законное место

2021-10-03 18:37 UTC, evi1ghost commented on apps/afisha/models.py
> +        if hasattr(self, "masterclasses"):
С данной моделью через OneToOneField связаны модели Спектакля, Мастер-класса и Читки (эту связь реализовала Аня, при создании моделей).
Через hasaatr проверяется с каким именно классом связан конкретный объект BaseEvent.

2021-10-03 19:03 UTC, evi1ghost commented on apps/afisha/models.py
>  class BaseEvent(BaseModel):
Основная идея - избежать наличия в Event необязательных полей ForeignKey и соответственно необходимости дополнительной валидации, проверяющей, что хотябы одно из этих полей заполнено и заполнено не более одного поля.
Вот выдержки из статьи, которую Николай скидывал, из которой выбирал способ реализации. Выбирал из двух способов:
1. Несколько необязательных полей ForeignKey - https://drive.google.com/file/d/1h0tIZ1gRFUwj327XqKN7TXFJOr2dymfB/view?usp=sharing
2. Реализация через OneToOneField (текущая) - https://drive.google.com/file/d/1NFk9qNeGg9WetSF_Nm2eVJqqEFePnpXF/view?usp=sharing

Полный текст статьи - https://lukeplant.me.uk/blog/posts/avoid-django-genericforeignkey/

2021-10-03 23:28 UTC, AntonZelinsky commented on apps/afisha/models.py
>  class BaseEvent(BaseModel):
Хорошо, а где наследники базового ивента, например мастер класс? Без этих моделей вообще не наглядно.
Хотя бы одну добавь.

2021-10-03 23:29 UTC, AntonZelinsky commented on apps/afisha/models.py
> +        if hasattr(self, "masterclasses"):
Окей, посмотри как __стр__ сделали в примере, по которому ты делаешь свою задачу. Сделай тут тоже так.

2021-10-03 23:34 UTC, AntonZelinsky commented on apps/afisha/admin.py
>  class EventAdmin(admin.ModelAdmin):
А ещё, посмотри как в примере модельку регистрировали в админке, так будет правильнее, но опять же, без хотя бы одного наследника, аля мастеркласса, ничего не будет понятно 
https://github.com/spookylukey/djangoadmintips/blob/master/generic_foreign_key_tests/alternative3/admin.py

2021-10-04 22:09 UTC, evi1ghost commented on apps/afisha/models.py
> +        if hasattr(self, "masterclasses"):
Переделал через property. Заодно добавил это property в админку.

2021-10-04 22:11 UTC, evi1ghost commented on apps/afisha/admin.py
>  class EventAdmin(admin.ModelAdmin):
Сделано. Один из select_related (для спектакля) закомментирован, т.к. данная связь еще не создана, но будет реализована при подготовке модели спектакля.

2021-10-04 22:14 UTC, evi1ghost commented on apps/afisha/models.py
>  class BaseEvent(BaseModel):
Понял, что именно портит полноту картины:
Необходимые связи уже в develop залиты, т.к. их создавала Аня в рамках своих моделей.
В slack опишу подробнее, прилажу скрины.

2021-10-05 11:47 UTC, AntonZelinsky requested changes

2021-10-05 11:47 UTC, AntonZelinsky commented on apps/afisha/models.py
> +            return self.masterclasses
Метод называется event_name, а возвращает он не имя, а возвращать он будет явно не имя! А модель другого класса, в зависимости от присоединенного свойства. Именно по этому ты и использовал repr для получения имени. Зачем тебе event_name и как ты его бы использовал я не знаю. Мне кажется, тебе нужно конкретное событие.

2021-10-05 11:47 UTC, AntonZelinsky commented on apps/afisha/models.py
> +            return self.performances
С другой стороны, свойства называются `performances, readings и masterclasses`. Эти имена подразумевают множественное число, а у нас one-on-one. Нужно переименовать на `reading, masterclass и performance`.

2021-10-05 11:47 UTC, AntonZelinsky commented on apps/afisha/models.py
>  class BaseEvent(BaseModel):
Нужно добавить докстринг и описать связи, которые тут есть. Потому что, просто тут разобраться не получится. Можешь, ссылку на статью прикрепить.

2021-10-05 11:47 UTC, AntonZelinsky commented on apps/afisha/models.py
> +
А если ещё и отсюда сделать обратный ОneToOne филд к этим трём моделям? ничего же в связях поменяться не должно. А понимания этой сложной схемы намного больше будет

2021-10-05 11:47 UTC, AntonZelinsky commented on apps/afisha/models.py
> +
но, это на подумать

2021-10-05 20:45 UTC, evi1ghost commented on apps/afisha/models.py
> +            return self.performances
Да, связь one-to-one, но для каждого BaseEvent могут быть созданы несколько событий (Event), т.е. через данные свойства может быть получено больше одного события.

2021-10-05 20:52 UTC, evi1ghost commented on apps/afisha/models.py
> +
Если делать из BaseEvent обратные OneToOneField для этих моделей, то данные поля должны быть не обязательными. В таком случае схема связей через промежуточную таблицу потеряет смысл, т.к. не будет отличаться от варианта, в котором модель Event содержит 3 необязательных поля ForeignKey, только еще и лишняя таблица появится.

2021-10-05 21:32 UTC, evi1ghost commented on apps/afisha/models.py
> +            return self.masterclasses
Согласен, с неймингом промахнулся. Подбирал для отображения в админке, чтобы для BaseModel что-то кроме id выводить. Переименовал property и добавил описания для отображения в админке. Сложно подобрать походящее описание для поля, не используя слово "событие" (введет в заблуждение относительно того, какая именно связь отображается).

2021-10-05 21:32 UTC, evi1ghost commented on apps/afisha/models.py
>  class BaseEvent(BaseModel):
Докстринг добавил.

2021-10-08 21:56 UTC, AntonZelinsky approved these changes

2021-10-08 22:05 UTC, merged