Refactor/author slug and play year city
Studio-Yandex-Practicum/Lubimovka_backend pull request #253
Opened 2022-02-14 14:11 UTC by Omnomus

Поля "год" и "город" сделаны необязательными для модели Пьеса. 
Для автора добавлено поле slug, которое может быть сформировано автоматически, либо вручную введено админом (в случае дублирования или по желанию пользователя). Slug добавлен в выдачу в сериалайзерах. Адрес странички автора формируется в виде /library/authors/pushkin

2022-03-04 19:25 UTC, AntonZelinsky requested changes

2022-03-04 19:25 UTC, AntonZelinsky commented on apps/library/migrations/0010_author_slug.py
> +        if author.slug == "someslug":
Не нужно делать никаких дефолтов, как вариант, в одной миграции добавить колонку  slug без констрейнта уникальности, вызвать функцию установки слага для всех записей, а потом обновить колонку добавив констрейнт

2022-03-04 19:25 UTC, AntonZelinsky commented on apps/library/migrations/0010_author_slug.py
> +        if author.slug == "someslug":
1. AddField
2. RunPython
3. AlterField

2022-03-04 19:25 UTC, AntonZelinsky commented on apps/library/migrations/0010_author_slug.py
> +                baseslug += str(author.person.id)
Зачем этот код нужен? Что-то вообще странное.

2022-03-04 19:25 UTC, AntonZelinsky commented on apps/library/models/author.py
> +        return slugify(value.last_name)
Не вижу смысла от этой функции. Не понятно что за параметры пришли на вход, почему у «значения» есть свойство фамилия. 
И зачем объекту автора такое свойство аuthor.get_unique_slug.

2022-03-04 19:25 UTC, AntonZelinsky commented on apps/library/models/author.py
> +        return slugify(value.last_name)
лучше обращаться к пути, а не функции. Так, сразу понятно откуда эта функция `utils.slugify`

2022-03-04 19:25 UTC, AntonZelinsky commented on apps/library/models/author.py
> +                raise ValidationError("Автоматическое формирование транслита фамилии невозможно из-за дублирования")
Хорошо бы ещё сделать проверку на то, что слаг который установил пользователь так же не присутствует в базе.
Можно сделать одну общую проверку и сообщение касающееся дубликата, а не автоматического формирования. Главное, чтобы если на этом проблема, то значение у пользователя осталось для изменения

2022-03-04 19:25 UTC, AntonZelinsky commented on apps/library/migrations/0010_author_slug.py
> +                baseslug += str(author.person.id)
В базе прода всего пару авторов, поэтому дубликатов там точно не будет.

2022-03-05 08:47 UTC, Omnomus commented on apps/library/views/author.py
> +            slug=self.kwargs["slug"],
вытаскиваем конкретного автора. а как по другому можно?)

2022-03-05 08:48 UTC, Omnomus commented on apps/library/migrations/0010_author_slug.py
> +        if author.slug == "someslug":
Антон, я создала тред по этому вопросу. У меня проблема с обьединением в одну миграцию.

2022-03-05 08:48 UTC, Omnomus commented on apps/library/migrations/0010_author_slug.py
> +                baseslug += str(author.person.id)
ок

2022-03-05 08:48 UTC, Omnomus commented on apps/library/models/author.py
> +        return slugify(value.last_name)
учла, убрала функцию

2022-03-05 08:52 UTC, Omnomus commented on apps/library/models/author.py
> +                raise ValidationError("Автоматическое формирование транслита фамилии невозможно из-за дублирования")
А это уже проверяет unique=True. Если пользователь введет существующий слаг, ему будет другое сообщение
<img width="731" alt="Снимок экрана 2022-03-05 в 11 51 01" src="https://user-images.githubusercontent.com/78786450/156876112-ebe78e89-7cea-4436-80ca-0278d2279e14.png">

2022-03-05 15:18 UTC, AntonZelinsky commented on apps/library/views/author.py
> +            slug=self.kwargs["slug"],
Так, а дальше то что? После этого шага выход из функции, а это была запись в переменные уровня функции. То есть вытянули и забыли. Или я что-то не улавливаю?

2022-03-05 15:47 UTC, AntonZelinsky commented on apps/library/models/author.py
> +                raise ValidationError("Автоматическое формирование транслита фамилии невозможно из-за дублирования")
Пример сохранения человека без заполненного транслита, ошибка есть, а что пыталась подставить туда система нет. Обязательно должно быть, а то вообще непонятно
![image](https://user-images.githubusercontent.com/1431279/156890405-714425b4-49a2-480e-8b94-e919c68e0c35.png)

2022-03-05 15:57 UTC, Omnomus commented on apps/library/views/author.py
> +            slug=self.kwargs["slug"],
author = get_object_or_404(Author.objects.prefetch_related(…), slug=slug)
Return author 
Почему уровня функции?

2022-03-06 18:21 UTC, AntonZelinsky commented on apps/library/views/author.py
> +            slug=self.kwargs["slug"],
Ааа, блин, это она достаёт значение в параметры функции, я не увидел этого и подумал, что что-то странное..

2022-03-06 18:29 UTC, AntonZelinsky commented on apps/library/views/author.py
> +            slug=self.kwargs["slug"],
Мой косяк, не заметил что это функция.

2022-03-09 20:03 UTC, AntonZelinsky commented on apps/library/models/author.py
> +                raise ValidationError("Автоматическое формирование транслита фамилии невозможно из-за дублирования")
Этот пункт так и не был сделан.

2022-03-09 20:03 UTC, merged

2022-03-09 20:34 UTC, Omnomus commented on apps/library/models/author.py
> +                raise ValidationError("Автоматическое формирование транслита фамилии невозможно из-за дублирования")
Я сделала так: 
<img width="775" alt="Снимок экрана 2022-03-09 в 23 32 14" src="https://user-images.githubusercontent.com/78786450/157531007-c66eceac-af77-4e68-b8e4-9633cf25261d.png">
Именно в поле вставить оказалось нетривиальной задачей(