Add api question, add model MainSettings
Studio-Yandex-Practicum/Lubimovka_backend pull request #27
Opened 2021-10-08 14:19 UTC by AnnaKPolyakova

Add api question, add model MainSettings

2021-10-08 21:57 UTC, AntonZelinsky commented on apps/main/models.py
> +class MainSettings(BaseModel):
И вообще, я не понимают таких таблиц. Мне кажется, мы уже обсуждали, что так плохо делать..(
Вообще, много примеров расширений, где хранятся настройки в базе, в виде колонок ключ значение.Но ни в одной из них не будет хранения в виде ключ — это свойство таблицы, а значение, это первая строка этой колонки.
https://django-constance.readthedocs.io/en/latest/
https://github.com/fabiocaccamo/django-extra-settings
https://github.com/zlorf/django-dbsettings

Тут можно найти больше вариантов https://djangopackages.org/grids/g/live-setting/

2021-10-12 23:16 UTC, nkiryanov requested changes
Есть некоторые правки.

2021-10-13 08:56 UTC, AnnaKPolyakova commented on config/settings/base.py
> +TEMPLATES_DIR=os.path.join(ROOT_DIR, "templates")
Мне и так и так понятно) вкусовщина)

2021-10-13 15:54 UTC, nkiryanov commented on apps/info/views/question.py
> +class QuestionSerializer(serializers.ModelSerializer):
Ну... нужно принять политическое решение как поступить :)

2021-10-13 17:06 UTC, merged