info models (renaming + separation)
Studio-Yandex-Practicum/Lubimovka_backend pull request #272
Opened 2022-02-21 17:00 UTC by baby-platom

Когда создаёте PR, убедитесь, что:

- [ ] вы проверили обновления в [брифе](https://www.notion.so/00f5d5a6d39e426fa1ea7ab69b694f07)
- [ ] синхронизировали изменения кода с [ER-диаграммой базы данных](https://drive.google.com/file/d/1RCIPaEgaLUSqek3znd38VPCKSzOlmJFy/view) связей моделей
- [ ] убедились, что модель OpenAPI проверена (в Swagger отображаются изменения)
- [ ] тесты все пройдены и нет конфликтов
- [ ] созданы необходимые миграции

Когда ваш PR смержен:

- [ ] если у вас были изменения в API, сообщите об этом команде Фронта, им это важно знать!

2022-02-21 17:01 UTC, baby-platom commented
Было проведено [переименование](https://www.notion.so/FestivalTeam-FestivalTeamMember-f89925af9601429a80982238cb8c7abb) и [разбитие](https://www.notion.so/info-3e24d9b15c7146689075403889d7ebae) моделей в info

2022-02-21 17:16 UTC, AntonZelinsky requested changes

2022-02-21 17:16 UTC, AntonZelinsky commented on apps/info/admin.py
> +admin.site.register(FestivalTeamMember, FestivalTeamAdmin)
На проекте[ приняли решение](https://github.com/Studio-Yandex-Practicum/Lubimovka_backend/blob/develop/docs/codestyle.md#%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%B0-%D0%B4%D0%BB%D1%8F-%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D0%B8-%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D0%B5%D0%B9-%D0%B2-%D0%B0%D0%B4%D0%BC%D0%B8%D0%BD%D0%BA%D0%B5), регистрировать модели через декораторы. замени регистрацию всех моделей админки в этм файле

2022-02-21 17:16 UTC, AntonZelinsky commented on apps/info/admin.py
> +admin.site.register(FestivalTeamMember, FestivalTeamAdmin)
И моедль админки тоже переименуй, согласно регистрируемой модели

2022-02-21 17:16 UTC, AntonZelinsky commented on apps/library/factories/author.py
> +from apps.info.models import Festival
Странно, что в ПР ты ничего не делаешь с Person, но он почему-то меняет своё расположение из приложения info в core. Такое ощущение, что этот код раньше не работал

2022-02-21 17:17 UTC, AntonZelinsky approved these changes

2022-02-22 15:39 UTC, AntonZelinsky commented on apps/info/migrations/0004_alter_volunteer_options.py
> +        migrations.RenameModel("FestivalTeam", "FestivalTeamMember")
А почем миграция меняется, а не создаётся новая? Она же не будет применена на основном сервере, поскольку там уже накачена эта миграция!

2022-02-25 19:50 UTC, AntonZelinsky approved these changes

2022-02-26 13:12 UTC, AntonZelinsky approved these changes

2022-02-26 13:12 UTC, merged