Bugfix/person last name ordering
Studio-Yandex-Practicum/Lubimovka_backend pull request #288
Opened 2022-02-27 10:58 UTC by baby-platom

Когда создаёте PR, убедитесь, что:

- [ ] вы проверили обновления в [брифе](https://www.notion.so/00f5d5a6d39e426fa1ea7ab69b694f07)
- [ ] синхронизировали изменения кода с [ER-диаграммой базы данных](https://drive.google.com/file/d/1RCIPaEgaLUSqek3znd38VPCKSzOlmJFy/view) связей моделей
- [ ] убедились, что модель OpenAPI проверена (в Swagger отображаются изменения)
- [ ] тесты все пройдены и нет конфликтов
- [ ] созданы необходимые миграции

Когда ваш PR смержен:

- [ ] если у вас были изменения в API, сообщите об этом команде Фронта, им это важно знать!

2022-02-27 11:01 UTC, baby-platom commented
[Тикет](https://www.notion.so/a2bb81bbda3b459aada8630d0b336998)

2022-02-27 13:24 UTC, nkiryanov requested changes
Написал, что `first_name` тоже нужно добавить для сортировки. Но что ещё: а сделанные изменения точно дают нам результат? Проверял? Если правильно помню мы нигде TeamMember отдельно не выводим, только совместно с другими сериалайзерами, где собираем структуру в отдельных запросах. Там эта сортировка останется (может быть её ломаем, когда собираем структуру).

Ну и чтоб не сломать в будущем у меня рекомендация тест на это написать.

2022-02-27 13:24 UTC, nkiryanov commented on apps/info/models/festival.py
> +        ordering = ("person__last_name",)
Имя тоже нужно добавить, нет? Иначе `Янова Сергей `может оказаться раньше чем `Янова Александр`, а так быть не должно

2022-02-27 13:26 UTC, nkiryanov commented
Пожалуй ещё добавлю (попрошу) в изначальном шаблоне писать что поменялось в PR. Открывать тикет или смотреть просто по коду неудобно. Ведь несложно когда создаешь PR описать что делал в PR. Вот сюда (прикладываю картинку)

![screenshot_2022-02-27_at_16 25 54@2x](https://user-images.githubusercontent.com/70921439/155884296-5a2fccfd-3bac-46f5-8c3d-f2ac8e6b481c.png)

2022-02-28 13:43 UTC, baby-platom commented
Добавил преференцию по first_name, сразу везде где человек у нас есть. По поводу не ломает ли сериалайзер ordering: проверил, сериалайзер нигде не вызывается кроме вьюхи модели самой, сама модель также

2022-02-28 14:26 UTC, AntonZelinsky approved these changes

2022-03-01 13:30 UTC, baby-platom commented
@nkiryanov в ожидании твоего апрува)

2022-03-01 17:49 UTC, kr0t approved these changes

2022-03-01 21:00 UTC, nkiryanov commented
Друзья, у меня походу месяц такая загрузка, что ничего не успею.

Апрувьте без меня 🙏

2022-03-02 14:29 UTC, merged