get data containing tag, last_commit, commit_date, and environment
Studio-Yandex-Practicum/Lubimovka_backend pull request #297
Opened 2022-03-06 12:33 UTC by baby-platom

Когда создаёте PR, убедитесь, что:

- [ ] вы проверили обновления в [брифе](https://www.notion.so/00f5d5a6d39e426fa1ea7ab69b694f07)
- [ ] синхронизировали изменения кода с [ER-диаграммой базы данных](https://drive.google.com/file/d/1RCIPaEgaLUSqek3znd38VPCKSzOlmJFy/view) связей моделей
- [ ] убедились, что модель OpenAPI проверена (в Swagger отображаются изменения)
- [ ] тесты все пройдены и нет конфликтов
- [ ] созданы необходимые миграции

Когда ваш PR смержен:

- [ ] если у вас были изменения в API, сообщите об этом команде Фронта, им это важно знать!

2022-03-06 12:34 UTC, baby-platom commented
[Тикет: Добавить версиирование](https://www.notion.so/3053cc39833341c9abdf1d48c4a865d8)

2022-03-07 14:49 UTC, AntonZelinsky requested changes

2022-03-07 14:49 UTC, AntonZelinsky commented on templates/admin/base_site.html
> +        <a style="color:rgb(232, 240, 240);">Environment: <span class="badge badge-pill badge-info" style="color:rgb(232, 240, 240)";>{{ environment }}</span></a>
Этот кусок html очень переусложнён. Зачем тут вообще ссылка, которая никуда не ведёт?
![image](https://user-images.githubusercontent.com/1431279/157053723-ff8b495d-f85c-4520-a20c-449436fa0195.png)
![image](https://user-images.githubusercontent.com/1431279/157053979-4d012cfa-ed56-4c0b-b1c5-00feb4a93b5f.png)

Да и сам блок стал выглядеть громоздко. Если его и добавлять его, то чтобы выглядел очень минималистично. 
Вообще, в идеале, чтобы при наведении на надпись «Администрирование сайта» показывался этот блок, но боюсь, это решение ты не сделаешь на html и css, а тянуть за собой js библиотеки точно не стоит.
Вообще, я так посмотрел на всё это и понял, что надпись «Environment: feature» не имеет смысла, так как мы из урла можем увидеть что это за инвайрмент. Давай не будем её делать вообще. 
Давай немного актуализирую задание и сразу извини что не сразу есть все требования..:
Для мастер ветки на сайте выводить тег(если есть), дату и номер комита
Для дева, дату и номер комита
Для тестового, название ветки, дату и номер комита.

Подумай как сделать более компактно

2022-03-07 14:49 UTC, AntonZelinsky commented on apps/info/views/version.py
> +        master = repo.head.reference
Тут точно название должно быть не master!

2022-03-12 01:31 UTC, AntonZelinsky requested changes
Я не знаю, насколько правильно решать эту задачу в контекстном процессоре, надеюсь, коллеги подскажут!

2022-03-12 01:31 UTC, AntonZelinsky commented on apps/info/context_processors.py
> +        last_tag = repo.tags[-1]
Ожидаемо, что твой код упадёт! Я про эту проблему писал ещё в прошлом ревью!
![image](https://user-images.githubusercontent.com/1431279/157997867-386e478c-e852-449c-817f-277762e9fdf8.png)

Может ещё будет активен сервер и сам сможешь увидеть ошибку. https://test.dev.lubimovka.ru/admin/login/?next=/admin/

2022-03-12 01:31 UTC, AntonZelinsky commented on templates/admin/base_site.html
> +    {% endif %}
Очень много бессмысленно дублирующегося кода

2022-03-12 01:31 UTC, AntonZelinsky commented on apps/info/context_processors.py
> +            extra_context["type"] = "develop"
Зачем это всё, если в переменной environment и так есть это значение!

2022-03-12 01:31 UTC, AntonZelinsky commented on apps/info/context_processors.py
> +            extra_context["type"] = "develop"
Тут тоже очень много дублирующегося кода!

2022-03-12 01:31 UTC, AntonZelinsky commented on apps/info/context_processors.py
> +        environment = str(branch).split("/")[0]
из-за того что переменную назвал неправильно, только путаница возникает..( Это первая часть имени ветки.
А что если ветка будет иметь название „test“? 
Тебе кстати нужно вывести именно название ветки, если она не develop или master.

2022-03-12 01:31 UTC, AntonZelinsky commented on apps/info/context_processors.py
> +    route = request.path.split("/")[1]
Если запрос в корень сайта, что тут произойдёт?

2022-03-12 09:01 UTC, baby-platom commented on apps/info/context_processors.py
> +        environment = str(branch).split("/")[0]
вот тут не понял, какое название переменной?

2022-03-16 01:36 UTC, AntonZelinsky commented on apps/info/context_processors.py
> +            if environment == "master":
Не, слишком сложно! Удали везде инфайрмент и передавай только имя ветки. В шаблоне сделай проверку, если имя ветки не равно мастер или девелоп, то выводи её.
Тег тоже пытайся вернуть каждый раз, если он есть, то не важно где и на какой ветке, всё равно показывай его.
Итого, кода должно стать меньше строк на 10. В extra_context передавай commit_date, last_commit, tag и branch

2022-03-16 01:36 UTC, AntonZelinsky commented on apps/info/context_processors.py
> +        if route == "admin":
Прям не нравится этот кусок кода! Пришли в треде что приходит в path в на различных страницах. На главной админки, на любой другой странице админки, на странице логина. Я думаю, этот код можно сделать красивее и проще

2022-03-16 01:39 UTC, AntonZelinsky commented
И пришли скрин как это выглядит на сайте. попробуем помочь, если что

2022-03-18 15:13 UTC, AntonZelinsky commented on apps/info/context_processors.py
> +def admin_index(request):
Только называй этот препроцессор связано с версиированием, а то сейчас, это вообще не о чём ни говорит.
например admin_versioning

2022-03-18 15:13 UTC, AntonZelinsky commented on apps/info/context_processors.py
> +        repo = git.Repo(os.getcwd())
А ещё, это очень трудозатратные операции, которые глупо выполнять каждый раз. Тут нужно добавить кэширование! Кэшировать можно один раз после запуска, больше эти данные меняться не будут. Поэтому, самый простой кэш тут подойдёт.

2022-03-18 15:13 UTC, AntonZelinsky commented on apps/info/context_processors.py
> +            tag = str(last_tag) if branch.commit == last_tag.commit else None
Скорее всего, тебе нужно будет подредактировать cicd, в том месте, где происходят чекауты данных, чтобы стягивалась ещё и информация о тегах, так как сейчас, скорее всего этого не происходит. 
Попробуй локально на комит повесить тег и передеплоить тестовое приложение. Скорее всего, тег не появится. Можно обратиться к нашему девопсу Максиму, чтобы он подсказал, где это нужно сделать.

2022-03-20 06:36 UTC, baby-platom commented on templates/admin/base_site.html
> +        branch: {{ branch }}<br>
подожди, а как тогда знать что мы в develop или master?

2022-03-21 15:27 UTC, AntonZelinsky commented on templates/admin/base_site.html
> +        branch: {{ branch }}<br>
`if branch != "develop" or branch != "master":`

2022-03-24 19:10 UTC, AntonZelinsky approved these changes

2022-03-24 19:10 UTC, AntonZelinsky commented on templates/admin/base_site.html
> +        <div style="position: fixed; right: 20px; bottom: 20px; color: #00000024;">
Блин, последний комент. Изменение цвет от сюда перенеси в тег ниже, а то он не применяется.

2022-03-24 19:10 UTC, AntonZelinsky commented on templates/admin/base_site.html
> +        <div style="position: fixed; right: 20px; bottom: 20px; color: #00000024;">
А вообще, я немного переделал этот html, приведи к такому виду и всё будет окей

```html
<div style="position: fixed;right: 20px;bottom: 20px;color: #00000024;display: grid;font-weight: bold;">
      <span>branch: feature/versioning</span>   
      <span>commit_date: 23 марта 2022 г. 10:52</span>   
      <span> last_commit: 0ccb967</span>   
</div>
```

Тогда будет выглядеть вот так
![image](https://user-images.githubusercontent.com/1431279/159992227-84eca36a-79e9-4ec9-a5b8-5ed8e50568ea.png)

А потом, нужно будет сделать задачу, перенести все стили в один файл. Но тут уже со всего проекта нужно будет стили собрать. Главное, чтобы руки до этого дошли

2022-03-25 12:34 UTC, baby-platom commented
![image](https://user-images.githubusercontent.com/82268688/160121663-29c2d25a-d8f2-40b7-9925-94c45e92c598.png)
давай цвет все же старый оставлю))

2022-03-25 12:41 UTC, baby-platom commented
![image](https://user-images.githubusercontent.com/82268688/160122560-a228ef2c-9915-4a23-9e13-f3d1b7931745.png)
думаю отлично

2022-03-25 12:41 UTC, merged