Create autocomplete for large lists
Studio-Yandex-Practicum/Lubimovka_backend pull request #326
Opened 2022-03-18 17:43 UTC by stepakiselev

Собрал все автокомплиты в одном autocomplete.js файле, не знаю на сколько это разумно. Или может лучше разложить файлы по отдельным приложениям?

Наткнулся на подводный камень: автокомпликт не подключается к инлайновым полям. Занимаюсь этим вопросом.

Этот ПР проверочный, вдруг вообще данный подход не подходит и нужен другой способ.

2022-03-20 01:42 UTC, AntonZelinsky approved these changes

2022-03-20 01:42 UTC, AntonZelinsky commented on apps/library/forms/admin.py
> +            "link": forms.TextInput(attrs={"size": 30}),
Увидел это, долго смотрел и пытался понять, что это такое и зачем оно нужно. Открыл тестовую ветку и стейдж и в упор не видел разницы. 
А потом вспомнил, что кто-то писал с какой-то проблемой, что поле не влазило. Оказалось, что я 2 часа до этого прочитал и всё забыл.
На моём 15-ти дюймовом монике эту проблему оказалось сложно воспроизвести...

2022-03-20 01:42 UTC, AntonZelinsky commented on apps/library/static/js/admin/autocomplete.js
> +    $("#id_person").select2({
Я думаю, что комментарии можно удалить, так как из id и плейсхолдера понятно к чему это

2022-03-20 01:42 UTC, AntonZelinsky commented on apps/articles/admin/blog_items.py
> +    autocomplete_fields = (
эти все штуки qa протестирую и быстро на правду выйдут

2022-03-21 11:50 UTC, stepakiselev commented on templates/admin/base.html
> +  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
@AntonZelinsky без этой строки скрипт select2 не работает, как будто Jquery не подключен. Я не додумался как иначе выйти из ситуации.

2022-03-21 11:52 UTC, stepakiselev commented on apps/library/forms/admin.py
> +            "link": forms.TextInput(attrs={"size": 30}),
извиняюсь, надо было docstring добавить

2022-03-22 17:59 UTC, stepakiselev commented
@AntonZelinsky на основе ваших слов маленький вопрос: "Если подключать jquery не через класс мета, то переменная jQuery не будет доступна, но будет доступна django.jQuery. Как вариант, можно сделать jQuery = django.jQuery и всё будет работать в более привычном варианте." 
Где именно прописывать  jQuery = django.jQuery? Получается лучше тогда скрипты из шаблонов перетащить в классы Meta у моделей админ?

Своей сортировкой персон я все равно не доволен. Вроде как удобно что ты вводишь начальные данные и эти данные сопоставляются с именем и фамилией и выдается наиболее подходящий вариант. Но когда ты просто вводишь одну букву тебе не предлагают варианты только начинающиеся на эту букву. Странно. В общем чтобы попадать наверняка надо набрать три символа.

2022-03-22 18:11 UTC, KonstantinRaikhert reviewed
А вообще, если проверочный PR, то его можно перевести в состояние draft)

2022-03-25 15:17 UTC, AntonZelinsky commented on apps/library/admin/author.py
> +        ]
```suggestion
    ordering = (
            "person__first_name",
            "person__last_name",
        )
```

2022-03-29 10:01 UTC, stepakiselev commented
@AntonZelinsky, сделал через django-select2, но меня смущает, что дополнительно надо запускать redis, чтобы все работало.
Гляньте подходит ли такой подход.

2022-03-29 10:05 UTC, stepakiselev commented on templates/admin/base.html
>    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
без этих подключений автокомплит в PerformanceMediaReviewAdmin и PerformanceReviewAdmin не хочет работать

2022-03-29 13:51 UTC, AntonZelinsky commented
Не, редис вообще не вариант. Давай откатываться назад, на то что было. Можешь просто откатиться на предыдущий  коммит

2022-03-29 14:07 UTC, stepakiselev commented
ок

2022-03-30 11:58 UTC, stepakiselev commented
я тут немного тупил с ревертом, надеюсь в изменениях разберетесь (((

2022-03-30 19:46 UTC, AntonZelinsky approved these changes

2022-03-30 19:46 UTC, AntonZelinsky commented on apps/library/admin/events.py
> +    autocomplete_fields = ("image",)
Автокомплит такой мы не используем, а только преобразование списка в новый контрол селект2, так что, эти поля мы точно не используем. Попробуй удалить их и проверить что всё нормально работает
![image](https://user-images.githubusercontent.com/1431279/160916997-67d6a743-4175-4be6-8d5d-6b6e09c22767.png)

2022-03-30 19:46 UTC, AntonZelinsky commented on apps/library/static/js/admin/autocomplete.js
> +    });$("#id_button").select2({
Перенос строки пропал

2022-03-30 19:46 UTC, AntonZelinsky commented on apps/library/static/js/admin/autocomplete.js
> +    });$("#id_button").select2({
И почему в одних селекторах есть свойство `width`, а в других нет?

2022-03-30 20:58 UTC, stepakiselev commented on apps/library/admin/events.py
> +    autocomplete_fields = ("image",)
если autocomplete_fields убрать то в инлайновых полях не будет работать. тогда попробую реализовать это в фале autocomplete.js. Я находил решение, но было давольно сложным и поэтому откинул этот вариант, там было кажется через установку библиотеки [Django Suit](https://django-suit.readthedocs.io/en/develop/index.html)

2022-03-30 21:38 UTC, AntonZelinsky commented on apps/library/admin/events.py
> +    autocomplete_fields = ("image",)
Если это необходимо, то не нужно ничего менять, пусть так остаётся. 
Расскажи только почему не будет работать? Как это зависит? Ты же обычный select превращаешь в select  с автодополнением на самом уже сайте. Мне просто это интересно)

2022-03-31 20:56 UTC, AntonZelinsky commented on apps/library/admin/events.py
> +    autocomplete_fields = ("image",)
Такой код будет брать все селекты начинающиеся с id_: `jQuery('select[id^=id_]')`
Можно проверить так, посчитав количество: `jQuery('select[id^=id_]').length;`

2022-03-31 20:58 UTC, AntonZelinsky commented on apps/library/admin/events.py
> +    autocomplete_fields = ("image",)
https://api.jquery.com/attribute-starts-with-selector/

2022-03-31 22:26 UTC, AntonZelinsky commented on apps/library/admin/events.py
> +    autocomplete_fields = ("image",)
Да, при добавлении новых записей этот метод не будет отрабатывать. Как один из вариантов решения, это на кнопку добавления повесить тригер клик, и в нём вызывать код выше повторно. 
Но я придумал вариант получше
```
jQuery('tbody').bind("DOMNodeInserted",function(event){
    alert("child is appended");
});
```
На тег tbody я повесил триггер на добавление новых элементов в дом дерево. И при добавлении нового элемента в дерево будет вызываться содержимое колбэка. Туда тоже добавь конвертацию селектов. Можно вообще получить добавленный элемент из ивента. `jQuery(event.target).select2()`.

2022-04-04 09:03 UTC, stepakiselev commented
Выложил ПР с недоработками, так как есть вопросы, на которых уже долго туплю, нужна помощь (сроки горят).
Инлайны. При добавление нового поля, создается с боку дублирующее и неработающее поле, причем при первом нажатие на кнопку добавить. Где:(почти все инлайны)
Инлайн. Не работает автокомплит для ролей. Где: везде где добавить члена команды это в: добавить спектакль, добавить Мастер-класс, добавить читки, добавить блог). Там идет добавление связки двух полей персона+роль. Для персоны все ок, а для другого поля нет.
Из плюсов: удалось сделать автокомплиты для блоков/элементов конструктора
скрины проблемных мест:
<img width="495" alt="Screenshot 2022-04-04 at 11 50 12" src="https://user-images.githubusercontent.com/78082206/161510888-8989c1ff-790b-45a2-a241-39f624f93094.png">


<img width="874" alt="Screenshot 2022-04-04 at 11 49 23" src="https://user-images.githubusercontent.com/78082206/161510929-a7bd2d68-7031-46c2-84c3-ee9ddb703d02.png">

2022-04-04 09:12 UTC, stepakiselev commented
еще появилось новое поле "другие пьесы" и оно не работает.
Может поправить модель админки
<img width="729" alt="Screenshot 2022-04-04 at 12 06 34" src="https://user-images.githubusercontent.com/78082206/161512462-5ee3f0e8-b576-410c-86f3-2598d5450bf0.png">
?

2022-04-04 13:40 UTC, Omnomus requested changes

2022-04-04 13:40 UTC, Omnomus commented on templates/admin/base.html
> +
видимо тут проблема, что подключая js файл тут, все наши отдельно подключенные слетают. Может дописывать в имеющиеся js отдельно? Конечно, тут много дублирования получится
(

2022-04-04 15:23 UTC, AntonZelinsky commented on templates/admin/base.html
> +
Ой, а в чём проблема, что-то я смотрел и не смог разобраться?

2022-04-04 21:13 UTC, stepakiselev commented
комплиты вроде все работают, осталось только сделать чтобы js файлы функционировали. Там видимо после того как select2 подключился он меняет id полей к которым привязана работа js файлов

2022-04-04 21:22 UTC, evi1ghost commented on templates/admin/base.html
> +
Тут возможно дело в том, что select2 те поля, к которым подключен, делает скрытыми и замещает их на структуру из <span>. Соответственно, если другой js файл работает со стандартным полем, то результатов работы мы не увидим.
Свою часть с ограничением изменений для foreign key полей переделывал под эту особенность.

2022-04-04 21:39 UTC, stepakiselev commented on templates/admin/base.html
> +
> Тут возможно дело в том, что select2 те поля, к которым подключен, делает скрытыми и замещает их на структуру из `<span>`. Соответственно, если другой js файл работает со стандартным полем, то результатов работы мы не увидим.
> Свою часть с ограничением изменений для foreign key полей переделывал под эту особенность.

а как ты их переделал? где можно глянуть

2022-04-04 22:02 UTC, evi1ghost commented on templates/admin/base.html
> +
Тут добавляю к стандартным полям foreignKey класс, чтобы было легко их найти - https://github.com/Studio-Yandex-Practicum/Lubimovka_backend/blob/feature/limit-change-for-foreignkey-fields/apps/core/templates/admin/widgets/custom_foreign_key_select.html

https://github.com/Studio-Yandex-Practicum/Lubimovka_backend/blob/feature/limit-change-for-foreignkey-fields/apps/core/static/js/admin/ForeignKeyLimitChange.js - тут обрабатываю структуру select2.

2022-04-05 07:00 UTC, stepakiselev commented
@AntonZelinsky протестируй плз

2022-04-05 14:03 UTC, AntonZelinsky commented
[Добавь сортировку. ](https://stackoverflow.com/questions/28762180/how-to-sort-the-select2-jquery-plugin-options-alphabetically) У нас четвёртая версия библиотеки

2022-04-05 14:09 UTC, AntonZelinsky commented
Вообще странно, какие-то дропдауны переделались, а какие-то нет. И так много где
![image](https://user-images.githubusercontent.com/1431279/161772693-5bad8106-9bad-4319-b12d-05952854b017.png)

2022-04-05 14:14 UTC, AntonZelinsky commented
На проекты можно не вешать, проектов будет 5-7 штук, автодополнение сейчас не упрощает, а наоборот усложняет выбор
![image](https://user-images.githubusercontent.com/1431279/161773967-c28f897d-13bf-4006-87ac-eef63c6ff8e4.png)

2022-04-05 14:29 UTC, AntonZelinsky commented on config/settings/base.py
> +    # "suit",
?

2022-04-05 14:29 UTC, AntonZelinsky commented on templates/admin/base.html
> +  <script type="text/javascript" src="{% static 'admin/play.js' %}"></script>
Используй сокращённые теги
```suggestion
  <script type="text/javascript" src="{% static 'admin/author_slug.js' %}" />
  <script type="text/javascript" src="{% static 'admin/play.js' %}" />
```

2022-04-05 14:29 UTC, AntonZelinsky commented on apps/library/static/js/admin/autocomplete.js
> +    $('tbody').bind("DOMNodeInserted",function(event){
Тут ты пытаешься ко всем инлайнам с селектом добавить автодополнение. Из-за этого много непонятных ситуаций. Лучше задавать руками под какие id используем это автодополнение. Примеры ошибок я описал выше.

2022-04-05 14:29 UTC, AntonZelinsky commented on apps/library/static/js/admin/autocomplete.js
> +    setSelect2($, "select#id_project", "Выберите проект");
👍🏻

2022-04-05 14:29 UTC, AntonZelinsky commented on apps/library/static/js/admin/autocomplete.js
> +    setSelect2($, "select#id_volunteers-0-person", "Выберите человека");
Из-за этого, только первый элемент инлайна получает автодополнение, а другие нет.
Как вариант, сделать отдельную функцию для инлайнов и проверять id по первым символам, я показывал как это сделтаь. А потом, ещё добавлять `$('tbody').bind("DOMNodeInserted"` если элемент нашёлся.

2022-04-08 13:16 UTC, stepakiselev commented on templates/admin/base.html
> +  <script type="text/javascript" src="{% static 'admin/play.js' %}"></script>
@AntonZelinsky что-то у меня такие сокращенные теги подсвечиваются как не верные. Если не трудно скиньте ссылку на подобные варианты, я чтото не могу найти (((

2022-04-11 06:06 UTC, Omnomus approved these changes

2022-04-13 05:28 UTC, merged