export of application to yandex disk
Studio-Yandex-Practicum/Lubimovka_backend pull request #331
Opened 2022-03-19 17:14 UTC by baby-platom

Когда создаёте PR, убедитесь, что:

- [ ] вы проверили обновления в [брифе](https://www.notion.so/00f5d5a6d39e426fa1ea7ab69b694f07)
- [ ] синхронизировали изменения кода с [ER-диаграммой базы данных](https://drive.google.com/file/d/1RCIPaEgaLUSqek3znd38VPCKSzOlmJFy/view) связей моделей
- [ ] убедились, что модель OpenAPI проверена (в Swagger отображаются изменения)
- [ ] тесты все пройдены и нет конфликтов
- [ ] созданы необходимые миграции

Когда ваш PR смержен:

- [ ] если у вас были изменения в API, сообщите об этом команде Фронта, им это важно знать!

2022-03-21 22:37 UTC, kr0t reviewed
Я завтра с утра вернусь, на свежую голову, непосредственно к самому методу загрузки, там явно есть что улучшить.

2022-03-21 22:37 UTC, kr0t commented on apps/library/models/participation_application.py
> +    file_in_storage = models.URLField(
У тебя тут лежит ссылка, а из названия поля кажется что файл, лучше придумать что-то более подходящее

2022-03-21 22:37 UTC, kr0t commented on apps/library/utilities.py
> +def yandex_disk_export(y, instance):
Мне кажется было бы более логичным вынести это в директорию services, по аналогии с тем, как это сделано с гугл таблицей. Это взаимодействие с ещё одним внешним сервисом.

2022-03-21 22:37 UTC, kr0t commented on apps/library/utilities.py
> +    cwd = str(os.getcwd())
```
getcwd()
        Return a unicode string representing the current working directory.
```
Зачем ты обернул дополнительно в `str`?

2022-03-21 22:37 UTC, kr0t commented on apps/library/views/participation.py
> +y = yadisk.YaDisk(token="AQAAAAAoiXEIAAfBYfQtH0Dmg05Zpw0i8B-_1_Y")
И название переменной лучше дать более говорящее...
Понимаю, что так к документации и по аналогии сделано с Гугл-таблицей, но на мой взгляд хотя бы "yndx"

2022-03-21 22:37 UTC, kr0t commented on apps/library/serializers/participation.py
> +    file_in_storage = serializers.URLField(required=False)
И тут название переменной не соотвествует.

2022-03-22 11:12 UTC, baby-platom commented
Вот [тут объяснил](https://yandex-students.slack.com/archives/C02ER615RT2/p1647922019577419?thread_ts=1647882818.839879&cid=C02ER615RT2) про все переменные

2022-03-22 17:53 UTC, KonstantinRaikhert commented on apps/library/services/yandex_disk_export.py
> +    except yadisk.exceptions.PathExistsError:
Может два эксепшена одинаковых обьединить в один?

2022-03-22 17:53 UTC, KonstantinRaikhert commented on apps/library/views/participation.py
> +yndx = yadisk.YaDisk(token="AQAAAABd9Kl7AAfB0fMaFfzwSkZRlPYfF3vu2f4")  # жду пока в акшнс добавят
Сразу заведи переменную в env и если не будет ключа будет исключение вылетать?

2022-03-23 07:54 UTC, baby-platom commented on apps/library/views/participation.py
> +yndx = yadisk.YaDisk(token="AQAAAABd9Kl7AAfB0fMaFfzwSkZRlPYfF3vu2f4")  # жду пока в акшнс добавят
будет)

2022-03-24 18:17 UTC, KonstantinRaikhert commented on apps/library/services/yandex_disk_export.py
> +        pass
Тут можно обработать исключение в логер. 
logger = logging.getLogger("django")

except yadisk.exceptions.PathExistsError as error:
            logger.critical(error, exc_info=True)

2022-03-24 18:17 UTC, KonstantinRaikhert commented on config/settings/base.py
> +YNDX_DISK = env("YNDX_DISK")
Можно тут добавить по дефолту какое нибудь значение, чтобы тесты не падали.
И если ты завел диск для любимовки, можешь мне скинуть ключ - я добавлю.
А если нет.. @AntonZelinsky Где бы нам его взять? Может заведем на аккаунт lubimovka-2021@yandex.ru ?

2022-03-24 18:43 UTC, AntonZelinsky commented on apps/library/services/yandex_disk_export.py
> +        pass
И описание добавить, что случилось и на какой записи, чтобы можно было отловить ошибку

2022-03-24 18:52 UTC, AntonZelinsky commented on config/settings/base.py
> +YNDX_DISK = env("YNDX_DISK")
Я как раз на этом аккаунте создавал диск для тестирования. 
Другой вопрос, что его хорошо бы очищать после загрузки, чтобы диск был жив

2022-03-25 00:29 UTC, AntonZelinsky requested changes
Много чего написал, надеюсь, разберёшься!)

2022-03-25 00:29 UTC, AntonZelinsky commented on apps/library/services/yandex_disk_export.py
> +        pass
И имена файла от куда и куда.

Но к этому исключению отдельный разговор. Тут ты перехватываешь ту ошибку, которая происходит при создании папки. Вообще, это неправильно, у яндекса есть методы проверки что [папка ](https://yadisk.readthedocs.io/en/latest/docs.html?highlight=mkdir#yadisk.YaDisk.is_dir)или [путь ](https://yadisk.readthedocs.io/en/latest/docs.html?highlight=mkdir#yadisk.YaDisk.exists)существует. Вызывать можно передавая даже просто цифру `yndx.is_dir(2021)`.

2022-03-25 00:29 UTC, AntonZelinsky commented on apps/library/services/yandex_disk_export.py
> +        yndx.upload(from_dir, to_dir)
Вообще, у диска есть апи загрузки [файла по урлу](https://yadisk.readthedocs.io/en/latest/docs.html?highlight=mkdir#yadisk.YaDisk.upload_url). Можно просто передать место для загрузки и наш публичный урл, всё будет работать, а кода в методе станет меньше, но это так, просто размышления...

2022-03-25 00:29 UTC, AntonZelinsky commented on apps/library/views/participation.py
> +        yandex_disk_export(instance)
Эту функцию оберни в трай и перехватывай самую верхнюю ошибку из библиотеки `YaDiskError` и логируй как критикал. КОд дальше должен продолжить работу

2022-03-25 00:29 UTC, AntonZelinsky commented on apps/library/services/yandex_disk_export.py
> +import os
`os `мы больше не используем и пытаемся выпилить везде где только можно. Переезжаем на https://docs.python.org/3/library/pathlib.html

2022-03-25 06:43 UTC, baby-platom commented on apps/library/services/yandex_disk_export.py
> +    name = name.replace("\\", "_").replace("/", "_")
я добавлял это на всякий случай, а так да, это маловероятно)

2022-03-25 12:49 UTC, baby-platom commented on apps/library/services/yandex_disk_export.py
> +        pass
я делал[ как в документации](https://yadisk.readthedocs.io/ru/latest/intro.html#recursive-upload) перехват

2022-03-25 13:24 UTC, baby-platom commented on apps/library/services/yandex_disk_export.py
> +        pass
к слову, я сейчас добавил логирование и ток сейчас задумался, а вообще нужно оно тут? эта ошибка что "существует путь", то есть что уже есть заявки на 2022 год например, она будет постоянно выдаваться (n - 1 от всех заявок в этом году) и это просто перехват ошибки, она ничего толком не несет. Нет другой причины ошибки как то, что папка уже существует, но она ведь и так постоянно существует))

2022-03-25 13:58 UTC, baby-platom commented on config/settings/base.py
> +YNDX_DISK = env("YNDX_DISK")
а так что по дефолту поставить?

2022-03-25 13:59 UTC, baby-platom commented on apps/library/serializers/participation.py
> +    file = serializers.FileField(required=False)
в последней версии только поле `file_in_storage` осталось, я таким образом не обязательным сделал

2022-03-26 00:14 UTC, AntonZelinsky submitted a review, later dismissed

2022-03-26 00:14 UTC, AntonZelinsky commented on apps/library/services/spreadsheets.py
> +from django.conf import settings
@Omnomus посмотри как импорт переделали. Настройки в джанго нужно импортить только так.

2022-03-26 00:14 UTC, AntonZelinsky commented on apps/library/services/yandex_disk_export.py
> +        pass
Ещё раз повторяю, не нужно пытаться создавать папку каждый раз, когда загружаешь файл и как следствие, не нужно перехватывать каждый раз.
Сначала делаешь запрос `yndx.is_dir`, если вернули фолс, то создаёшь. Всё!

Не важно что в документации, мы руководствуемся в первую очередь здравым смыслом и логикой.

2022-03-26 00:14 UTC, AntonZelinsky commented on apps/library/services/yandex_disk_export.py
> +    cwd = str(settings.ROOT_DIR)
Ещё раз, путями мы манипулируем посредством объектов Path, а не строк. Перечитай предыдущие коменты!
И почитай что это за библиотека и для чего она нужна! Я уже писал тебе об этом.

Приводить из объекта Path, чтобы потом смержить с другой строкой пути, это не правильно! Как правильно, я писал в предыдущем ревью!

2022-03-26 00:14 UTC, AntonZelinsky commented on apps/library/services/yandex_disk_export.py
> +        yndx.mkdir(f"/{year}")
Тут можно просто передать год, он правильно всё создаст, я приводил пример в пердыдущем ревью
```suggestion
        yndx.mkdir(year)
```

2022-03-26 03:45 UTC, baby-platom commented
Внес правки в спешке немного, ноутбука у меня нет с собой, поэтому какие-то новые смогу лишь через дней пять внести

2022-03-26 11:04 UTC, AntonZelinsky commented on apps/library/models/participation_application.py
> +        if self.file:
У тебя есть специальный флаг `saved_to_storage`

2022-04-04 14:41 UTC, baby-platom commented
Запушил с правильным удалением и from_dir , момент с year тоже исправил (хоть это и не из-за него проблемы выше были). Документацию еще раз ченкул, там в путях для upload ждут / , поэтому использую Path, но потом replace("\\", "/")

2022-04-04 18:28 UTC, KonstantinRaikhert commented on apps/library/views/participation.py
> +        except (YaDiskError) as error:
Скобки?

2022-04-04 18:28 UTC, KonstantinRaikhert commented on apps/library/services/yandex_disk_export.py
> +    from_dir = str(Path(settings.MEDIA_ROOT / instance.file.name)).replace("\\", "/")
https://docs.python.org/3/library/pathlib.html
![pathlib](https://user-images.githubusercontent.com/69113745/161607533-5f16c297-6ec5-4358-a364-af21fc5f9689.jpeg)

В документации все есть)

2022-04-04 18:28 UTC, KonstantinRaikhert commented on apps/library/services/yandex_disk_export.py
> +    if yndx.is_dir(year) is False:
здесь можно использовать конструкцию 
`Path(yndx.is_dir(year)).mkdir(exist_ok=True)`

То есть проверку с if убрать

2022-04-04 18:28 UTC, KonstantinRaikhert commented on config/settings/base.py
> +YNDX_DISK_TOKEN = env("YNDX_DISK_TOKEN", default="AQAAAABd9Kl7AAfB0fMaFfzwSkZRlPYfF3vu2f4")
А тут в дефолт случайно не реальный токен попал?)))

2022-04-04 22:39 UTC, AntonZelinsky commented on config/settings/base.py
> +YNDX_DISK_TOKEN = env("YNDX_DISK_TOKEN", default="AQAAAABd9Kl7AAfB0fMaFfzwSkZRlPYfF3vu2f4")
Это мой, тестовый, я правда не знаю, оставлять его для тестирования или лучше в .env закинуть его..С одной стороны не жалко, так как он на специальносозданном аккаунте, с друго стороны вроде как не по правилам

2022-04-05 05:35 UTC, baby-platom commented on apps/library/services/yandex_disk_export.py
> +    from_dir = str(Path(settings.MEDIA_ROOT / instance.file.name)).replace("\\", "/")
боже, столько раз перечитывал и нини

2022-04-05 05:41 UTC, baby-platom commented on apps/library/services/yandex_disk_export.py
> +    if yndx.is_dir(year) is False:
Подожди, мне кажется ты перепутал где мы создаем директорию. В этой части кода я создаю папку на диске, это `yndx.mkdir(year)` и в документации `yadisk` в `mkdir()` к тому же нет аргумента `exist_ok` 
![image](https://user-images.githubusercontent.com/82268688/161686347-7793180f-4f3e-40b0-99fb-3ce35f4998f7.png)

2022-04-05 06:55 UTC, KonstantinRaikhert commented on apps/library/services/yandex_disk_export.py
> +    if yndx.is_dir(year) is False:
Понял, извиняюсь)

2022-04-05 06:56 UTC, KonstantinRaikhert commented on config/settings/base.py
> +YNDX_DISK_TOKEN = env("YNDX_DISK_TOKEN", default="AQAAAABd9Kl7AAfB0fMaFfzwSkZRlPYfF3vu2f4")
В общем, если есть возможность, предлагаю написать просто слово token. Вроде не должно сломать а просто выкидывать исключение будет, что сервис не работает

2022-04-05 06:57 UTC, KonstantinRaikhert approved these changes
Убери токен с дефолтов и думаю норм)

2022-04-05 07:07 UTC, merged