Refactor/other plays
Studio-Yandex-Practicum/Lubimovka_backend pull request #343
Opened 2022-03-24 09:00 UTC by Omnomus

Удалена модель OtherPlay. Теперь другие пьесы - это объекты Play (добавлен атрибут play_type, указывающий на тип пьесы). Доработаны фильтры, создание пьесы, фабрики.

2022-03-28 15:39 UTC, AntonZelinsky commented on apps/library/admin/author.py
> +        return obj.play.get_play_type_display()
Хорошо бы сделать два инлайна, один для основных пьес, другой такой же для других

2022-03-28 15:39 UTC, AntonZelinsky commented on apps/library/admin/author.py
> +        return obj.play.get_play_type_display()
Разве что, во втором инлайне не показывать ссылку на видео и в форме его не выводить, но это можно сейчас опустить

2022-03-29 16:41 UTC, Omnomus commented on apps/content_pages/admin/content_blocks.py
> +        kwargs["queryset"] = Play.objects.filter(play_type=PlayType.MAIN)
Нет, он отвечает за другое. get_queryset отвечает за то, какие объекты будут отображены в инлайне, а formfield - за то, какие объекты будут в выпадающем списке при добавлении в инлайне. В админке автора это хорошо видно на инлайнах пьес - нам нужно для просто пьес переопределить QuerySet -  чтобы не выводились другие пьесы и формфилд - чтобы при добавлении случайно не добавить другую пьесу. А у он-лайна других пьес зеркально.

2022-03-29 16:42 UTC, Omnomus commented on apps/library/admin/author.py
> +        return obj.play.get_play_type_display()
сделала два он-лайна

2022-03-29 16:46 UTC, Omnomus commented on apps/library/admin/author.py
> +        return obj.play.get_play_type_display()
Еще вот этот момент прокомментирую тут, чтоб не бегать: 

> И JS мне кажется можно не добавлять, по крайнем мере сделать его проще. Можно вообще сделать 2 формы и проблем ни с отображением ни с сменой в моменте не будет. Да и пользователям будет проще

Две формы предполагают же вторую кнопку админке? Но тогда боковое меня останется с просто "+добавить". В общем тут я не стала менять - уже был рабочий вариант, немного его подправила. Если ты считаешь, что лучше переделать, опиши мне, пожалуйста, чуть подробнее твой вариант с двумя формами, может я не правильно его поняла.

2022-03-29 23:00 UTC, AntonZelinsky commented
Галочка «Опубликовано» должна остаться у других пьес, сейчас её нет.
Из пьесы можно удалить всех авторов, а так быть не должно. Добавь в инлайн свойство `min_num = 1`

2022-03-29 23:44 UTC, AntonZelinsky requested changes

2022-03-29 23:44 UTC, AntonZelinsky commented on apps/library/models/play.py
> +        null=True,
Блин, можно было вообще фильтр по этому свойству делать, это ведь логично, что если фестиваль не выбран, то это Другие пьесы. Хотя, это уже был бы фильтр не программы, а что-то иное

2022-03-29 23:44 UTC, AntonZelinsky commented on apps/library/models/play.py
> +        verbose_name="Ссылка",
Что-то я в админке не смог найти этой ссылки! И не совсем понятно что это за ссылка, особенно по такому названию.

2022-03-29 23:44 UTC, AntonZelinsky commented on apps/library/models/play.py
> +        return super().save(*args, **kwargs)
Нашли вредителя! Вот кто плодит эти функции. Мы сегодня только начали выпиливать их)
У нас обращение к моделям идёт только через админку, а при сохранении через неё, метод клин всегда будет вызван! Можешь протестить
А потом удалить это переопределение

2022-03-29 23:44 UTC, AntonZelinsky commented on apps/library/models/play.py
> +        if self.program.slug == "other_plays":
Тут можно поставить else.

Внизу валидационная ошибка «Необходимо указать ссылку на другую пьесу"». Немного не понял. У нас же старый функционал выпиливается полностью, а новый подразумевает то же что и для обычных пьес. То есть, пьеса будет храниться на нашем сервере. Ссылка и проверка тут не нужна

2022-03-29 23:44 UTC, AntonZelinsky commented on apps/library/models/play.py
> +            self.published = False
А почему она сразу не опубликована? по идее, логика не должна чем-то отличаться от обычных пьес

2022-03-29 23:44 UTC, AntonZelinsky commented on apps/library/views/playfilters.py
> -        programs = ProgramType.objects.all()
Вообще, кажется, другие пьесы должны отображаться в библиотеке. И при клике на эту категорию, все остальные фильтры должны уйти. Но вообще, можно там и не показывать. Если попросят ещё раз, значит действительно очень нужно) и заодно уточнят требования

2022-03-29 23:44 UTC, AntonZelinsky commented on apps/library/views/playfilters.py
> -        programs = ProgramType.objects.all()
ПОлучается, если эту программу мы не отдаём фронту, то тут нужно смотреть на логику приложения чуть-чуть по другому. 
Если я тут не прав, то поправь

2022-03-29 23:44 UTC, AntonZelinsky commented on apps/library/models/play.py
>          return self.name + ("" if self.published else " <— не опубликована —>")
Сюда добавь упоминание, что пьеса не из Любимовки

2022-03-30 10:38 UTC, Omnomus commented on apps/library/views/playfilters.py
> -        programs = ProgramType.objects.all()
А как? Я делала по аналогии с как было - то есть другие пьесы не показываю там, где их не было. Может тут действительно у клиента уточнить - где они хотят их видеть теперь

2022-03-30 12:44 UTC, Omnomus commented
> Галочка «Опубликовано» должна остаться у других пьес, сейчас её нет и все пьесы по умолчанию не опубликованы. Фабрики тоже должны часть других пьес опубликоваными делать, а часть нет
> Из пьесы можно удалить всех авторов, а так быть не должно. Добавь в инлайн свойство `min_num = 1`

а `min_num = 1` не срабатывает при удалении(( пофиксила переписав формсет

2022-03-30 12:51 UTC, AntonZelinsky commented on apps/library/views/playfilters.py
> -        programs = ProgramType.objects.all()
Давай, пока в библиотеке не буде их показывать. Выпускаем фитчу без программы в библиотеке, потом, если что, будет не сложно переделать

2022-03-30 22:02 UTC, AntonZelinsky commented
Ксюша, я всё тебя не отпускаю с этим ПРом)
Нужно и те и другие пьесы сделать сортируемыми. Кажется, что это не должно быть сложно, так как такие штуки мы уже делали. Помню, там добавлялись миксины, но и в базу тоже что-то записывается. Можем это как отдельную задачу сделать. Давай наверно я заведу её, этот ПР нужно смержить, а то очень много файлов затрагивает

2022-03-30 23:01 UTC, AntonZelinsky commented on apps/library/static/admin/play.js
> +        let urlReadingField = $('#play_form > div > fieldset.module.aligned > div.form-row.field-url_reading');
Вообще, всё это мне кажется, очень большим усложнением! Потом что появился отдельный эндпоинт, заточеный только на то, чтобы сказать какого типа опшен в селекте. 
Как вариант, можно в опшены передавать дополнительную информацию, на крайний случай, можно добавлять скрытое поле, в котором будет храниться id этой программы other_plays.

2022-03-31 07:29 UTC, Omnomus commented on apps/library/models/play.py
> +        if hasattr(self, "program"):
Нет, если объект сохраняется без выбранной программы, тут будет false. И дальше при проверке слага приложение упадёт с relatedobjectdoesnotexist. В похожей ситуации у автора мы (кажется даже я!) делали скрытый метод с проверкой через try except. Но вообще Джанго предлагает использовать этот способ, чтобы не ловить исключения https://docs.djangoproject.com/en/4.0/topics/db/examples/one_to_one/

2022-03-31 07:30 UTC, Omnomus commented on apps/core/management/commands/set_perms.py
> -                | Q(codename__endswith="_otherplay")
Да, я посмотрю

2022-03-31 07:33 UTC, Omnomus commented on apps/library/static/admin/play.js
> +        $('select#id_program').each(function() {
Я тут пыталась найти решение для случая, когда программа выбрана,  а потом выскочила ошибка. При попытке сохранения страница перезагрузится и первый селект on change не сработает, как следствие, страница всегда будет с полями как для обычной пьесы. А each смотрит значение, уже выставленное и показывает/скрывает поля в зависимости от программы.

2022-03-31 07:35 UTC, Omnomus commented on apps/library/static/admin/play.js
> +        let urlReadingField = $('#play_form > div > fieldset.module.aligned > div.form-row.field-url_reading');
Согласна. Я даже думала посмотреть, под каким id создаётся программа другие пьесы и просто этот номер использовать, но кажется, это может быть источником бага(( может ещё вариант сделать для программ primary key = slug?

2022-03-31 07:36 UTC, Omnomus commented on apps/library/migrations/0016_delete_other_play.py
> +        slug="other_plays"
Ок

2022-03-31 08:26 UTC, AntonZelinsky commented on apps/library/static/admin/play.js
> +        let urlReadingField = $('#play_form > div > fieldset.module.aligned > div.form-row.field-url_reading');
Предложенный тобой вариант очень хороший!

2022-03-31 08:30 UTC, AntonZelinsky commented on apps/library/models/play.py
> +        if hasattr(self, "program"):
Про исключение понятно, но вопрос про проверку аттрибута. То есть такой код `self.program` тоже с исключением упадёт? Мне кажется, он должен будет вернуть none

2022-03-31 20:15 UTC, Omnomus commented on apps/library/forms/admin/play.py
> +    program = forms.ModelChoiceField(queryset=ProgramType.objects.all(), to_field_name="slug", label="Программа")
И никаких Ajax запросов.

2022-03-31 20:15 UTC, Omnomus commented on apps/library/forms/admin/play.py
> +                raise ValidationError("У пьесы Любимовки должен быть фестиваль")
Перенесла всю логику проверки сюда. Со сменой порядка вызова  clean() и validate сложности возникли((

2022-03-31 23:06 UTC, AntonZelinsky commented on apps/library/forms/admin/play.py
> +                raise ValidationError("У пьесы Любимовки должен быть фестиваль")
Я увидел в коде аналогичный нашей ситуации пример и у меня возник вопрос, а почему бы нам так не сделать?
![image](https://user-images.githubusercontent.com/1431279/161163724-9fd7f0b3-a9b8-4764-a762-55bb70ccf627.png)

ПС, два ифа выше, можно в одну строку свести, если оставишь их тут, то сделай это пожалуйста

2022-03-31 23:11 UTC, AntonZelinsky commented on apps/library/forms/admin/play.py
> +    program = forms.ModelChoiceField(queryset=ProgramType.objects.all(), to_field_name="slug", label="Программа")
Правда, мне так не нравится когда в формах или сериалайзерах делаются запросы к базе... Но я не знаю как эту проблему решить в формах, в сериалайзерах то всё понятно. 
Другой вопрос, что это админка, и тут наверно никак без этого, но всё же, больно смотреть.

2022-03-31 23:28 UTC, AntonZelinsky commented on apps/library/filters/play.py
> +            ("all", _("Показать все пьесы")),
Сделай, пожалуйста, небольшой комментарий, что значат эти два свойства. Я что-то пытался въехать, но до конца и не понял. В следующем методе, как раз на этом и завязано, но всё равно не понимаю.

2022-03-31 23:34 UTC, AntonZelinsky commented on apps/library/forms/admin/play.py
> +    program = forms.ModelChoiceField(queryset=ProgramType.objects.all(), to_field_name="slug", label="Программа")
Да, очень круто, пока не запустил твой код, не мог понять что вообще происходит!

2022-04-01 09:51 UTC, AntonZelinsky commented on apps/library/static/admin/play.js
> +        let yearField = $('#play_form > div > fieldset.module.aligned > div.form-row.field-year');
Можно упростить и ускорить без потери качества
```suggestion
        let cityField = $('#play_form > div.form-row.field-city');
        let yearField = $('#play_form > div.form-row.field-year');
```

2022-04-01 10:57 UTC, AntonZelinsky commented on apps/library/static/admin/play.js
> +        let yearField = $('#play_form > div > fieldset.module.aligned > div.form-row.field-year');
Почитал jquery standart, очень даже интересно https://lab.abhinayrathore.com/jquery-standards/https://lab.abhinayrathore.com/jquery-standards/

2022-04-01 11:59 UTC, Omnomus commented on apps/library/forms/admin/play.py
> +                raise ValidationError("У пьесы Любимовки должен быть фестиваль")
так упадет же, если программы не выбрано... давай сделаем, как у автора, с приватным методом проверки в модели.

2022-04-01 12:24 UTC, Omnomus commented on apps/library/static/admin/play.js
> +        let yearField = $('#play_form > div > fieldset.module.aligned > div.form-row.field-year');
У меня не сработало) тут, кстати, играет роль куки (или кэши?) - я такие вещи тестирую после очистки в браузере.

2022-04-01 14:01 UTC, AntonZelinsky commented on apps/library/static/admin/play.js
> +        let yearField = $('#play_form > div > fieldset.module.aligned > div.form-row.field-year');
Тут оказывается, нужно указать все вложенности. 
` $('#play_form >>> div.form-row.field-city');`
Пусть остаётся как есть

2022-04-02 16:55 UTC, AntonZelinsky approved these changes

2022-04-02 20:36 UTC, merged