Change usercreationform in admin with sending email and new fields
Studio-Yandex-Practicum/Lubimovka_backend pull request #375
Opened 2022-04-04 21:27 UTC by valerycode

Когда создаёте PR, убедитесь, что:

- [ ] вы проверили обновления в [брифе](https://www.notion.so/00f5d5a6d39e426fa1ea7ab69b694f07)
- [ ] синхронизировали изменения кода с [ER-диаграммой базы данных](https://drive.google.com/file/d/1RCIPaEgaLUSqek3znd38VPCKSzOlmJFy/view) связей моделей
- [ ] убедились, что модель OpenAPI проверена (в Swagger отображаются изменения)
- [ ] тесты все пройдены и нет конфликтов
- [ ] созданы необходимые миграции

Когда ваш PR смержен:

- [ ] если у вас были изменения в API, сообщите об этом команде Фронта, им это важно знать!

2022-04-04 21:32 UTC, valerycode commented
Все замечания с прошлого PR исправила. Настроить отправку писем, используя шаблон в Mailjet не успеваю, поэтому пока через встроенный шалон Джанго. Я в прошлый раз писала, что исправить переменные domain, site_name можно через БД(модель Site). Это чтобы вместо example.py писалось lubimovka.ru.
Тут можно почитать - https://docs.djangoproject.com/en/4.0/ref/contrib/sites/#module-django.contrib.sites

2022-04-05 07:14 UTC, KonstantinRaikhert submitted a review, later dismissed
Апрувну только из за релиза. Относительно работает, но нужно многое поправить! Стоило все же соглашаться на помощь.

Относительно сайта example.com
Если данное значение берётся из БД, мы можем его поменять через миграцию! Посмотри пожалуйста как мы добавляем или убираем данные в БД через миграции (самописные).
Вроде ты говорила, что можешь сейчас вносить правки, сделай пожалуйста эту реализацию. Будет значительно красивее.
<img src="https://user-images.githubusercontent.com/69113745/161698938-cf4512c7-f9c3-49f7-b523-c8094c9804cf.jpeg" height="500">

2022-04-05 07:14 UTC, KonstantinRaikhert commented on apps/users/forms.py
> +                from_email="lubimovka-2021@yandex.ru",
Тут как то адрес захардкодили. Не гут.
У нас даже этот адрес есть в default email. Есть так же адреса в БД. 
Так что нужно брать откуда то из настроек. Server email либо default email.
А может необходимо новую переменную завести!
@AntonZelinsky

2022-04-05 07:14 UTC, KonstantinRaikhert commented on apps/users/models.py
> +            raise ValueError("Users must have an email address")
Это исключение вроде как попадает в админку, не? Если да, то предлагаю на русский переписать

2022-04-05 09:50 UTC, valerycode commented on apps/users/forms.py
> +                from_email="lubimovka-2021@yandex.ru",
Забыла этот момент поправить.

2022-04-05 09:50 UTC, valerycode commented on apps/users/models.py
> +            raise ValueError("Users must have an email address")
Нет, не попадает.

2022-04-05 09:51 UTC, valerycode commented
> Апрувну только из за релиза. Относительно работает, но нужно многое поправить! Стоило все же соглашаться на помощь.
> 
> Относительно сайта example.com Если данное значение берётся из БД, мы можем его поменять через миграцию! Посмотри пожалуйста как мы добавляем или убираем данные в БД через миграции (самописные). Вроде ты говорила, что можешь сейчас вносить правки, сделай пожалуйста эту реализацию. Будет значительно красивее. ![image](https://user-images.githubusercontent.com/69113745/161698938-cf4512c7-f9c3-49f7-b523-c8094c9804cf.jpeg)

Не поняла про "многое поправить". Речь про работу шаблона?

2022-04-05 10:23 UTC, KonstantinRaikhert commented
> > Апрувну только из за релиза. Относительно работает, но нужно многое поправить! Стоило все же соглашаться на помощь.
> 
> > 
> 
> > Относительно сайта example.com Если данное значение берётся из БД, мы можем его поменять через миграцию! Посмотри пожалуйста как мы добавляем или убираем данные в БД через миграции (самописные). Вроде ты говорила, что можешь сейчас вносить правки, сделай пожалуйста эту реализацию. Будет значительно красивее. ![image](https://user-images.githubusercontent.com/69113745/161698938-cf4512c7-f9c3-49f7-b523-c8094c9804cf.jpeg)
> 
> 
> 
> Не поняла про "многое поправить". Речь про работу шаблона?

Речь про логику.
Чтобы переводить на библиотеку anymail нужно писать отличную от этой логику.
Ну и плюс поправить через миграцию значение сайта.

2022-04-05 11:27 UTC, valerycode commented
> 

В задаче не было ни слова про то, что надо реализовать отправку писем через anymail, как и в замечаниях к прошлому PR, поэтому я реализовала задачу через встроенные методы Джанго. Если реализовать это через anymail, то **код надо переписывать полностью.** Был разговор про то, что "хорошо было бы" использовать шаблон anymail вместо шаблона Джанго, но я думала, что это делается быстро и просто. По факту нет. 
Про шаблон Джанго - я пыталась поправить эти переменные программно, но у меня не получилось это сделать. И так как надо было срочно делать PR, то я оставила так(с учетом того, что это можно поправить руками в БД).

2022-04-05 12:22 UTC, AntonZelinsky commented on apps/users/forms.py
> +                from_email="lubimovka-2021@yandex.ru",
У нас есть специальный email адрес в настройках, от куда его нужно брать

2022-04-06 23:55 UTC, AntonZelinsky commented
Сделать доступными только для чтения. Админ не должен такое редактировать
![image](https://user-images.githubusercontent.com/1431279/162092842-3cc4c62e-820a-46fa-b068-b391c3b36a8e.png)

2022-04-07 00:01 UTC, AntonZelinsky commented
Нужно придумать кнопку сброса пароля в админке, а то ссылка пришла, я вроде как сбросил, но войти не смог..( хз, это из-за неправильного ввода пароля или ещё чего-то

2022-04-07 00:09 UTC, AntonZelinsky commented
обсуждалась проблема

2022-04-07 00:10 UTC, AntonZelinsky commented
Обсуждалась проблема домена, но ведь домен можно достать из `requet.headers`, там будет точно саый актуальный. Даже если у сайта несколько зеркал, ссылка придёт с тем адрессом, с которого отправлял админ

2022-04-10 23:26 UTC, KonstantinRaikhert commented
@AntonZelinsky 
1. Теперь можно использовать и username и email для входа
2. Конфликты с сохранением пьесы решены
3. Смена пароля по ссылке в письме

2022-04-11 11:35 UTC, AntonZelinsky commented
Пароль давай вообще прятать. Он никакой полезной информации не несёт. Кнопка сброса должна отправлять письмо, со ссылкой как при регистрации. Видно, нужно добавить ещё одно письмо
![image](https://user-images.githubusercontent.com/1431279/162730826-0a158a30-1ea9-48ca-8019-26792c664431.png)

2022-04-11 11:36 UTC, AntonZelinsky commented
![image](https://user-images.githubusercontent.com/1431279/162731520-814b0dc2-310e-48c4-8a68-c9e3e02a90b9.png)
И эти поля сделать ридонли. Их не должно быть возможности редактировать

2022-04-11 15:38 UTC, AntonZelinsky commented on config/settings/local.py
> +DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default=None)
Это же берётся из базы? пользователи задают эти поля в админке!

2022-04-11 15:38 UTC, AntonZelinsky commented on config/settings/local.py
> +}
Сейчас, у нас уже в трёх сетингс файлах есть этот конфиг. То есть, локально тоже будет отправляться письма через ANYMAIL?

2022-04-11 15:38 UTC, AntonZelinsky commented on apps/users/models.py
> +            raise ValueError("Users must have an email address")
Этот код вообще никогда не исполнится, так как валидационные ошибки отработают в форме. От сюда можно убрать

2022-04-11 15:38 UTC, AntonZelinsky commented on apps/users/migrations/0003_auto_20220411_0119.py
> +            ],
СТранно, что менеджера старого убрала, но нового не добавила. Может так и нужно, просто смутило и решил написать

2022-04-11 15:38 UTC, AntonZelinsky commented on apps/core/migrations/0016_add_new_emails.py
> +        defaults=values_for_update_email_to_send_questions,
Ой, а объясни пожалуйста что тут происходит? Ты меняешь ключ с email_send_to на email_to_send_questions?

2022-04-14 18:20 UTC, Omnomus commented on apps/core/utils.py
> +        if hasattr(message, "anymail_status") and message.anymail_status.esp_response.status_code == status.HTTP_200_OK:
тут по документации вернётся 1 или 0 - почему логика усложнится? Если 1 - вернем True. У нас разве может быть несколько писем?

2022-04-14 18:21 UTC, Omnomus commented on apps/library/services/yandex_disk_export.py
>      from_dir = Path(settings.MEDIA_ROOT / instance.file.name).as_posix()
поменяла

2022-04-14 18:33 UTC, Omnomus commented on config/settings/base.py
> +DOMAIN_URL = env("DOMAIN_URL", default="localhost")
вроде сделала

2022-04-14 19:25 UTC, Omnomus commented on apps/library/views/participation.py
> +            instance.save()
переделала

2022-04-14 19:27 UTC, Omnomus commented on apps/library/views/participation.py
> +            export_to_google_sheets_success = gs.export(instance, file_url)
если выгрузка на Яндекс прошла, то мы уже тут получим полную ссылку. Поэтому логично и в случае не сохранения на яндексе тут собирать полную ссылку и отдавать в Гугл таблицы.

2022-04-14 19:28 UTC, Omnomus commented on config/settings/local.py
> +}
Локально тоже через мэйлджет приходят письма, видимо да)

2022-04-14 19:40 UTC, Omnomus commented on apps/core/migrations/0016_add_new_emails.py
> +        settings_key="email_subject_for_question",
кроме той, где ключ меняется (ниже).

2022-04-14 19:41 UTC, Omnomus commented on apps/core/migrations/0016_add_new_emails.py
> +        defaults=values_for_update_email_to_send_questions,
да, я тоже так поняла

2022-04-14 19:55 UTC, Omnomus commented on apps/core/utils.py
> +        if hasattr(message, "anymail_status") and message.anymail_status.esp_response.status_code == status.HTTP_200_OK:
здесь ничего пока не трогала

2022-04-18 07:24 UTC, KonstantinRaikhert commented on config/settings/local.py
> +}
А блин! Нет! Я забыл убрать это, когда тестил локально mailjet( в общем отсюда это можно убрать.
Локально у нас используется джанговсуий почтовый бэкенд и письмо отправляет в консоль

2022-04-18 07:25 UTC, KonstantinRaikhert commented on apps/core/migrations/0016_add_new_emails.py
> +        defaults=values_for_update_email_to_send_questions,
Чтобы не было путаницы. У нас 2 почты для отправки, одна для вопросов, вторая для заявок

2022-04-18 15:21 UTC, AntonZelinsky requested changes
Предлагаю, [эти строки](https://github.com/Studio-Yandex-Practicum/Lubimovka_backend/pull/375/files#diff-92bacd7aba5a8d64c5f5c782690ed7a463b62b20df91fdb57b6c94bbaea016beR66) можно перенести в байз сетингс и задать дефолты в качестве админ/админ. Мы их дублируем 2 раза, при том, в локальном нет, а в локальном хотелось бы с одной строки  создавать юзера.
Вообще, нужно создать таску на переработку этих файлов, очень много чего стоит улучшить. Например, домены кривые https://github.com/Studio-Yandex-Practicum/Lubimovka_backend/pull/375/files#diff-d4a76e5d1ce8d7a9743e81d3f538d1046d9d368fd9281cae0a6f4918b0759717R13.

2022-04-18 15:21 UTC, AntonZelinsky commented on apps/core/utils.py
> +    server_protocol = "".join(filter(str.isalpha, request.META["SERVER_PROTOCOL"])).lower()
Сложновато, может значение взять из HTTP_REFERER и сплитнуть по ://
По сути одно и тоже, однако второй вариант намного очевиднее.
![image](https://user-images.githubusercontent.com/1431279/163827679-375a7c64-6afd-4730-96d6-88e1ce25fb26.png)

2022-04-18 15:21 UTC, AntonZelinsky commented on config/urls.py
> +        route="reset/done/",
В облаке это работать не будет
![image](https://user-images.githubusercontent.com/1431279/163828708-b8f3af09-bcb9-4a13-8c54-eb2e9b74eee5.png)

2022-04-18 15:21 UTC, AntonZelinsky commented on apps/users/models.py
> +            raise ValueError("Users must have an email address")
@Omnomus

2022-04-18 16:15 UTC, Omnomus commented on apps/users/models.py
> +            raise ValueError("Users must have an email address")
Проглядела, сорри(

2022-04-18 17:01 UTC, AntonZelinsky requested changes

2022-04-18 23:02 UTC, AntonZelinsky commented on apps/core/utils.py
> +    server_protocol = "".join(filter(str.isalpha, request.META["SERVER_PROTOCOL"])).lower()
Или тот же аттрибут, но сплитать по `/1.1`, так как семантически http/s — это протокол

2022-04-18 23:03 UTC, AntonZelinsky commented on apps/users/forms.py
> +            user_email = getattr(user, email_field_name)
точнее не гет, а `filter(email).first`, так как гет — это зло!

2022-04-19 16:03 UTC, Omnomus commented on apps/core/utils.py
> +def send_email(from_email: str, to_emails: tuple, template_id: str, context: dict, attach_file: bool = False) -> bool:
done

2022-04-19 18:54 UTC, Omnomus commented on apps/library/services/yandex_disk_export.py
> +            Path(instance.file.path).unlink()
я тут его совсем удалила.

2022-04-19 18:54 UTC, Omnomus commented on apps/library/services/yandex_disk_export.py
> +            Path(instance.file.path).unlink()
я тут его совсем удалила.

2022-04-19 19:47 UTC, Omnomus commented on apps/library/views/participation.py
> +            send_email_success = send_email(from_email, to_emails, template_id, context, attach_file=True)
тут немного некрасиво выйдет. удалять файл нужно, если выгрузка на диск прошла, не иначе. Получается, сначала сохраняя на ЯД мы не можем тут же его (файл) удалить, так как дальше мы аттачим его к письму. И вот дальше нам надо снова проверить, что выгрузка на ЯД прошла и только тогда удалить.

2022-04-19 19:47 UTC, Omnomus commented on apps/library/views/participation.py
> +            send_email_success = send_email(from_email, to_emails, template_id, context, attach_file=True)
тут немного некрасиво выйдет. удалять файл нужно, если выгрузка на диск прошла, не иначе. Получается, сначала сохраняя на ЯД мы не можем тут же его (файл) удалить, так как дальше мы аттачим его к письму. И вот дальше нам надо снова проверить, что выгрузка на ЯД прошла и только тогда удалить.

2022-04-21 20:03 UTC, AntonZelinsky commented on apps/library/views/participation.py
> +            instance.file.delete()
Нужен этот файл для гугла и почты?

2022-04-21 20:04 UTC, AntonZelinsky commented on apps/library/services/spreadsheets.py
> +        except (ValueError, Error) as error:
Ааа, сори, меня сила с толку название исключения

2022-04-21 20:17 UTC, Omnomus commented on apps/library/views/participation.py
> +            instance.file.delete()
нет, туда ссылка только идет (раз мы решили, что нет смысла и ссылку отправлять, и прикреплять файл). Так что удаляю его в ParticipationExport.yandex если выгрузка прошла.

2022-04-22 16:49 UTC, Omnomus approved these changes

2022-04-22 17:17 UTC, AntonZelinsky approved these changes

2022-04-22 17:17 UTC, merged