brief response in api of question/participation
Studio-Yandex-Practicum/Lubimovka_backend pull request #384
Opened 2022-04-09 09:20 UTC by baby-platom

Тикет вашего PR (если есть):
    ___[ваш тикет](https://www.notion.so/Questions-Participation-post-9526b60db5114a55817ec6db24d05df2)___

Когда создаёте PR, убедитесь, что:

- [ ] вы проверили обновления в [брифе](https://www.notion.so/00f5d5a6d39e426fa1ea7ab69b694f07)
- [ ] синхронизировали изменения кода с [ER-диаграммой базы данных](https://drive.google.com/file/d/1RCIPaEgaLUSqek3znd38VPCKSzOlmJFy/view) связей моделей
- [ ] убедились, что модель OpenAPI проверена (в Swagger отображаются изменения)
- [ ] тесты все пройдены и нет конфликтов
- [ ] созданы необходимые миграции

Когда ваш PR смержен:

- [ ] если у вас были изменения в API, сообщите об этом команде Фронта, им это важно знать!

2022-04-09 10:26 UTC, AntonZelinsky requested changes

2022-04-09 10:26 UTC, AntonZelinsky commented on apps/info/views/question.py
>  class QuestionCreateAPIView(generics.CreateAPIView):
Перепиши, пожалуйста, с `generics.CreateAPIView` на `views.APIView` Сейчас логика стала очень запутанной. 
Из того что я вижу, я вообще не уверен что оно сработает, но даже если сработает, то тут какие-то странные операции происходят. 
Смотри стиль [написания кода на джа](https://github.com/HackSoftware/Django-Styleguide)нго, которого мы пытаемся придерживаться и другие `APIView` в нашем коде

2022-04-09 11:04 UTC, KonstantinRaikhert commented
@baby-platom Давай эту задачу заберу в свой ПР. Как раз занимаюсь "причесыванием" почтового сервиса.

2022-04-10 20:20 UTC, AntonZelinsky reviewed
Твой ПР затрагивает части, которые нужно порефакторить, поэтому и такие фидбеки.

2022-04-10 20:20 UTC, AntonZelinsky commented on apps/info/views/question.py
> +                raise ValidationError("Неверный ID шаблона Mailjet.")
В каждую из этих ошибок нужно ещё передать информацию из исключения. Неверные настройки, это слишком абстрактно. В исключении будет необходимая информация. 
Причём, при ошибке возвращаются валидационные ошибки на фронт. Это значит, пользователь сайта увидит какие-то очень странные сообщения, а сделать ничего не сможет!
На фронт не нужно ничего возвращаться, если запись сохранилась в базе. Если ошибка произошла потом, то её нужно всю залогировать, плюс, можно добавить сообщения которые отправляются сейчас на фронт.

2022-04-10 20:20 UTC, AntonZelinsky commented on apps/info/views/question.py
> +                raise ValidationError("Неверный ID шаблона Mailjet.")
Пример логгирования можно увидеть в другом методе апи. 
Его кстати, нужно переделать так же как этот.

2022-04-10 20:20 UTC, AntonZelinsky commented on apps/info/views/question.py
> +                raise ValidationError("Неверный ID шаблона Mailjet.")
Плюс, обрати внимание, что при отправке письма происходит попытка приатачить файл из `instance.file`, но из инстанс файл удаляется при отправке на диск.
Тут 2 варианта, либо выгружать файл из диска обратно, либо взять его из сериализатора. Я предлагаю второй вариант,  чтобы уменшить время отклика и не гонять в пустую байты, плюс, есть вариант с ошибкой загрузки на диск и его пришлось бы тут обрабатывать. Достань файл из сериализатора и передай его вторым параметром в функцию отправки писем.

2022-04-10 20:20 UTC, KonstantinRaikhert commented on apps/info/views/question.py
> +    class QuestionSerializer(serializers.ModelSerializer):
Что то я запутался. Это по стайлгайду так? Перенести сериализатор сюда. Как то нелогично, у нас все сериализаторы расположены в сериализаторах. Запутывает

2022-04-10 20:20 UTC, KonstantinRaikhert commented on apps/library/views/participation.py
> +    def create(self, request):
И тут. @AntonZelinsky наверно ты имел ввиду все на APIView переписать?

2022-04-10 20:22 UTC, AntonZelinsky commented on apps/info/views/question.py
> +    class QuestionSerializer(serializers.ModelSerializer):
Ну, это такой [джанго стайлгайд](https://github.com/HackSoftware/Django-Styleguide#apis--serializers). Коля уже много где так делал. Я не говорил переносить, но раз уж перенёс, то пусть будет. Тут ему самое место. Он нигде больше не используется и хорошо вписывается в картину

2022-04-10 20:23 UTC, AntonZelinsky commented on apps/library/views/participation.py
> +    def create(self, request):
Да, мы с тобой одновременно отписали и отправили фидбеки)

2022-04-10 20:31 UTC, KonstantinRaikhert commented on apps/info/views/question.py
> +                raise ValidationError("Неверный ID шаблона Mailjet.")
Ой, не надо.. Я рефакторю этот момент. И исправляю ошибки. Вроде договорились, что Платон сделает все на APIView, я подтяну изменения к себе. А то сейчас начнется))

2022-04-10 20:40 UTC, AntonZelinsky commented on apps/info/views/question.py
> +                raise ValidationError("Неверный ID шаблона Mailjet.")
Окей, я всё напутал)

2022-04-11 06:13 UTC, baby-platom commented on apps/library/views/participation.py
> +    def create(self, request):
Так, не учел)

2022-04-11 09:32 UTC, KonstantinRaikhert approved these changes

2022-04-11 09:47 UTC, AntonZelinsky approved these changes

2022-04-11 09:47 UTC, merged