Refactor/creation of duplicate entities
Studio-Yandex-Practicum/Lubimovka_backend pull request #396
Opened 2022-04-13 20:07 UTC by huppafr

Тикет вашего PR (если есть):
[Задача](https://www.notion.so/accb523b4ef34aa780eaba9b1e8cfea8)

В Админке в разделе [НОВОСТИ, ПРОЕКТЫ, БЛОГ] создавались дублирующие записи при неоднократном нажатии кнопки "Сохранить"
Подправил это дело. Теперь будет проверка на уникальность записей при помощи UniqueConstraint

2022-04-13 21:52 UTC, AntonZelinsky approved these changes

2022-04-15 00:39 UTC, nkiryanov requested changes
1. Беспокоит выбор полей проверки уникальности для блога. Кажется выбор не очень логичный. У этого решения есть какая-то логика, которую не знаю?
2. Думаю именование constraints неплохо привести к одному виду
3. Не создано миграции (упал тест). Она обязательна.

2022-04-15 00:39 UTC, nkiryanov commented on apps/articles/models/blog_items.py
> +        constraints = [
(пишу только тут, но для всех моделей)
По нашему [код-стайлу](https://github.com/Studio-Yandex-Practicum/Lubimovka_backend/blob/develop/docs/codestyle.md) лушче использовать кортежи, а не списки. То есть тут список желательно заменить на кортеж.

2022-04-15 00:39 UTC, nkiryanov commented on apps/articles/models/blog_items.py
> +                fields=("author_url", "author_url_title", "description"),
Смущает выбор полей для уникальности. Ссылка на автора и заголовок ссылки автора должны быть уникальными, а как же поле title? Оно наследуется из базового класса. Предлагаю ещё раз посмотреть на список уникальных полей.

Мне кажется title и description тут будет вполне достаточно, нет?
Вижу именно так сделано для новостей и вроде блог не должен в этом отношении отличаться.

2022-04-15 00:39 UTC, nkiryanov commented on apps/articles/models/blog_items.py
> +                name="unique_blog_entry",
тогда скорее `unique_blog_item`?

2022-04-15 00:39 UTC, nkiryanov commented on apps/articles/models/news_items.py
> +                name="unique_news",
Мысль вслух.

В этом PR задаешь 3 подобных ограничения для похожих моделей/сущностей, но именуешь поля каждый раз по разному:
- в одном случае добавляешь entry
- во втором множественное число
- в третьем по названию модели.

Неплохо придерживаться единого стандарта именования. Так меньше путаницы в будущем + проще понимать с чем имеешь дело и легче выбирать названия.

Модели назваются в единственном числе и тут неплохо дать навание соответственно. Может быть `unique_news_item` ?

2022-04-15 00:39 UTC, nkiryanov commented on apps/articles/models/news_items.py
>          return f"Новость {self.title}"
Что-то не понял когда это произошло, может быть даже это я накосячил 😳. В этой модели нарушен порядок [Model Style](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/#model-style). Может быть, под шумок, поправим? Метод `__str__` должен идти за классом Meta, не наоборот.

2022-05-22 19:15 UTC, closed without merging