new emails for volunteers, blog, and support pages
Studio-Yandex-Practicum/Lubimovka_backend pull request #405
Opened 2022-04-20 17:32 UTC by baby-platom

Тикет вашего PR (если есть):
    ___[ваш тикет](https://www.notion.so/e2e20e32d32a44fa8b9b15bf4d2fee80)___

Когда создаёте PR, убедитесь, что:

- [ ] вы проверили обновления в [брифе](https://www.notion.so/00f5d5a6d39e426fa1ea7ab69b694f07)
- [ ] синхронизировали изменения кода с [ER-диаграммой базы данных](https://drive.google.com/file/d/1RCIPaEgaLUSqek3znd38VPCKSzOlmJFy/view) связей моделей
- [ ] убедились, что модель OpenAPI проверена (в Swagger отображаются изменения)
- [ ] тесты все пройдены и нет конфликтов
- [ ] созданы необходимые миграции

Когда ваш PR смержен:

- [ ] если у вас были изменения в API, сообщите об этом команде Фронта, им это важно знать!

2022-04-20 18:26 UTC, nkiryanov requested changes
Комментариев не много. Но пора бы вьюшку переписать и вместо 13 раз дергать БД только один раз.

2022-04-20 18:26 UTC, nkiryanov commented on apps/info/views/settings.py
> +        email_on_volunteers_page = Setting.get_setting("email_on_volunteers_page")
Будет круто, если что-то пишем, то будем сразу думать про то как сделать оптимальнее.

В этой вьюшке делаем 13 (а может и больше) запросов к БД.

Уже давно написал метод получения нескольких значений настроек за раз. Давай его задействуем и будем обращаться к БД только один раз.

Пример такого есть в афише.

2022-04-20 18:26 UTC, nkiryanov commented on apps/info/admin.py
> +        if self.value() == "False":
Эта строка наверное лишняя. А что будет, если value() будет None?

2022-04-20 18:26 UTC, nkiryanov commented on apps/core/migrations/0016_additional_email_settings.py
> +from django.db import migrations
Неплохо все файлы с датамиграциями называть в одном ключе, чтоб потом их можно проще найти.

Я называю 0016_data_additional...

Наверняка, есть миграции где не придерживались этого правила, но стоит начать.

2022-04-21 12:48 UTC, AntonZelinsky commented on apps/info/admin.py
> +        if self.value() == "False":
Будет использован стандартный кверисет

2022-04-22 13:17 UTC, nkiryanov requested changes
Почти отлично, но есть вопросы/что поправить.

2022-04-22 13:17 UTC, nkiryanov commented on apps/info/selectors.py
> +    pr_director = Person.objects.filter(festivalteammember__is_pr_director=True).first()
Вот тут нет никакой ошибки, не уточнял?

Смотри — имя PR директора берём из настроек. А всё остальное из таблицы Person. Причем этот Person никак не связан с именем. Вопрос: а зачем тогда имя на настройках? Может быть из БД брать? Или правильное ли название в наятройках.

2022-04-22 13:17 UTC, nkiryanov commented on apps/info/views/settings.py
>          except email on contacts page
Хм. Тут докстринг в одну строчку норм помещается. Давай сделаем по красоте.

2022-04-22 13:17 UTC, nkiryanov commented on apps/info/views/settings.py
> +        response_data = selectors.feedback_settings_get()
То что логика уехала в selector — отлично!

2022-04-22 13:17 UTC, nkiryanov commented on apps/info/selectors.py
> +def feedback_settings_get() -> dict[str, Union[str, Any]]:
Имя которое в selector у афиши названо по [NameConvention](https://github.com/HackSoftware/Django-Styleguide#naming-convention), а тут совсем другое. У нас же ещё сущности feedback нет нигде.

Прочитай plz рекомендацию по ссылке и придумаем соответствующее название.

2022-04-22 13:17 UTC, nkiryanov commented on apps/info/selectors.py
> +    """Return feedback settings (mostly related to emails) queryset."""
Return feedback settings (mostly related to emails) queryset. — судя по докстрингу (если преревести) возвращаешь queryset, но ведь возвращаешь словарь. Нет ничего хуже докстринга, который устарел/не соответствует действительности.

Как понимаю брал за пример селектор из афиши и там он возвращает qs. То есть там всё верно и если берешь какой-то код за пример, то стоит делать осознанно.

Это нужно поправить и впредль быть вниматльным к таким мелочам.

2022-04-22 13:17 UTC, nkiryanov commented on docs/codestyle.md
> +1. При добавлении новых настроек миграцию стоет называть "00XX_data_additional..."
```suggestion
1. При добавлении новых настроек миграцию стоет называть "00XX_data_..."
```

Т.е без additional. Ведь не всегда это будет добавление чего-то к чему-то. Может быть создание чего-то нового. А начало названия с data — уже достаточно.

А так спасибо, что перенёс в правила.

2022-04-22 16:51 UTC, baby-platom commented on apps/info/selectors.py
> +    pr_director = Person.objects.filter(festivalteammember__is_pr_director=True).first()
Лазил в моделях, поле `is_pr_director` как раз таки существует на уровне `festivalteammember`, ее в настройках галочкой указываем

2022-04-22 17:35 UTC, nkiryanov requested changes
Получившийся код не работает: response_data = selectors.afisha_info_get()

2022-04-22 17:35 UTC, nkiryanov commented on apps/info/views/settings.py
> +        response_data = selectors.afisha_info_get()
Такс. Не могу не упомянуть вот [этот пост](https://yandex-students.slack.com/archives/C02ER615RT2/p1650546195047739?thread_ts=1650472799.816229&cid=C02ER615RT2) + если бы написали тесты, то увидел бы ошибку сразу.

И вообще IDE хотя бы ошибку не подчеркнул?

2022-04-22 17:35 UTC, nkiryanov commented on apps/info/selectors.py
> +            "pr_director_name": feedback_settings_data["pr_director_name"],
Вот тут сначала устанавливаешь значения, а потом делаешь pop. Логика чуть размазана (нужно прочитать весь селектор, чтоб увидеть удаление ключей). Почему бы не делать это сразу за одно действие. Будет красивее, понятнее и даже короче.

Вот это странно. Почему бы сразу не делать pop?
Чтоб было вообще всё по красоте

```suggestion
    pr_director_name = feedback_settings_data.pop("pr_director_name")
    photo_gallery_facebook_link = feedback_settings_data.pop("photo_gallery_facebook")
    for_press = {
        "pr_director": {
            "pr_director_name": pr_director_name,
            "pr_director_email": pr_director.email,
            "pr_director_photo_link": pr_director.image,
        },
        "photo_gallery_facebook_link": photo_gallery_facebook_link,
    }
    feedback_settings_data["for_press"] = for_press
    return feedback_settings_data
```

Но можно и так:
```suggestion
for_press = {
        "pr_director": {
            "pr_director_name": feedback_settings_data.pop("pr_director_name"),
            "pr_director_email": pr_director.email,
            "pr_director_photo_link": pr_director.image,
        },
        "photo_gallery_facebook_link": feedback_settings_data.pop("photo_gallery_facebook"),
 }
```

2022-04-22 17:35 UTC, nkiryanov commented on apps/info/selectors.py
> +    pr_director = Person.objects.filter(festivalteammember__is_pr_director=True).first()
Так. Понятно, это не просто имя PR директора, а имя в дательном падеже. По хорошему дать название настройке другое (иначе почему бы не брать имя просто из персоны? Зачем делаем для этого отдельную настройку).

По-моему так и называется `pr_directore_dative_name`

<img width="909" alt="screenshot_2022-04-22_at_20 25 15@2x" src="https://user-images.githubusercontent.com/70921439/164764227-62f53ee3-8556-4046-951a-ebd8d9266bb2.png">

2022-04-22 17:35 UTC, nkiryanov commented on apps/info/selectors.py
>      feedback_settings_data = Setting.get_settings(settings_keys)
Ок, только почему теперь тут feedback_settings_data. Это для фидбека?

2022-04-23 06:00 UTC, baby-platom commented on apps/info/views/settings.py
> +        response_data = selectors.afisha_info_get()
вот что значит когда поздним вечером делаешь(

2022-04-23 12:26 UTC, baby-platom commented on apps/info/selectors.py
> +            "pr_director_name": feedback_settings_data["pr_director_name"],
запутался в идее как осуществить, изначально думал лишь про то чтобы сначала достать, а потом удалить, не подумал что вот так сразу ведь можно)

2022-04-23 17:23 UTC, AntonZelinsky approved these changes

2022-04-23 17:23 UTC, AntonZelinsky commented on apps/info/selectors.py
> +    pr_director = Person.objects.filter(festivalteammember__is_pr_director=True).first()
Прекрасно, раз ты сюда влез, то вот тебе доп задачка, нужно в фабриках назначать ПР-директора по умолчанию. Это не блокер этого ПРа, но если будет минутка, то добавь 3 строчки https://www.notion.so/e45e380f8d014852815c15999c7a2b3e

2022-04-23 17:23 UTC, AntonZelinsky commented on apps/core/migrations/0017_data_additional_and_updated_email_settings.py
> +        settings_key="pr_directore_dative_name",
Тут ты создаёшь ключ, а хорошо бы обновлять существующую запись. Плюс, незабудь отразить изменения в 0002 миграции

2022-04-24 03:44 UTC, baby-platom commented on apps/core/migrations/0017_data_additional_and_updated_email_settings.py
> +        settings_key="pr_directore_dative_name",
Тут и до этого брал get_or_create и update_or_create т к думал что так вернее, чтобы точно ошибки не было

2022-04-24 09:09 UTC, nkiryanov requested changes
К API у меня вопросов нет (не запускал, но вроде работать должно).

Что нужно подправить:
1. В названии ключа ошибка. Да, это я написал в прошлом ревью предложение по имени и там допустил ошибку, но не повод копипастить и вживлять её в прод 😅
2. Сейчас создаешь новый ключ настройку, а нужно менять название старой. Заодно поправить недочеты которые видишь (добавить ключ в начальную миграцию).

У меня предложение: очень много изменений связанных с заменой имени настройки. Выбери plz вариант как тут поступить. Оба варианта ок:
1. откатить изменения по замене имени настройки тут (то есть оставить pr_director_name) и сделать замену имени в отдельном PR
2. довести тут до ума

2022-04-24 09:09 UTC, nkiryanov commented on apps/info/admin.py
>          js = ("admin/info/js/FestivalTeamFooter.js",)
Обрати внимание — везде меняешь название ключа. Дела хорошее, но нужно внимательно посмотреть где оно используется (а были бы тесты, то и смотреть бы не пришлось. Но как тесты писать на js код хз).

К чему клоню: js скрипт не поправлен и работать не будет.

2022-04-24 13:45 UTC, baby-platom commented on apps/info/selectors.py
> +def info_settings_get() -> dict[str, Any]:
тогда еще вариант boolean, т к "plays_reception_is_open": true

2022-04-24 15:16 UTC, AntonZelinsky commented on apps/core/management/commands/filldb.py
> +    command.stdout.write(command.style.SUCCESS(f"{len(objects)} {text} успешно создан."))
Это уже какая-то внутренняя логика метода уведомления. Если ты хочешь сделать другое уведомление, то внутри метода `notification` проверяй количество элементов `objects` и в зависимости от этого выводи.

2022-04-24 19:58 UTC, nkiryanov approved these changes
Апрувну, но вопрос с `Params` и фабриками актуальный.

Есть ещё несколько небольших комментариев.

2022-04-24 19:58 UTC, nkiryanov commented on apps/info/factories.py
> +        is_pr_director = True
А можешь рассказать что это делает?
С функционалом вроде как знаком, но тут два варианта: 
- либо недостаточно знаком я
- либо .. либо будет здорово описать ту логику которую в этот параметр вкладывал, что оно делает. Мне не понятно.

2022-04-24 19:58 UTC, nkiryanov commented on apps/core/management/commands/filldb.py
> +            team_with_pr_director = FestivalTeamFactory.create_batch(1)
Для этого есть просто create или ().
Так работать тоже будет, но не красиво и не оч понятно.

Предполагаю, что тут сделал "по образу и подобию", но у нас нет задачи выпустить PR здесь и сейчас, а задача сделать +/- качественно. Это значит стоит прочитать хотя бы основу в документации. Принцип работы create, create_batch, build и прочее там в самом начале.

2022-04-24 19:58 UTC, nkiryanov commented on apps/core/migrations/0002_setting_initial_data.py
> +    Setting.objects.create(
Такс. Если не переименовываем поле, то хотя бы поправить ошибки с ним нужно, м?

Мы же обнаружили, что почему-то первый раз имя pr_director_name задается только в 15 миграции. Давай его тоже сюда добавим, чтоб не забыли?

А переименуем в другой раз.

2022-04-24 19:58 UTC, nkiryanov commented on apps/info/tests/conftest.py
> +def festival_team_pr_director(persons_with_image):
Эта фикстура сейчас нигде не используется. Её стоит удалить.

2022-04-25 12:43 UTC, baby-platom commented
оставил лишь модификацию notification, а так пусть фактори в другом пиаре уже будет хорошо сделанная

2022-04-25 13:02 UTC, merged