Feature/preview unpublished pages
Studio-Yandex-Practicum/Lubimovka_backend pull request #416
Opened 2022-04-26 10:44 UTC by stepakiselev

Тикет вашего PR (если есть):
    ___[ваш тикет](https://www.notion.so/0bab7ccacb2b4dbd81f6358650abfa5a)___

**Задача:** 

Создать кнопку в админке с предпросмотром неопубликованных станиц блогов, проектов, новостей и спектаклей.

**Подробности задачи:**

Должна быть кнопка, нажав на которую, будет открыт сайт в новом окне и там можно будет посмотреть как выглядит эта статья. То есть, отрендерить её должен фронт.

Тут нужно будет тесно по взаимодействовать с фронтом

По-хорошему, должна быть какая-то защита против того, чтобы случайным или не случайным образом, пользователи не попали на неопубликованные статьи. Как это сделать? Вариантов масса. Например, к обычному урлу статьи добавлять какой-то хеш, а фронт должен его передать на бэк как параметр запроса. В апишке, мы же должны проверить, что такой хэш соответсвует id статьи и тогда отдавать её [https://stage.dev.lubimovka.ru/news/20?hash=3dmr7pn1q](https://stage.dev.lubimovka.ru/news/20?hesh=3dmr7pn1q). Только может ключевое слово лучше придумать чем hash. 

Чтобы не вытягивать из базы данных полую запись и не сверяться или уж тем более не создавать колонку в базе данных, нужно проверять соответствует ли хэш до запроса к бд. Для этого, можно сделать простой алгоритм генерации и проверки хэша. Например

```jsx
hash(SECRET_KEY + id + datetime.day)[0:5]
```

Так, ссылка будет уникальной каждый день для каждой записи.

Для опубликованных статей, кнопка пред просмотра пусть заменяется на обычный просмотр.

P.S. Не совсем уверен что удалось реализовать верную логику.

2022-04-26 13:17 UTC, Omnomus commented on apps/articles/views/blog_items.py
>          context = {"request": request}
но получается, что и по обычному роуту теперь можно получить неопубликованный блог?

2022-04-26 14:34 UTC, stepakiselev commented on apps/library/utilities.py
> +    word = item[obj.get_class_name()]
да, я тоже это понимал. но не смог найти способ вытащить название модели из контекста в шаблон. Вот этом месте: templates/admin/includes/preview_unpublished_button.html
```
{% load i18n %}
<form action="" method="GET">
     {% if original.get_class_name == 'BlogItem' %}
       <a class="button" href="{% url 'blog-item-detail-preview' original.id hash %}" >{% if original.get_status_display != 'Опубликовано' %} Предпросмотр страницы {% else %} Просмотр страницы {% endif%}</a>
     {% elif original.get_class_name == 'NewsItem' %}
       <a class="button" href="{% url 'news-item-detail-preview' original.id hash %}" >{% if original.get_status_display != 'Опубликовано' %} Предпросмотр страницы {% else %} Просмотр страницы {% endif%}</a>
     {% elif original.get_class_name == 'Project' %}
       <a class="button" href="{% url 'project-item-detail-preview' original.id hash %}" >{% if original.get_status_display != 'Опубликовано' %} Предпросмотр страницы {% else %} Просмотр страницы {% endif%}</a>
     {% elif original.get_class_name == 'Performance' %}
       <a class="button" href="{% url 'performance-item-detail-preview' original.id hash %}" >{% if original.get_status_display != 'Опубликовано' %} Предпросмотр страницы {% else %} Просмотр страницы {% endif%}</a>
     {% endif%}
</form>
```

2022-04-26 14:37 UTC, stepakiselev commented on templates/admin/includes/status_buttons.html
> +      {% include "admin/includes/preview_unpublished_button.html" %}
да, попробую без него обойтись, это видимо осталось в процессе отладки

2022-04-26 14:51 UTC, stepakiselev commented on apps/articles/views/blog_items.py
>          context = {"request": request}
упс, тут кажется при чистке кода удалил лишнее

2022-04-26 20:49 UTC, nkiryanov requested changes
У меня много комментариев получилось по стилю и главное по функционалу: сейчас нет никакой проверки хэша, то есть предпросмотреть можно любую страницу, нет ограничений на права доступа.

2022-04-26 20:49 UTC, nkiryanov commented on apps/articles/views/news_items.py
> +class PreviewNewsItemDetailViewSet(NewsItemsViewSet):
Тут плохо:

1. Наследуешь от ViewSet. В этом классе будут методы для листинга, фильтрации, получения конкретного элемента, но будешь использовать только один метод. Зачем такая сложная структура (которая не известно как будет работать и когда "выстрелит в ногу"), когда можно написать 1 простой API View? Да, кода возможно станет больше, но он будет простой, предсказуемый и будет делать ровно 1 вещь которую от него просят.
2. Не вижу где передаешь <hash> и проверяешь его. Или там мы можем открыть любую новость?
3. Давай писать по StyleGuied и соблюдать [NamingConvention](https://github.com/HackSoftware/Django-Styleguide#naming-convention-1)
4. Докстринг.

2022-04-26 20:49 UTC, nkiryanov commented on apps/articles/views/projects.py
> +    def get(self, request, id, **kwargs):
Такс, я что-то пропустил наверное. А где здесь передаешь <hash>, проверяешь его. Или там мы можем открыть любой проект?

2022-04-26 20:49 UTC, nkiryanov commented on apps/library/models/performance.py
> +    def get_class_name(self):
Удалить?

2022-04-26 20:49 UTC, nkiryanov commented on apps/library/utilities.py
> +    """Set a button to view the page."""
По-моему плохой выбор в расположение функции и докстринг, который скорее запутывает.

Добавляет "кнопку" для view. В views не используется, что такое page не понятно, что такое obj тоже. Нужно весь код пересмотреть, чтоб понять что это и для чего.

Эта функция добавляения какой-то кнопки в админку? Так давайте сделаем его миксином админки или добавим в базовый админки.

Аналогия с тем, что написать сюда метод get для вью класса. Работать будет, но кто догадается его тут искать?

2022-04-26 20:49 UTC, nkiryanov commented on apps/library/utilities.py
> +    word = item[obj.get_class_name()]
Комментарий Ксюши актуалный, а про то, что не удалось вытащить в шаблон что-то не понял. Можешь тут подробнее написать?

2022-04-26 20:49 UTC, nkiryanov commented on apps/library/utilities.py
> +    word = item[obj.get_class_name()]
Что такое word?
Код будет читаться проще, если давать осмысленные названия переменным.

2022-04-26 20:49 UTC, nkiryanov commented on apps/library/admin/events.py
> +    def button_preview_page(self, obj):
Мы тут вызываем функцию в функции.
Почему бы этот метод сразу не определить в базовом классе админки или написать миксин?

+ сюда бы досктсринг для чего нужно и как работает.

2022-04-26 20:49 UTC, nkiryanov commented on apps/core/utils.py
> +def create_hash(object_id):
Наверное просто ID. Это утилитка, она универсальная и и делает хэш на основе номера и времени.
Пожалуй ещё параметр можно добавить (название или номер модели, иначе хэш для разных объектов будет одинаковым).

Что ещё важно: получаемый в таком виде хэш точно будет валидным для url? Не может быть такого, что в url будет символы, которые нельзя использовать?

2022-04-26 20:49 UTC, nkiryanov commented on apps/core/mixins.py
> +        preview_page_hash = create_hash(object_id)
Возможно просто не понима, объясните plz.
Насколько вижу для кнопки "StatusButtonMixin" добавляем хэш.

То есть миксин для статуса, а добавляем хэш. Тут точно всё правильно?

2022-04-26 20:49 UTC, nkiryanov commented on apps/content_pages/querysets.py
> +    def current_and_published(self, object_id):
Насколько вижу этот метод в итоги не нужен, хотя он вроде норм (ниже пишу комментарии по правкам и если им последовать, то вроде можно будет удалить).

2022-04-26 20:49 UTC, nkiryanov commented on apps/articles/admin/news_items.py
> +        """Set a button to view the page."""
Создание новой апишки через наследование от вьюсета ниже то, как делать не стоит :)
Когда напишешь там норм метод, то и тут станет универсальным.

2022-04-26 21:26 UTC, AntonZelinsky commented on apps/articles/urls.py
> +        name="blog-item-detail-preview",
Тут уже без меня вс проревьювили. Как уже написал в ЛС, нужно сделать так, чтобы урл отвечающий за отдачу блогов, например, отдавал скрытые блоги. Пример урла привёл ниже.

https://test.dev.lubimovka.ru/api/v1/library/performance/preview/6/3285208066514059590/

https://test.dev.lubimovka.ru/api/v1/library/performance/6/?hash=3285208066514059590
Вьюшка соответственно тоже одна

2022-04-26 23:00 UTC, AntonZelinsky commented on apps/articles/admin/news_items.py
> +        return mark_safe(f'<a class="button" href={preview_link}>{label_button}</a>')
Ещё, на минуточку, эту страницу должен рендерить обычный фронт, а не наша апишка)

2022-04-26 23:05 UTC, AntonZelinsky commented on apps/articles/admin/news_items.py
> +        return mark_safe(f'<a class="button" href={preview_link}>{label_button}</a>')
И добавь стиль `padding: 10px 15px;`, чтобы кнопка была нормального размера

2022-04-26 23:06 UTC, AntonZelinsky commented on apps/articles/admin/blog_items.py
> +        "button_preview_page",
Мне кажется, на списке записей эта кнопка не имеет смысла. Она нужно для предпросмотра, а не для быстрого перехода

2022-04-26 23:13 UTC, AntonZelinsky commented on apps/articles/admin/news_items.py
> +        return mark_safe(f'<a class="button" href={preview_link}>{label_button}</a>')
Кнопку лучше сделать последней в списке, так как лейбл статуса и кнопки изменения статуса даже по смыслу ближе стоят
Может ещё цвет сделать кнопки зелёненький? чтобы выделялось.
![image](https://user-images.githubusercontent.com/1431279/165407495-ac8811b0-3ff4-40be-95fe-72a476e2fc88.png)

2022-04-29 17:19 UTC, stepakiselev commented on templates/admin/includes/preview_unpublished_button.html
> +     {% elif original.get_class_name == 'NewsItem' %}
Ксюш, думаешь стоит менять basename в урлах? в каких еще местах они могут быть задействованы? так чтобы не поломать что работающее. По идеи чтобы это прием оплатить нужно поменять только basename="news_item" и name="blog-item-detail"

2022-04-29 19:01 UTC, Omnomus commented on templates/admin/includes/preview_unpublished_button.html
> +     {% elif original.get_class_name == 'NewsItem' %}
так тут вроде используются твои урлы, которые с detail. ты же им сам назначил basename? то есть только твой код надо вспомнить, использовал ли ты их где-то еще

2022-04-30 16:50 UTC, nkiryanov requested changes
Есть что поправить.
1. Функционал размазан по разным блокам. Нужно переписать [по стайл-гайду](https://github.com/HackSoftware/Django-Styleguide).2. 
2. Правки и замечания поменьше, но тоже важные

2022-04-30 16:50 UTC, nkiryanov commented on apps/articles/urls.py
> +news_item_urls = [
Я бы оставил ровно так, как это было ранее. Почему: потому что логично сделать ровно точно так же как сделано с блогами: переписать ViewSet на APIView и тогда роуты норм будут.

Тут в отдельный список добавляешь только один элемент и только вводишь в заблуждение. В них ожидаешь news, но большая часть news будет в router. Зачем в общем?

2022-04-30 16:50 UTC, nkiryanov commented on apps/articles/urls.py
> +    basename="newsitem",
Зачем? Только читается хуже.

2022-04-30 16:50 UTC, nkiryanov commented on apps/articles/tests/blog_items/conftest.py
> +        # id=200,
?

2022-04-30 16:50 UTC, nkiryanov commented on apps/articles/tests/blog_items/test_selectors.py
> +    blog_items_published = BlogItem.ext_objects.published()
Здесь и далее: смотри комментарий к селектору + к вью-функции.

2022-04-30 16:50 UTC, nkiryanov commented on apps/articles/tests/blog_items/tests_views/test_blog_item_detail.py
> +BLOG_ITEM_DETAIL_URL = reverse("blogitem-detail", args=(100,))
Ну так стало читать сложнее. Зачем?

2022-04-30 16:50 UTC, nkiryanov commented on apps/articles/views/blog_items.py
> +    def get(self, request, id, **kwargs):
Нужно переделать.
Смотрю код и складывается впечатление, что с [стайлгайдом не знакомился](https://github.com/HackSoftware/Django-Styleguide). Если нет, прочитай его plz. Мы сейчас стараемся писать по нему и он ОЧЕНЬ симпатичный, а главное подходит для большинства сложной логики. Не размазывает всё по разным файлам и даже очень сложную бизнес-логику удается вполне красиво организовывать.

Посмотри plz цели этого стайлгайда. Тут делаешь делаешь ровно обратное: бизнес-логику размазываешь по разным блокам приложения. **В вьюшках не должно быть логики.**

Вывод такой: подумай и перепиши по стайлгайду. Если возникает вопрос как, то сделай для одной модели, покажи, потом расширим на оставшиеся.

Вообще не понимаю, зачем просмотр непубликованной сущности пытаешься запихнуть в этот же APIView.

Вообще я бы делал так:

1. Написал отдельный APIView.
2. Написал селектор для сравнения хешей и сравнивал хэш из url там.
3. Вообще не понимаю зачем делаешь отдельный queryset если новость неопубликованная. Понимаешь что в нём происходит вообще и для чего? Если его не трогать, то данные будут отдаваться ровно как нужно
4. API View должен получиться простой, буквально в 3-5 строк

2022-04-30 16:50 UTC, nkiryanov commented on apps/articles/views/blog_items.py
> +        ingress = request.GET.get("ingress", "")
1. Что такое inggress? Это плохое название переменной. 
2. Зачем делать пустому ingress по умолчанию пустую строку, ведь None даже информативнее.
3. Опять про именование: почему ингресс потом ещё должен быть равен хэшу?

2022-04-30 16:50 UTC, nkiryanov commented on apps/articles/views/news_items.py
> +    def get_queryset(self, **kwargs):
Смотрим комментарий для блогов.

2022-04-30 16:50 UTC, nkiryanov commented on apps/articles/views/projects.py
> +    def get_queryset(self, **kwargs):
Смотрим комментарий для блогов.

2022-04-30 16:50 UTC, nkiryanov commented on apps/core/mixins.py
>  class StatusButtonMixin:
Писал в комменатриях раньше. Этот класс называется "StatusButtonMixin". Что в нём делает хэш?

Вот покажут тебе этот класс и нужно будет предположить что там происходит. Сколько человек из 1000 предположат что там что-то происходит с хэшем и кнопкой предпросмотра. Думаю 0.

2022-04-30 16:50 UTC, nkiryanov commented on apps/core/mixins.py
> +        ingress_hash = create_hash(object_id, current_model_name)
Не совсем понимаю как выбрано название ingress_hash. Мы же тут формируем хэш для будущей ссылки. Почему бы так его и не назвать.

link_hash, daily_link_hash и тд.

2022-04-30 16:50 UTC, nkiryanov commented on apps/core/mixins.py
> +        extra_context["model_name"] = current_model_name
В целом тут ок, но можно сделать всё за раз словарем. Будет красивее выглядеть. Что-то такое в вью для main делаем.

2022-04-30 16:50 UTC, nkiryanov commented on apps/core/utils.py
> +from config.settings.base import HASH_SECRET_KEY
Нужно исправить. Посмотри пожалуйста как правильно получать доступ к настройкам у django.

2022-04-30 16:50 UTC, nkiryanov commented on apps/core/utils.py
> +def create_hash(object_id, model_name):
Это не приниципиально, но model_name более "большая" сущность и её хочется передать первой. Хотя так тоже ок.

2022-04-30 16:50 UTC, nkiryanov commented on apps/core/utils.py
> +    hex_dig = hash_object.hexdigest()
Что такое hex_dig. У нас не хватает длины для названия переменных?

2022-04-30 16:50 UTC, nkiryanov commented on apps/core/utils.py
> +    return hex_dig[0:5]
Вот тут не знаю. Была какая-то обсужденная причина почему брать только часть хэша? Я бы скорее брал весь хэш.

2022-04-30 16:50 UTC, nkiryanov commented on apps/library/models/performance.py
> +from ...content_pages.querysets import ContenPageQuerySet
Вот это оч плохо.
Тут думаю если обратишь внимание, то не нужно объяснять почему. Если не понятно дай знать, распишу.

2022-04-30 16:50 UTC, nkiryanov commented on apps/library/models/performance.py
>  from ...content_pages.utilities import path_by_app_label_and_class_name
Это тоже плохо. Пропустили потому что не заметили. Тоже давай исправим, это быстро.

2022-04-30 16:50 UTC, nkiryanov commented on apps/library/urls.py
> +    basename="performance",
Да, вот тут в ед. числе правильнее и скорее ожидаешь. 👍

2022-04-30 16:50 UTC, nkiryanov commented on templates/admin/includes/preview_unpublished_button.html
> +{% load i18n %}
А что-то не вижу такого файла для блогов и тд. Где-то уже есть, ага?

2022-04-30 17:06 UTC, nkiryanov commented
> Несколько вопросов есть.
> 
> Почему во вьюфункциях BlogItem сериализаторы находятся внутри вьюх?

Написал в ревью и приложил ссылку на стайл-гайд. Вообще думал, что всем известно, что стараемся писать по стайл-гайду и с ним знакомы. Не был знаком? Может быть не одинок и нужно для всех "новеньких" ребят написать новость?

> Изминение размера кнопки подключил через autocomplete.css. На сколько это правильно, или лучше создать новый файл и снова подключать через base.html? Или лучше переименовать autocomplete.css в универсальное название?

Хорошо что написал 👍. Я даже не заметил. Ксюша @Omnomus, сможешь эту штуку глянуть. Она вроде тебе знакомее. Но если нет, уделю время, разберусь, посмотрю.

> Выложил ПР чтобы можно было глянуть и отметить ошибки. Еще не доделал упрощение `create_hash`

👍

2022-05-03 12:57 UTC, stepakiselev commented on apps/articles/views/blog_items.py
> +    def get(self, request, id, **kwargs):
Переписываю логику и снова возникает вопрос. делать разные вьюхи и прокладывать путь preview/news_item/3/?hash= или все в одной и путь news_item/3/?hash=

так как разница в вьюфункциях будет совсем маленькая.
@nkiryanov @AntonZelinsky @Omnomus

2022-05-03 15:21 UTC, nkiryanov commented on apps/articles/views/blog_items.py
> +    def get(self, request, id, **kwargs):
Моё предложение описано в комментарии: писал отдельный вью-класс. В нем всего будет 5-6 строк кода. Похожесть будет только в использовании того же сериализатора и один раз того же селектора. Но будет и другая логика. Это же предлагает стайлгайд

2022-05-03 22:27 UTC, AntonZelinsky commented on apps/articles/views/blog_items.py
> +    def get(self, request, id, **kwargs):
Я не вижу особого смысла делать отдельный роут и вьюшку, ведь то что мы добавили предпросмотр, это всё то же самое, просто доп условие, по сути, авторизация. Тут можно добавить ещё один селектор, и в нём через `get_object_or_404(BlogItem, id)` сделать запрос, а всё остальное в общую между селекторами функцию отдать, чтобы запомнить модель. Вообще, хорошо бы prefetch добавить, а не делать десяток запросов, но это можно оставить на другой ПР.

Если делать ещё одну вьюшку, то прийдётся сериализатор выносить наверх, так как он вложенный в этот класс. Плюс, будет на 95% дубликат селектора, так как в текущем `BlogItem.ext_objects.published()` используется и от этого не уйти.

2022-05-03 22:27 UTC, AntonZelinsky commented on apps/articles/views/blog_items.py
> +    def get(self, request, id, **kwargs):
Я так глянул со стороны, и нам вообще нет особого смысла использовать `BlogItem.ext_objects.published()`, можно просто передавать в селектор флаг `is_published` и в зависимости от него строить запрос. Это добавить всего один фильтр, а всё станет намного проще. Одна вью, один селектор, один сериализатор, всё очень просто и прозрачно

2022-05-03 22:27 UTC, AntonZelinsky commented on apps/articles/views/blog_items.py
> +        ingress = request.GET.get("ingress", "")
Согласен, `preview_hash` информативнее. Сперва нужно проверять что он есть, а потом считать сумму, а то лишняя мозговая активность получается. `if preview_hash and preview_hash == calculate_hash(id)`

2022-05-03 22:27 UTC, AntonZelinsky commented on apps/core/utils.py
> +from config.settings.base import HASH_SECRET_KEY
В код стайле проекта описано! А вообще, не вижу смысла вводить ещё одну переменную, только множество сложностей в поддержке добавится. Пусть будет обычный `SECRET_KEY`

2022-05-03 22:27 UTC, AntonZelinsky commented on apps/core/utils.py
> +    return hex_dig[0:5]
А какая разница? моя идея в 5 символов в том, чтобы url был красивее, потому что sha1 отдаёт 40 символов. С такими длинными адресами как минимум неудобно работать.

2022-05-03 22:27 UTC, AntonZelinsky commented on apps/core/utils.py
> +def create_hash(object_id, model_name):
Хэш сумма не создаётся, а рассчитывается `calculate_hash`

2022-05-03 22:27 UTC, AntonZelinsky commented on apps/articles/views/news_items.py
> +    def get_queryset(self, **kwargs):
В одном месте вьюсеты, в другом `APIView`, предлагаю всё на `APIView` переделать

2022-05-04 02:19 UTC, nkiryanov commented on apps/articles/views/blog_items.py
> +    def get(self, request, id, **kwargs):
Потому что сделать отдельный вью-класс решение более прозрачное. Если уж переходим на APIView. Они предполагают, что в них не должно быть много логики. В случае объединения получается непрозрачный url + нужно писать логику, а был ли передан хэш.

С отдельным вью-классом можем явно задать url: `blog/<int: id>/preview/<str: hash> `и явно передавать параметры в вью-функцию и не заниматься поискам по kwargs, что непрозрачно. Отдельный вью-класс лучше масштабируется — нужно будет поменять логику или url или убрать этот функционал.

Про сериализаторы: вынести сериализаторы из вью-функцию потребуется, но это по-моему ок. Я бы склонялся писать сирализаторы отдельно и явно наследоваться от них в классах. Так получается более компактные вью-классы и главное избавляет от кучи проблем когда в одном подклассе нужно получить доступ к другому подклассу. По-моему самое спорное решение из стайл-гайда.

2022-05-04 02:24 UTC, nkiryanov commented on apps/library/models/performance.py
> +    objects = models.Manager()
1. Нет, не будет по умолчанию. По умолчанию будет явно заданный менеджер в классе.
2. Это best practices — явно оставлять стандартный менеджер. Иначе приводит к сложным ошибкам, если кто-то от этой модели наследуется.

В общем рекомендую оставить как есть + могу поделиться главой из книги где такие рекомендации вычитал.

2022-05-04 12:12 UTC, AntonZelinsky commented on apps/articles/views/blog_items.py
> +    def get(self, request, id, **kwargs):
Окей, будь по твоему. 
Только такой урл  `blog/<int: id>/preview?hash=<str: hash>` мне больше нравится, так как hash это не часть пути к ресурсу, а что-то для авторизации

2022-05-04 12:49 UTC, stepakiselev commented on apps/core/utils.py
> +from config.settings.base import HASH_SECRET_KEY
то есть просто записать в константы? SECRET_KEY = "some_secret_key"

2022-05-04 15:13 UTC, AntonZelinsky commented on apps/core/utils.py
> +from config.settings.base import HASH_SECRET_KEY
Она уже есть там.

2022-05-04 21:39 UTC, nkiryanov commented on apps/core/utils.py
> +    return hex_dig[0:5]
Подумал и посмотрел. Да, пожалуй тут от нас большой секурности не нужно. Согласен.

2022-05-04 21:40 UTC, nkiryanov commented on apps/articles/views/blog_items.py
> +    def get(self, request, id, **kwargs):
Ага, так ещё красивее. 👍

2022-05-06 21:59 UTC, AntonZelinsky commented on apps/library/models/performance.py
> +    ext_objects = ContenPageQuerySet.as_manager()
Ты последний редактировал `ContenPageQuerySet`, поэтому поправь в нём значение фильтра со строки на choose класс. И у меня вопросы к названию этого кверисета, что значит `ContenPage`? там вроде бы есть чёткая логика внутри, которая ниакак не отражается в названии.
И кстати, тут ты говоришь, что `Performance.objects.all()` вернёт все опубликованные записи, но разве их не обработает стандартный `objects = models.Manager()`
![image](https://user-images.githubusercontent.com/1431279/167216219-61b57d43-f693-4826-97a8-6ca81b548397.png)

2022-05-06 21:59 UTC, AntonZelinsky commented on apps/library/urls.py
> +    path("library/", include(performance_item_urls)),
Предлагаю выкинуть DefaultRouter и перенести всё в performance_item_urls или наоборот, главное, чтобы читаемее было. А то так, сразу возникает путаница и непонимание.

2022-05-06 21:59 UTC, AntonZelinsky commented on apps/library/urls.py
> +        name="performance-detail-preview",
Этот комент возник скорее всего из-за того, что ты из админки идёшь на этот апи, а не на страницу фронта. Это уже со страницы фронта сюда запрос должен идти, поэтому, этот комент и такой подход не правильные

2022-05-06 21:59 UTC, AntonZelinsky commented on templates/admin/includes/preview_unpublished_button.html
> +       <a class="button" href="{% url url_name original.id %}?preview_hash={{ link_hash }}" >{% if original.get_status_display != 'Опубликовано' %} Предпросмотр страницы {% else %} Просмотр страницы
Просмотр страницы на фронте должен идти на реальную страницу, а не на страницу пред просмотра. Есть смысл генерировать ссылку в миксине, а сюда передавать только значение линки и название кнопки.

2022-05-07 14:44 UTC, AntonZelinsky commented on apps/core/mixins.py
> +        current_model_name = obj._meta.model_name
[Посмотри как тут](https://github.com/Studio-Yandex-Practicum/Lubimovka_backend/blob/develop/apps/info/admin.py#L316) из админ модели обращаются к модели и делают запрос к базе

2022-05-08 02:46 UTC, stepakiselev commented on apps/library/models/performance.py
> +    ext_objects = ContenPageQuerySet.as_manager()
> Ты последний редактировал `ContenPageQuerySet`, поэтому поправь в нём значение фильтра со строки на choose класс. 
@AntonZelinsky я чуточку не понял этот момент.

2022-05-08 02:49 UTC, stepakiselev commented on apps/library/models/performance.py
> +    ext_objects = ContenPageQuerySet.as_manager()
> И кстати, тут ты говоришь, что `Performance.objects.all()` вернёт все опубликованные записи, но разве их не обработает стандартный `objects = models.Manager()`
Ох, этот момент я упустил, не стал лезть в другую вьюху, а стоило глянуть. Наверно точно, надо переключаться на создание тестов.

2022-05-08 16:23 UTC, stepakiselev commented on apps/articles/selectors.py
> +    raise Http404()
значит так нельзя делать? Вроде все работает)))

2022-05-08 16:43 UTC, AntonZelinsky commented on apps/articles/selectors.py
> +    raise Http404()
Можно, извини, я подумал что тут ретурн, а не райз. Всё окей)

2022-05-10 00:30 UTC, AntonZelinsky commented on apps/library/static/css/autocomplete.css
> +   background: #00CC99;
Давай чуть цвет поменяем
```suggestion
   background: #759e4a;
```
и добавим при наведении изменение цвета
```
a.button:hover {
    background: #435b2a;
}
```

2022-05-10 00:30 UTC, AntonZelinsky commented on templates/admin/includes/preview_unpublished_button.html
> +<a class="button" href="/api/v1/{{ url_name }}/{{ original.id }}/" >Просмотр страницы</a>
Но то что ссылки работают, и хорошо, я убедился!)

2022-05-10 00:30 UTC, AntonZelinsky commented on apps/library/models/performance.py
> +    ext_objects = PublishedContentQuerySet.as_manager()
Не вижу смысла делать дополнительный объект. Так как при обращении к `PublishedContentQuerySet` будет использоваться весь стандартный функционал, то есть, `Performance.ext_objects.all()` вернёт все записи у этой модели,  `Performance.ext_objects.published()`, только у опубликованных. Следовательно, `ext_objects` не имеет смысла. Есть смысл сделать доп метод для кверисета `def preview(self, id):` для предпросмотра.
```
class PublishedContentQuerySet(models.QuerySet):
    def published(self):
        """Return only published objects."""
        qs = self.filter(status=Status.PUBLISHED)
        return qs
```

`objects = PublishedContentQuerySet.as_manager()`

Может я конечно не прав, но что-то подсказывает, что так тоже всё будет работать.

2022-05-10 07:02 UTC, stepakiselev commented on apps/articles/urls.py
> +        name="news-item-detail-preview",
@AntonZelinsky, то есть во всех урлах если в `basname` и `name` стоит дефис поменять на нижнее подчеркивание. Просто я глянул по урлам там много где придется менять, ничего не поломаю?

2022-05-10 13:18 UTC, AntonZelinsky commented on apps/articles/urls.py
> +        name="news-item-detail-preview",
Ой, это я затупил, в 3 часа ночи писал и не знаю куда вообще смотрел. Тут всё окей)

2022-05-10 13:45 UTC, stepakiselev commented on apps/library/models/performance.py
> +    ext_objects = PublishedContentQuerySet.as_manager()
@AntonZelinsky, а тогда и в `AbstractContentPage` у блогов тоже поменять на `objects = PublishedContentQuerySet.as_manager()`

по поводу доп метода `def preview(self, id):` думаете точно следует его добавить? он будет возвращать один объект, это для лучшей читаемости?

2022-05-10 18:15 UTC, AntonZelinsky commented on apps/library/models/performance.py
> +    ext_objects = PublishedContentQuerySet.as_manager()
Да, везде поправить, ведь логика общая. Если нужно загружать 1 объект, то нужен метод который отдаёт один объект. Зачем отдавать весь список, чтобы потом ещё дополнительно отфильтровать то что нужно, если можно сразу отдать то что нужно. В этом суть инкапсуляции. Можешь ещё почитать про такую штуку как DDD, там вообще всё на таких методах делается

2022-05-11 16:19 UTC, AntonZelinsky approved these changes
Всё окей, отписал ещё в ЛС, что нужно чуть-чуть переделать миксин, чтобы Там формировалась ссылка , в зависимости от потребностей страницы. Так же, чтобы ссылка вела на новую страницу

2022-05-11 19:11 UTC, Omnomus commented on templates/admin/includes/preview_unpublished_button.html
> +{% if original.get_status_display != 'Опубликовано' %}
А может тут Опубликовано не хардкодить? Передать в переменных тоже. 
extra_context["published"] = Status.PUBLISHED.label

2022-05-11 19:11 UTC, Omnomus commented on apps/content_pages/querysets.py
> +        qs = get_object_or_404(self, id=id)
это занудство, конечно. но мы же тут один объект возвращаем, лучше obj = ...?

2022-05-12 10:51 UTC, Omnomus approved these changes

2022-05-12 11:36 UTC, AntonZelinsky commented on templates/admin/includes/preview_unpublished_button.html
> +<a class="button" href="/{{ url_name }}/{{ original.id }}{{ link_hash }}" target="_blank">{{ button_name }}</a>
Формируй ссылку в миксине!
```suggestion
<a class="button" href="{{ link }}" target="_blank">{{ button_name }}</a>
```

2022-05-12 11:40 UTC, AntonZelinsky commented on apps/core/mixins.py
> +            "url_name": string_url[self.model._meta.object_name],
Эти штуки в if|else делай, так будет проще читаться

2022-05-14 14:14 UTC, merged