update set_perms to journ,editor
Studio-Yandex-Practicum/Lubimovka_backend pull request #432
Opened 2022-05-05 09:00 UTC by Ghibliliker

https://www.notion.so/1d2122db365b42568da17ea6a58a05fe?p=f882b14fe8bd46c187d150b2d50c2e73

2022-05-06 18:37 UTC, Omnomus requested changes

2022-05-06 18:37 UTC, Omnomus commented on apps/core/management/commands/set_perms.py
>                  | Q(codename__endswith="_eventsblock")
это надо оставить, сейчас тестирую, этот пермишен блокирует добавление форматированного текста

можно еще удалить otherlink, Image

2022-05-08 10:52 UTC, Omnomus requested changes

2022-05-08 10:52 UTC, Omnomus commented on apps/core/management/commands/set_perms.py
>                  | Q(codename__endswith="_person")
У нас произошли изменения - убрали модель OtherPlay.  Поэтом этот пермишен не нужен, но должен быть пермишен на промежуточную модель AuthorPlay


Еще есть мысль, что редакторы не должны иметь право добавлять и удалять людей, только просмотр для добавления Автора. @AntonZelinsky что скажешь?

2022-05-08 10:52 UTC, Omnomus commented on apps/core/management/commands/set_perms.py
> -                | Q(codename__endswith="_contentunitrichtext")
Аналогично журналистам - это надо вернуть обратно.

2022-05-08 10:52 UTC, Omnomus commented on apps/core/management/commands/set_perms.py
> -                | Q(codename__endswith="_eventsblock")
тоже вернуть, он отвечает за добавление блока спектаклей

2022-05-08 10:52 UTC, Omnomus commented on apps/core/management/commands/set_perms.py
> -                | Q(codename__endswith="_projectcontent")
| Q(codename__endswith="_performancesblock") - вот это кажется не нужно. Но потестируй, плиз

2022-05-08 18:54 UTC, Omnomus commented on apps/core/management/commands/set_perms.py
> -                | Q(codename__endswith="_projectcontent")
а спектакли разве редактору не нужны?

2022-05-08 23:39 UTC, AntonZelinsky commented on apps/core/management/commands/set_perms.py
>                  | Q(codename__endswith="_person")
По идее должн иметь, ведь если редактор создаёт статью и хочет добавить фотографа, звукорежисёра и ещё кого-то, то ему прийдётся просить админов помочь написать статью. Сюда же относится и должности, их тоже нужно разрешить редактировать и создавать. В табличку нужно внести.

2022-05-09 09:38 UTC, Omnomus requested changes

2022-05-09 09:38 UTC, Omnomus commented on apps/core/management/commands/set_perms.py
>                  | Q(codename__endswith="_person")
@Ghibliliker  тогда тут еще и роли - role

2022-06-07 19:03 UTC, closed without merging