transfer models:MasterClass, Performance, Reading and all related com…
Studio-Yandex-Practicum/Lubimovka_backend pull request #450
Opened 2022-05-19 15:24 UTC by stepakiselev

…ponents from library app to afisha app

Тикет вашего PR (если есть):
    ___https://www.notion.so/93516fc6eed14ba7a1731dc999e6e7e4___

Нужно перенести то что касается афиши в приложение с событиями. 

Из Библиотеки перенести Спектакли, Мастер-классы, Читки в приложение Афиши.

2022-05-19 15:25 UTC, stepakiselev commented
При перемещение админ моделей из library в afisha пропал блок Афишы, пришлось полностью удалять базу и перезапускать контейнер (((

Можно было бы спокойно перетащить модели в другое приложение, но в моделях не было назначено имя таблиц. На всякий случай назначил.

2022-05-22 19:21 UTC, AntonZelinsky requested changes
Не буду дальше смотреть, исправление одного комента половину кода перефигачит

2022-05-22 19:21 UTC, AntonZelinsky commented on apps/afisha/models/events.py
> +from apps.afisha.models.reading import Reading
Импортируй все эти модели в файле apps/afisha/models/__init__.py и тут не нужно будет три разных импорта писать, будет один `from apps.afisha.models import MasterClass, Performance`.
Смотри как ты делал в файле apps/afisha/factories/__init__.py, то переменна __all не обязательна, кажется, всё будет работать и без неё.

2022-05-22 19:26 UTC, AntonZelinsky commented on apps/afisha/admin/__init__.py
> +__all__ = (
У нас всего 3 места в коде, где происходит импорт админ моделей. Предлагаю, во всех __init файлах делать только то, что нужно. Смысла тут импортировать все эти модели, а потом ещё и определять доступность только в `__all__` я не вижу. Просто отрегистрируй сайт и всё. 
Плюс, это относится ко всем остальным __инит файлам в админках.
![image](https://user-images.githubusercontent.com/1431279/169712504-2f3faaa0-fb18-4e23-bd6c-8f175865a91e.png)

2022-05-23 12:45 UTC, stepakiselev commented on apps/afisha/models/events.py
> +from apps.afisha.models.reading import Reading
))) я пытался но там конфликт при импорте возникал, попробую еще раз

2022-05-23 19:42 UTC, stepakiselev commented on apps/afisha/admin/__init__.py
> +__all__ = (
@AntonZelinsky, а как предпочтительнее делать? 
добавлять модель в `__init__` а после в каком либо файле импортировать например таким образом: `from apps.library.models import Play`
или сразу в файле вот так: `apps.library.models.play import Play` и без `__init__`

я так понял инит хорош если нужно импортировать много моделей и сразу в одном месте.

2022-05-23 21:33 UTC, AntonZelinsky commented on apps/afisha/admin/__init__.py
> +__all__ = (
Предпочтительнее первый вариант, но, админ модели мы нигде не импортируем, поэтому, тут оставить пустой файл `__init__ `и всё

2022-05-26 17:28 UTC, AntonZelinsky commented on apps/afisha/serializers/events.py
> +from apps.afisha.models.events import Event
Писал выше что поправить, чтобы объединить эти две строки

2022-05-26 17:28 UTC, AntonZelinsky commented on apps/afisha/views/events.py
> +from apps.afisha.serializers.events import AfishaEventSerializer
Та же история, добавь этот сериализатор в apps/afisha/serializers/__init__.py и не нужно будет тут ничего менять

2022-05-26 17:28 UTC, AntonZelinsky commented on apps/articles/factories/blog_items.py
> +from apps.afisha.models.events import Event
Пройди потом поиском по проекту на выражение `import Event` и посмотри, чтобы такого нигде больше не было. Писать больше про это не буду

2022-05-26 17:28 UTC, AntonZelinsky commented on apps/content_pages/factories/content_modules.py
> +from apps.content_pages.factories.content_units import ContentUnitRichTextFactory, LinkFactory
```suggestion
from apps.content_pages.factories import ContentUnitRichTextFactory, LinkFactory
```

2022-05-26 17:28 UTC, AntonZelinsky commented on apps/content_pages/models/content_blocks.py
> +from apps.content_pages.models.content_items import AbstractItemWithTitle
А вообще, пройди поиском по всему проекту на `models.` и если что-то будет находиться не в файле __init, то там скорее всего нужно будет поправить код.

2022-05-26 17:28 UTC, AntonZelinsky commented on apps/content_pages/models/content_blocks.py
> +from apps.content_pages.models.content_items import AbstractItemWithTitle
То же относится и к `serializers.content_items.`
И к `factories.`

2022-05-26 17:28 UTC, AntonZelinsky commented on apps/library/models/author.py
> +        "library.Play",
А тут можно класс передавать, как раньше было или теперь нужно обязательно строкой?

2022-05-26 17:28 UTC, AntonZelinsky commented on config/settings/base.py
> +        "Достижения",
УДали плиз эту строку. Ксюша в другом ПРе выпилила достижения и я боюсь, как бы не остался тут этот рудимент

2022-05-26 17:51 UTC, stepakiselev commented on apps/afisha/serializers/events.py
> +from apps.afisha.models.events import Event
никак не получается. возникает конфликт импорта ((( мне удалось его как то разрешить, но возникала ошибка в другом месте и я прыгал по коду как заяц. Давай еще раз попробую, а когда окажусь в тупике попрошу помощи у тебя

2022-05-26 17:53 UTC, stepakiselev commented on apps/library/models/author.py
> +        "library.Play",
так мне удалось избежать один из конфликтов

2022-05-26 17:58 UTC, AntonZelinsky commented on apps/afisha/serializers/events.py
> +from apps.afisha.models.events import Event
Окей, тогда не нужно, если это такое место. В следующей задаче вернёмся к этом месту и подумаем что можно сделать

2022-05-26 17:58 UTC, AntonZelinsky commented on apps/library/models/author.py
> +        "library.Play",
Окей, я понял, рекурсивные импорты получились. Хорошо, пусть будет так, подумаю после мержа, как их привести в порядок

2022-05-27 06:55 UTC, stepakiselev commented on apps/afisha/admin/reading.py
> +class ReadingAdmin(admin.ModelAdmin):
не уловил, где именно?

2022-05-27 06:57 UTC, stepakiselev commented on apps/afisha/serializers/events.py
> +from apps.afisha.models.events import Event
# isort:skip  выручил, спасибо. вы как обычно, легким движением разрешили проблему

2022-05-27 06:59 UTC, stepakiselev commented on apps/content_pages/factories/content_modules.py
> +from apps.content_pages.factories.content_units import ContentUnitRichTextFactory, LinkFactory
С этим моментом пока не разобрался, может смержить чтобы потом разобраться только с этим местом

2022-05-27 10:08 UTC, AntonZelinsky commented on apps/afisha/admin/reading.py
> +class ReadingAdmin(admin.ModelAdmin):
![image](https://user-images.githubusercontent.com/1431279/170679167-3184499a-0088-43f2-b186-0a1376f68de4.png)

2022-05-27 10:17 UTC, AntonZelinsky commented on apps/content_pages/factories/content_modules.py
> +from apps.content_pages.factories.content_units import ContentUnitRichTextFactory, LinkFactory
Тут возможно будет циклическая зависимость, можно оставить тут как есть. Он же внутри одной папки фабрики работает

2022-05-27 10:22 UTC, AntonZelinsky commented on apps/content_pages/models/__init__.py
> +# isort: split
Насколько я понимаю, [эта штука действует](https://pycqa.github.io/isort/docs/configuration/action_comments.html#isort-split) не на весь файл, а на то, что идёт после. А у тебя ничего после уже не идёт. 
Может из-за этого и были какие-то проблемы и нужно вернуть тот порядок который был раньше?

2022-05-27 10:27 UTC, stepakiselev commented on apps/afisha/admin/reading.py
> +class ReadingAdmin(admin.ModelAdmin):
ах ты ж блин, точно. это после мержа Ксюши, продублировалось. Сейчас поправлю

2022-05-27 10:32 UTC, AntonZelinsky approved these changes

2022-05-27 15:47 UTC, merged