add and change of related event is prohibited
Studio-Yandex-Practicum/Lubimovka_backend pull request #462
Opened 2022-05-30 10:29 UTC by Omnomus

Тикет вашего PR (если есть): [тикет](https://www.notion.so/Back-1d2122db365b42568da17ea6a58a05fe?p=19a5a418171647d9afa67ca53435e336)

Убрать возможность редактировать и создавать новое базовое событие на странице События.

2022-05-31 12:06 UTC, AntonZelinsky reviewed
Нет замены для карандаша. То есть, половина задачи не выполнена.

2022-05-31 12:06 UTC, AntonZelinsky commented on apps/afisha/static/admin/afisha/js/AfishaGetEvent.js
> +    hideAddButton($divDependedOnCommonEvent);
`let $divDependedOnCommonEvent = $(".depended_on_common_event");`
Тут что-то странное, в этой функции мы к объекту` $divDependedOnCommonEvent` добавляем в начале `#add_` и это всё превращается в строку? 
Окей, если ты говоришь что так работает, то пусть, не знал об этом. Я знал, что js слабая типизация, но чтобы настолько.. Вот хорошая [статья про типизации](https://habr.com/ru/post/161205/), на собесах легко могут спросить

2022-06-02 16:40 UTC, AntonZelinsky requested changes

2022-06-02 16:40 UTC, AntonZelinsky commented on apps/afisha/admin/events.py
> +        commonevent_id = int(re.search(r"\d+", path).group())
Тут точно нельзя другими способами достать переменную? Уж очень не нравится этот подход.
И разве в `object_id` будет лежать не нужная нам id?

2022-06-02 16:40 UTC, AntonZelinsky commented on apps/afisha/admin/events.py
> +                event_id = getattr(commonevent, event).id
Что-то совсем не нравится этот код! Попробуй переделать его
Мне кажется, если в функцию `type()` передать `target_model.target_model`, то в ответ придёт тип события, а этого достаточно для работы.

Раз уж затронешь работу свойства target_model, то нужно будет его немного проапгрейдить. Нужно добавить аннотацию возвращаемых типов, потом, вместо возвращения None, бросать исключение типа неподдерживаемого функционала.

2022-06-02 16:40 UTC, AntonZelinsky commented on apps/afisha/admin/events.py
> +        return redirect(to=f"{url}?{urlencode(query_string)}")
Параметры лучше задавать так `return redirect('product_detail', product_id=product_id)`

2022-06-02 19:26 UTC, Omnomus commented on apps/afisha/admin/events.py
> +        commonevent_id = int(re.search(r"\d+", path).group())
я, видимо, не ищу легких путей))))))

2022-06-02 19:26 UTC, Omnomus commented on apps/afisha/admin/events.py
> +                event_id = getattr(commonevent, event).id
можешь подробнее описать? я не поняла твою идею и не нагуглила про таргет

2022-06-02 19:26 UTC, Omnomus commented on apps/afisha/admin/events.py
> +        return redirect(to=f"{url}?{urlencode(query_string)}")
что-то так не работает, параметры не передаются

2022-06-02 19:50 UTC, AntonZelinsky commented on apps/afisha/admin/events.py
> +                event_id = getattr(commonevent, event).id
Опечатку сделал..
Что возвращает выполнение этого кода `type(commonevent.target_model)`?

2022-06-03 10:48 UTC, Omnomus commented on apps/afisha/admin/events.py
> +        return redirect(to=f"{url}?{urlencode(query_string)}")
return redirect(url, _to_field="id", _popup="1") => так аргументы просто не передаются, открывается Reading/4/change с боковой левой панелью админки
return redirect(url, query_string) аналогично

2022-06-03 11:54 UTC, AntonZelinsky approved these changes

2022-06-03 11:54 UTC, merged