creator field for BlogItem, NewsItem, Project and Perfomance + filtering
Studio-Yandex-Practicum/Lubimovka_backend pull request #474
Opened 2022-06-03 07:37 UTC by baby-platom

Тикет вашего PR (если есть):
    [___ваш тикет___](https://www.notion.so/afb0b3f784ff4abb9cd6e1ec752102d7)

Когда создаёте PR, убедитесь, что:

- [ ] вы проверили обновления в [брифе](https://www.notion.so/00f5d5a6d39e426fa1ea7ab69b694f07)
- [ ] синхронизировали изменения кода с [ER-диаграммой базы данных](https://drive.google.com/file/d/1RCIPaEgaLUSqek3znd38VPCKSzOlmJFy/view) связей моделей
- [ ] убедились, что модель OpenAPI проверена (в Swagger отображаются изменения)
- [ ] тесты все пройдены и нет конфликтов
- [ ] созданы необходимые миграции

Когда ваш PR смержен:

- [ ] если у вас были изменения в API, сообщите об этом команде Фронта, им это важно знать!

2022-06-03 11:07 UTC, AntonZelinsky requested changes

2022-06-03 16:52 UTC, baby-platom commented on apps/content_pages/filters.py
> +            ("me_author", _("Я автор")),
По дефолту все записи, в `def queryset` можешь видеть условие

2022-06-03 19:15 UTC, FinemechanicPub commented on requirements/prod.txt
> +sqlparse==0.4.2; python_version >= "3.8"
Интересно, что Poetry не дает установить окружение, если версия Питона меньше 3.9 Где-то эта зависимость уже прописана.

2022-06-04 03:59 UTC, baby-platom commented on apps/content_pages/models/contents.py
> +    creator = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Создатель", blank=True, null=True)
те самые дата миграции подошли)

2022-06-05 23:38 UTC, AntonZelinsky commented on requirements/prod.txt
> +sqlparse==0.4.2; python_version >= "3.8"
Странно, в файлах зависимости нет ни одной зависимости от 3.9. Ты на 3.8 не смог поставить? Я думаю, что у меня стоит 3.7 или 3.8, хотя стоит ещё и 3.10, но проект точно не на нём развёрнут

2022-06-05 23:45 UTC, AntonZelinsky commented on apps/content_pages/filters.py
> +            ("me_author", _("Я автор")),
Покажи тут пожалуйста скрин страницы списка, как только ты её открываешь

2022-06-06 09:30 UTC, FinemechanicPub commented on requirements/prod.txt
> +sqlparse==0.4.2; python_version >= "3.8"
@AntonZelinsky Нет, со стандартным в Ubuntu Python 3.8 отказывается работать. Поставил отдельно Python 3.9 и Poetry сама его выбирает при включении окружения командой shell. Возможно, ещё зависит от версии Poetry. Я сначала поставил по инструкции с этой страницы https://python-poetry.org/docs/#installation, она не ругалась на Питон, но у меня что-то не получилось при разворачивании проекта. Потом я взял инструкцию с другой страницы https://python-poetry.org/docs/master/#installation и эта Poetry уже говорит, что проект требует Питон 3.9. Вообще не очень понятно существование двух инструкций по установке на одном сайте.

2022-06-06 09:57 UTC, nkiryanov commented on requirements/prod.txt
> +sqlparse==0.4.2; python_version >= "3.8"
Друзья, думал сами найдете, но что-то нет.

Подсказываю: управление зависимостями занимается poetry и она генерит итоговый requirements.
У poetry четко указана зависимость версии python. Это в pyproject.toml лежит.

Сам requirements который получается на выходе не смотрел, но думаю там будет явно указано какая версия python нужна и будет 3.9

2022-06-07 18:55 UTC, AntonZelinsky commented on apps/content_pages/mixins.py
> +            return f"{obj.creator.first_name} {obj.creator.last_name}"
Мы же сейчас делаем так, что создатель будет всегда, нет варианта, что его не будет, так что, эти ифы никому не нужны будут.

2022-06-07 18:55 UTC, AntonZelinsky commented on apps/articles/admin/blog_items.py
> +        "creator_name",
Но тут же, и в двух других моделях, не подключается миксин с эти свойством, как оно работает?

2022-06-08 05:52 UTC, baby-platom commented on apps/articles/admin/blog_items.py
> +        "creator_name",
во всех их админ-классах используется BaseContentPageAdmin, а он в свою очередь теперь использует миксин. Тут такая же история как с базовой моделью распространяющейся на все три модели)

2022-06-08 06:12 UTC, baby-platom commented
Блин на факторис тесты падают( Я сейчас буду в отъезде сутки, завтра смогу поправить, хотя в факторис и не силен, вероятно там легко исправить

2022-06-19 19:44 UTC, AntonZelinsky approved these changes
Всё окей, можешь исправить эти мелочи, можешь не испрвлять, это скорее для тебя фидбек

2022-06-19 19:44 UTC, AntonZelinsky commented on apps/afisha/factories/performance.py
> +    user = User.objects.first()
Тут лучше не первого брать, а рандомного

2022-06-19 19:44 UTC, AntonZelinsky commented on apps/articles/migrations/0009_load_creators.py
> +    load_using_model_name("Project")
Можно было передавать модель напрямую, минус одна строка в функции, но и так тоже норм
```suggestion
    load_using_model_name(Project)
```

2022-06-20 04:42 UTC, baby-platom commented on apps/articles/migrations/0009_load_creators.py
> +    load_using_model_name("Project")
![image](https://user-images.githubusercontent.com/82268688/174526747-c37316b0-d751-4dda-ba06-58e4ec1064ac.png)

2022-06-20 05:06 UTC, merged