Feature/markdown for pages
Studio-Yandex-Practicum/Lubimovka_backend pull request #52
Opened 2021-10-31 21:28 UTC by KonstantinRaikhert

Создано новое приложение static_pages, которое включает в себя модель для хранения данных со статических страниц.
Добавлены ендпоинты:
api/v1/info/about-festival/what-we-do/
api/v1/info/about-festival/ideology/

2021-11-01 21:34 UTC, kr0t commented on apps/static_pages/models.py
> +            "https://ru.wikipedia.org/wiki/Markdown",
Я бы тут лучше указал ссылку на более информативный гайд, например [этот](https://www.markdownguide.org/basic-syntax/). Но это думаю не критично.

2021-11-01 21:34 UTC, kr0t commented on apps/static_pages/models.py
> +            Для того, чтобы загурзить картинку, перетащите её в поле.
опечатка

2021-11-01 21:38 UTC, AntonZelinsky reviewed
Всё хорошо, хорошее решение, выглядит красиво. Но нужно сделать пару правок)

2021-11-01 21:38 UTC, AntonZelinsky commented on config/urls.py
> +    url(r"^markdownx/", include("markdownx.urls")),
Не очень нравится этот роут. Получается, он внутренний, для админки, а мы его почему-то выставляем наружу (хотя, может в свагере он и не будет видет).
По хорошему, попробовать переопределить этот роут и включить в часть админки, как я понял, для этого есть свойство `MARKDOWNX_URLS_PATH`

2021-11-01 21:38 UTC, AntonZelinsky commented on config/settings/base.py
> +MARKDOWNX_IMAGE_MAX_SIZE = {"size": (1000, 1000), "quality": 90}
А почему качество 90?

2021-11-01 21:38 UTC, AntonZelinsky commented on apps/static_pages/serializers/static_pages.py
> +class StaticPagesSerializer(serializers.ModelSerializer):
Если от нас запрашивают страницу «Что мы делаем», то нет смысла присылать page_type с дублированием запроса.

2021-11-01 21:38 UTC, AntonZelinsky commented on apps/static_pages/admin.py
> +class MyModelAdmin(admin.ModelAdmin):
MyModelAdmin???

2021-11-01 21:38 UTC, AntonZelinsky commented on apps/static_pages/models.py
> +    page_type = models.CharField(
Не очень нравится это название. По идее, это просто ключ.

2021-11-01 21:38 UTC, AntonZelinsky commented on apps/static_pages/models.py
> +    page_type = models.CharField(
![image](https://user-images.githubusercontent.com/1431279/139744967-97dd6536-84dd-4d4b-b3ef-bc9f6d1823fa.png)
Кажется, что тут можно изменить что-то и всё сломается.
Не очень нравится идея с чузами. Я думаю, можно их в стандартной миграции добавить эти посты. Только ключ использовать такой как сейчас, а значение — это будет просто описание для пользователя. И наверно запретить удалять записи.

Что думаете?

2021-11-01 21:38 UTC, AntonZelinsky commented on apps/static_pages/apps.py
> +class StaticPagesConfig(AppConfig):
Думаю, что можно было и в инфо или в кор поместить, но это авторское решение)

2021-11-01 21:43 UTC, kr0t commented on apps/static_pages/admin.py
> +class MyModelAdmin(admin.ModelAdmin):
Думаю стоит изменить название по аналогии с классом модели

2021-11-01 21:51 UTC, kr0t requested changes
Надо поправить название класса в admin.py

2021-11-02 19:19 UTC, KonstantinRaikhert commented on config/urls.py
> +    url(r"^markdownx/", include("markdownx.urls")),
Нет. 
MARKDOWNX_URLS_PATH
Default: '/markdownx/markdownify/' - меняет этот дефолтный путь и потом приложение отправляет POST на этот адрес, но если его не зарегистрировать, то магии не будет...

В общем-то в свагере не отображается это url.
Можно красивее написать чтоб не выбивалось:
```
 path("markdownx/", include("markdownx.urls"))
```

2021-11-02 19:20 UTC, KonstantinRaikhert commented on config/settings/base.py
> +MARKDOWNX_IMAGE_MAX_SIZE = {"size": (1000, 1000), "quality": 90}
качество оставил по дефолту. а размер решил увеличить
```
Default: { 'size': (500, 500), 'quality': 90 }
```

2021-11-02 19:25 UTC, nkiryanov commented on config/urls.py
> +    url(r"^markdownx/", include("markdownx.urls")),
Тут идея в том, что убрать его куда-то в `hostname/admin/something/markdown/....`
Так будет как бы по красоте — относится к админке и в админку уберём.

2021-11-02 19:26 UTC, KonstantinRaikhert commented on config/urls.py
> +    url(r"^markdownx/", include("markdownx.urls")),
MARKDOWNX_URLS_PATH =  '/admin/markdownx/markdownify/
Норм?)

2021-11-02 19:29 UTC, KonstantinRaikhert commented on config/urls.py
> +    url(r"^markdownx/", include("markdownx.urls")),
ну да. а так не работает.. короче голову поломать придётся

2021-11-02 19:36 UTC, KonstantinRaikhert commented on config/urls.py
> +    url(r"^markdownx/", include("markdownx.urls")),
```
urlpatterns = [
    path(
        route="admin/markdownx/",
        view=include("markdownx.urls"),
    ),
    path(
        route="admin/",
        view=admin.site.urls,
    ),
    path(
        route="api/",
        view=include(apps_patterns),
    ),
    path(
        route="api/schema/",
        view=include(api_schema_patterns),
    ),
```

2021-11-02 19:45 UTC, nkiryanov requested changes
На удивление всё просто выглядит.

Из существенных моментов только unique_constraint который вроде не нужен. Всё остальное пожелание/дополнение комментариев ребят раньше.

2021-11-02 19:45 UTC, nkiryanov commented on apps/info/urls.py
>          "what-we-do/",
С точки зрения кода тут всё ок, но почему-то такой эндопонинт не нравится внутреннему перфикционисту. Только мне так?

Сам бы назвал `about`. Но наверное поздно и фронт тоже ожидает what-we-do из figma?

2021-11-02 19:45 UTC, nkiryanov commented on apps/static_pages/admin.py
> +class MyModelAdmin(admin.ModelAdmin):
Соглашусь с предыдущему ораторами :)
А ещё тут есть переопределение виджета текстового поля на Markdown и в таком случае для не помешает докстринг для класса.

2021-11-02 19:45 UTC, nkiryanov commented on apps/static_pages/models.py
> +    page_type = models.CharField(
1. Я может что не понял, но `page_type` мне нравится
2. Предлагаешь сделать не Choise, а связать с ещё с одной таблицей типов? М? Или поле обозначить как editable = False (чтоб в админке не показывалась)?

2021-11-02 19:45 UTC, nkiryanov commented on apps/static_pages/models.py
> +                fields=("page_type",),
Уникальность для одного поля задается в самом полe `unique=True` и это всё не нужно
вроде так.

2021-11-02 19:45 UTC, nkiryanov commented on apps/static_pages/serializers/static_pages.py
> +class StaticPagesSerializer(serializers.ModelSerializer):
соглашусь, ага

2021-11-02 19:48 UTC, KonstantinRaikhert commented on apps/static_pages/models.py
> +    page_type = models.CharField(
Я понял, что завести просто ключ и титл. Ключ нигде не отображать. А титл только при выборе в админке (внутри не отображать)

2021-11-02 19:50 UTC, KonstantinRaikhert commented on apps/info/urls.py
>          "what-we-do/",
ну в фигме так...

2021-11-02 20:29 UTC, AntonZelinsky commented on config/settings/base.py
> +MARKDOWNX_IMAGE_MAX_SIZE = {"size": (1000, 1000), "quality": 90}
Не знаю практик на эту тему, но мне кажется, не очень хорошо урезать качество.
А то будет, как у инстаграма, загружаешь фотографию, а он 30% качества срезает, а если сторис, то все 60%.
Мне кажется, пусть пользователи сами уменьшают качество, если хотят.

2021-11-02 20:31 UTC, AntonZelinsky commented on apps/static_pages/models.py
> +    page_type = models.CharField(
Только выборе чего? Когда из списка выбирается статическая страница?

2021-11-02 20:35 UTC, AntonZelinsky commented on apps/info/urls.py
>          "what-we-do/",
Коля, урл тогда получится `about-festival/about`.
Вообще, можно сделать `path("",` и тогда данные будут приходить на запрос  `about-festival`

2021-11-02 20:40 UTC, AntonZelinsky commented on apps/static_pages/serializers/static_pages.py
> +class StaticPagesSerializer(serializers.ModelSerializer):
Вообще, если у тебя один сериализатор, то нет смысла делать папку и помещать его сюда, это только усложняет понимание. Можно было просто в файл сераилизаторс его поместить. 
Даже когда несколько файлов, так делают, когда их становится слишком много или когда они из слишком разных тем.

2021-11-02 20:41 UTC, KonstantinRaikhert commented on apps/static_pages/models.py
> +    page_type = models.CharField(
Нет. Заходим в админку. выбираем страницы. Отображаются 3 страницы (3 обьекта). Нажимаем на любой и редактируем. В редактируемом шаблоне только data

2021-11-02 20:42 UTC, AntonZelinsky commented on apps/static_pages/models.py
> +    page_type = models.CharField(
Ой, а можешь записать видео пример?)

2021-11-02 21:13 UTC, KonstantinRaikhert commented on apps/static_pages/models.py
> +    page_type = models.CharField(
записал, скинул телеграм

2021-11-02 21:18 UTC, KonstantinRaikhert commented on config/settings/base.py
> +MARKDOWNX_IMAGE_MAX_SIZE = {"size": (1000, 1000), "quality": 90}
максималка по их документации это 100, а размер.

2021-11-02 23:31 UTC, KonstantinRaikhert commented
Пока не придумал как лучше с миграциями быть. Зашивать данные страниц. Но думаю пока можно смерджить, если нет замечаний.

2021-11-03 18:40 UTC, merged

2021-11-03 18:41 UTC, nkiryanov approved these changes
Просмотрел. Замечаний нет, класс!
Здорово, что продумал и добавил в API странички.

👍

2021-11-04 14:36 UTC, kr0t reviewed
Круто!