Bugfix/question fix email
Studio-Yandex-Practicum/Lubimovka_backend pull request #53
Opened 2021-11-01 13:27 UTC by AnnaKPolyakova

Fix send_question (add settings)

2021-11-02 12:48 UTC, AntonZelinsky commented on apps/info/utils.py
> +        Settings.get_setting("Subject_in_email"),
А от кого отправляется это письмо? Где это задаётся?

2021-11-02 12:48 UTC, AntonZelinsky commented on apps/info/utils.py
> +        Settings.get_setting("Subject_in_email"),
Название функции `get_setting` конечно не очень хорошее, потому что по стандартам именования django, подразумевается, что вернётся объект сетинга. Тут `get `или даже `get_value `будет намного лучше

2021-11-02 12:48 UTC, AntonZelinsky commented on apps/core/migrations/0006_create_settings_objects.py
> +        text="lubimovka",
Эта миграция, уже конечно не накатится на базу, может ручками добавить? Или сделать ещё одну миграцию, только там не называть её как дата, а пускать как обычную, а потом, когда всё будет схлопываться, тут останется одна актуальная дата миграция, а остальные просто удалятся?
Правда в тех миграциях нужно будет делать запрос в базу и проверять, нет ли такой уже записи.
В общем, нужно подумать.

2021-11-02 12:48 UTC, AntonZelinsky commented on apps/core/migrations/0006_create_settings_objects.py
> +        text="lubimovka",
Заголовок письма не очень. Уж лучше просто `Любимовка`, хотя, если это письмо с вопросом читателя, то можно уже более конкретный заголовок дать

2021-11-02 12:55 UTC, AnnaKPolyakova commented on apps/info/utils.py
> +        Settings.get_setting("Subject_in_email"),
Задается в переменных окружения Создайте переменные окружения:
EMAIL_HOST=
EMAIL_PORT=
EMAIL_HOST_USER=
EMAIL_HOST_PASSWORD=

2021-11-02 12:57 UTC, AnnaKPolyakova commented on apps/core/migrations/0006_create_settings_objects.py
> +        text="lubimovka",
Думаю, что с миграциями лучше так, и тут оставить и новую создать, только в новой сделать get_or_create

2021-11-02 13:22 UTC, AnnaKPolyakova commented on apps/core/migrations/0006_create_settings_objects.py
> +        text="lubimovka",
Про заголовок, а что там конкретнее такое можно задать? Типа "Вопрос Любимовке от {вставить тут почту от кого вопрос}? А нужно ли отдельную настройку создавать для этого? Можно и захардкодить...

2021-11-02 19:14 UTC, AntonZelinsky commented on apps/core/migrations/0006_create_settings_objects.py
> +        text="lubimovka",
Лучше всё же свойство настраиваемым оставить. Пусть будет «Вопрос Любимовке». Они посмотрят и если что, то попросят подредактировать.

2021-11-02 19:15 UTC, AntonZelinsky commented on apps/info/utils.py
> +        Settings.get_setting("Subject_in_email"),
Ну ладно, пусть там пока и остаётся. Чтобы мы не делали то, что воможо потом и не понадобится.

2021-11-02 19:18 UTC, AntonZelinsky commented on apps/core/migrations/0006_create_settings_objects.py
> +        text="lubimovka",
Только давай всё сделаем с маленькой или большой буквы. По хорошему, при сохранении нужно приводить к такому виду. Ведь, `Subject_in_email `и `subject_in_email `разные значения.

2021-11-02 19:55 UTC, nkiryanov requested changes
Ань, а что было в этом PR?
правильно понимаю что добавила настройки темы письма?

Можешь, пожалуйста, так явно и писать. Например мне нужно было всесь PR просмотреть, что понять что происходит.

Из значительных комментариев — перевести бы настройки в строчные символы все.

2021-11-02 19:55 UTC, nkiryanov commented on apps/core/migrations/0006_create_settings_objects.py
> +        settings_key="Subject_in_email",
Слушайте, а меня одного смущает, что у имя ключа начинается с большой буквы?
Так как это системное поле, настойчиво рекомендую придерживаться `snake_case` и писать с строчной. Точно не ошибемся.

Кто что скажет?

2021-11-02 19:55 UTC, nkiryanov commented on apps/core/migrations/0006_create_settings_objects.py
> +        text="lubimovka",
О! Думаем одинаково :) (про большую/маленькую букву)

2021-11-02 19:55 UTC, nkiryanov commented on apps/core/migrations/0006_create_settings_objects.py
> +        settings_key="Subject_in_email",
И тогда бы назвал ключ "email_subject".
Но у нас только одно письмо будет только с одной темой? Тогда так подойдёт. Или можно предположить, что у нас только одна тема будет, а будет нужно больше сделаем позже.

но "email_subject" нравится больше.

2021-11-02 20:24 UTC, AntonZelinsky commented on apps/core/migrations/0006_create_settings_objects.py
> +        settings_key="Subject_in_email",
Скорее всего больше писем. Просто пока не понятно какие.
Как минимум, письма приглашения пользователя и сброса пароля. Может какие-то системные уведомления о ошибке.

2021-11-03 21:04 UTC, nkiryanov approved these changes
Ну не шампанского, но пивка можно 👍

2021-11-03 21:04 UTC, nkiryanov commented on apps/info/utils.py
> +        Settings.get_setting("email_subject_for_question"),
👍

2021-11-03 21:05 UTC, merged