Bugfix/authors
Studio-Yandex-Practicum/Lubimovka_backend pull request #55
Opened 2021-11-03 21:49 UTC by evi1ghost

Дополнил докстринг в фабрике Автора.
Заменил поля plays и achievements в модели Автора на инлайны. Теперь пользоваться удобнее.

2021-11-03 22:02 UTC, DRAGANmik approved these changes

2021-11-03 22:02 UTC, nkiryanov requested changes
Вроде verbose имена не нужны для инлайнов.

2021-11-03 22:02 UTC, nkiryanov commented on apps/library/tests/factories.py
> +        You should create at least one Festival and Program
👍 

Вообще думаю ща, что эту проверку можно в `__init__` проверять с помощью `assert`.
Но сам так не делал и не знаю точно ли получится. На подумать в общем.

2021-11-03 22:50 UTC, evi1ghost commented on apps/library/tests/factories.py
> +        You should create at least one Festival and Program
О! Супер!
Покапался чуть-чуть. Проверку через `assert` сделать можно, но не в `__init__`, а вставив ее в `create`, т.к. `create` является методом класса и не использует `__init__`.
Сейчас проверок натыкаю ^___^

2021-11-04 01:33 UTC, evi1ghost commented on apps/library/admin.py
> +    verbose_name = "Достижение"
Видимо из-за того, что инлайн через through подключается, verbose_name из модели не подтягивается.

2021-11-04 01:34 UTC, evi1ghost commented on apps/library/tests/factories.py
> +        You should create at least one Festival and Program
Тебя за язык никто не тянул, теперь придется декоратор ревьюить :)

2021-11-04 23:32 UTC, nkiryanov approved these changes
Апрувну, чтоб не затягивать.

Ошибки у фабрик стали точно более информативные.
Но переопределять методы в каждой из фарик жестковато + код становится сложнее.

Хочется какого-то более простого/или изящного способа. Но сходу не могу придумать как это сделать.

2021-11-04 23:32 UTC, nkiryanov commented on apps/library/tests/utilities/decorators.py
> +            base_error_msg_ending = f"{method.__qualname__}()"
Это окончание сообщения об ошибке, но большой ценности это не несет.

Код об ошибке вида

 `error = f"{error_title_msf}, {base_error_msg_ending}"`

не особо понятен. Ну прочитали мы что есть какое-то начало, какой-то конец ошибки. А что в этом начале и конце?

Гораздо информативнее:

```
classmethod_name = f"{method.__qualname__}"
error_msg = (
         f"You should create at least one {required_instances} "
         f"before use {classmethod_name}"
     )

```

Будет сразу понятнее.

2021-11-04 23:32 UTC, nkiryanov commented on apps/library/tests/utilities/decorators.py
> +                check_restriction(checks.pop("global"), base_error_msg_ending)
Вычисление в функции тяжело для понимания. Лучше добавить +1 строчку

```python
if "global" in checks:
    models_list = checks.pop("global")
    check_restriction(models_list, base_error_msg_ending)
```

2021-11-04 23:32 UTC, nkiryanov commented on apps/library/tests/utilities/decorators.py
> +            for arg, models in checks.items():
Понятнее будет пройти по каждому kwarg-у и сверить его наличие в словаре исключений.
Тогда не потребуется 
```python
if not is_arg:
    continue
```

Что-то типа такого, но пишу но нужно посмотреть и может и globals сюда добавить или ещё как улучшить можно.
```python
method_keyword_variables = kwargs
for keyword_variable in method_keyword_variables:
    if keyword_variable in checks:
        models = checks[keyword_variable]
        check_restriction(models, keyword_variable)
```
(а keyword_variable передводил бы в ошибку уже в check_restriction)

2021-11-04 23:32 UTC, nkiryanov commented on apps/library/tests/factories.py
> +        You should create at least one Festival and Program
Отрвеьювил :)
Класс. Правда страшно немного, что кто-то со стороны скажет что с одной стороны делаем проверки и ошибки проще, а с другой появляется не очень очевидный декоратор. Короче подождём кто ещё поревьювит :)

2021-11-05 20:54 UTC, nkiryanov approved these changes
Написал ещё свои мысли, но меня немного беспокоит, что всё делаю какие-то правки. 

Желание что-то менять есть? С мыслями согласен?
Может быть подключить ещё кого-то и если всё понятно, то оставить без изменений?

2021-11-05 20:54 UTC, nkiryanov commented on apps/library/tests/utilities/decorators.py
> +def restrict_factory(restrictions: dict[str, list[Any]]):
Прямо круто получилось!
👍

2021-11-05 20:54 UTC, nkiryanov commented on apps/library/tests/utilities/decorators.py
> +        restrictions.update({"_factory_name": klass.__name__})
Думаю удобнее не обновлять словарь с ограничениями, а добавить новую переменную (имя класса) и передавать её в декоратор `restrict_factory_method` отдельно.

Т.е `restrict_factory_method(restrictions, factory_name)`

Что ещё думаю: у нас тут получилось 2 вложенных декоратора и это сложно для понимания.
Может быть ограничиться одним декоратором класса и код из `restrict_factory` вставить в расширение метода create? Как думаешь?

2021-11-05 21:27 UTC, nkiryanov approved these changes
Думаю с правками покончено 👍

2021-11-05 21:27 UTC, nkiryanov commented on apps/core/decorators/factory.py
>              def create(cls, **kwargs):
👍

2021-11-05 21:29 UTC, kr0t approved these changes
Мне нравится.

2021-11-05 21:29 UTC, kr0t commented on apps/core/decorators/factory.py
> +def restrict_factory(restrictions: dict[str, list[Any]]):
🔥

2021-11-05 21:30 UTC, merged