Feature/add festival api
Studio-Yandex-Practicum/Lubimovka_backend pull request #56
Opened 2021-11-03 22:16 UTC by AnnaKPolyakova

add api for festival
add test for api festival

2021-11-03 22:35 UTC, nkiryanov approved these changes
Из существенных вопрос про паджинацию.

То, что появились тесты класс 👍

2021-11-03 22:35 UTC, nkiryanov commented on apps/info/serializers/__init__.py
> +    "FestivalSerializer",
Мы везде на кортежи переезжаем, можно тут список на кортеж заменить если уж что-то редактируем

2021-11-03 22:35 UTC, nkiryanov commented on apps/info/views/festival.py
> +class FestivalViewSet(ListAPIView):
А почему паджинацию выключаем? Вроде нужна

2021-11-03 22:35 UTC, nkiryanov commented on apps/info/tests/test_urls.py
> +def festival():
Класс! Если что у нас есть factories и создание тестовых данных может быть чуть проще.

2021-11-03 22:36 UTC, nkiryanov requested changes
Из существенных вопрос про паджинацию.

То, что появились тесты класс 👍

2021-11-05 15:18 UTC, AnnaKPolyakova commented on apps/info/views/festival.py
> +class FestivalViewSet(ListAPIView):
![31110249-28CA-4B9F-919C-799F1308805B](https://user-images.githubusercontent.com/72471286/140533659-17988158-dd5b-466f-9bdb-64d78c86b6d4.png)
Не оч понятно, а по сколько фестивалей тогда надо выдавать? На картинке 6,5 видно). Я думала, что их все сразу выдавать надо. Вероятно там можно будет как бы прокрутить все возможные года и выбрать

2021-11-05 21:31 UTC, AntonZelinsky commented on apps/info/views/festival.py
> +class FestivalViewSet(ListAPIView):
На каждый фестиваль делается отдельный запрос. Список всех фестивалей возвращать просто нужно. Наверно, в каждом запросе это стоит делать. 
Пагинаций я не знаю где тут можно применить

2021-11-05 21:34 UTC, nkiryanov commented on apps/info/views/festival.py
> +class FestivalViewSet(ListAPIView):
Согласен, чот я видать тупенький и срзау не сообразил.
Пожалуй тогда нужно сделать простенький совсем сериализатор фестивалей (чтоб был их список, с годами), а по конкретному фестивалю отдавать полную информацию

В общем то, что в ща в проектах/новостях и тд.

Паджинация и правда не потребуется.

2021-11-06 09:16 UTC, AnnaKPolyakova commented on apps/info/views/festival.py
> +class FestivalViewSet(ListAPIView):
Если честно, то не очень поняла, зачем делать несколько запросов вместо 1? В любом случае мы будем делать сначала запрос на список всех фестивалей, потом сразу надо будет делать еще один запрос на данные по последнему фестивалю (о том какой это фестиваль мы узнаем их списка фестивалей), то есть уже 2 запроса, если пользователь захочет походить по другим годам, то это каждый раз новый запрос. Может оставить как есть?

2021-11-06 09:19 UTC, AnnaKPolyakova commented on apps/info/views/festival.py
> +class FestivalViewSet(ListAPIView):
Можно, конечно, сделать 1 отдельный метод на получение списка фестивалей (например "festival_list") и отдельно метод, который выдает данные фестиваля по году...

2021-11-06 09:21 UTC, AnnaKPolyakova commented on apps/info/views/festival.py
> +class FestivalViewSet(ListAPIView):
Можно этот метод дописать так, что когда не выставлен фильтр на год, то возвращается список фестивалей, но в нем данные только по годам (переопределить get_serializer_class)

2021-11-06 10:06 UTC, nkiryanov commented on apps/info/views/festival.py
> +class FestivalViewSet(ListAPIView):
>Можно, конечно, сделать 1 отдельный метод на получение списка фестивалей (например "festival_list") и отдельно метод, который выдает данные фестиваля по году...

и 

>Если честно, то не очень поняла, зачем делать несколько запросов вместо 1? В любом случае мы тогда будем делать сначала запрос на список всех фестивалей, потом сразу надо будет делать еще один запрос на данные по последнему фестивалю (о том какой это фестиваль мы узнаем их списка фестивалей), то есть уже 2 запроса, если пользователь захочет походить по другим годам, то это каждый раз новый запрос. Может оставить как есть?

Да, в общем потребуется сделать 2 запроса, ничего страшного.
Придерживаясь логики вернуть всё сразу для всего — можно провести аналогию с рецептами/постами в наших учебных проектах. Там ведь тоже есть одни данные в списке, а подробные отдаются по конкретному объекту.

В целом можно сделать и отдельный метод для получения списка фестивалей, но зачем?

2021-11-06 10:17 UTC, nkiryanov requested changes
Прокомментировал.

2021-11-06 10:17 UTC, nkiryanov commented on apps/info/serializers/__init__.py
> +    "FestivalSerializer",
Актуально.

2021-11-06 10:17 UTC, nkiryanov commented on apps/info/views/festival.py
> +        if len(self.request.query_params) == 0:
Вот это не очень понятная логика. Думаю, мы такой всех запутаем и главное не вижу в ней необходимости.

Почему бы не возвращать FestivalListSerializer когда нужно показать список, а FestivalSerializer когда нужно отдать конкретный объект?

2021-11-06 10:17 UTC, nkiryanov commented on apps/info/tests/test_urls.py
> +            "возвращаются данные объекта. Значение year неправильное"
Чот не понял этот тест. Если точнее, что значит "Значение year неправильное"?

2021-11-06 14:18 UTC, nkiryanov requested changes
Отревьювил. Становится лучше, но есть что улучшить :)

**И ещё давай менять списки на кортежи (там где что-то с кодом делаем)**

2021-11-06 14:18 UTC, nkiryanov commented on apps/info/urls.py
>      path(
Всё ок, но фестивали тоже давай отдавать в множественном числе. Это соглашение такое. Их же много фестивалей.

Т.е. /festivals/2020, /festivals/years

2021-11-06 14:18 UTC, nkiryanov commented on apps/info/views/festival.py
> +    data = list(festival.year for festival in Festival.objects.all())
Получить спиоск "лет" лучше сразу из БД. Так будет быстрее и даже понянее.
Нужно использовать `.values()` или даже `.values_list(flat=True)`. [Тут](https://docs.djangoproject.com/en/3.2/ref/models/querysets/#values) подробнее

2021-11-06 14:18 UTC, nkiryanov commented on apps/info/views/festival.py
> +class FestivalViewSet(RetrieveAPIView, ListAPIView):
Тогда здесь ListApiView не нужен вообще? Если мы список годов возвращаем в отдельной вьюхе?

2021-11-07 14:06 UTC, nkiryanov approved these changes
Апрувлю. Есть момент который можно изменить, но не критично.

Смерджишь?

2021-11-07 14:06 UTC, nkiryanov commented on apps/info/views/festival.py
> +    data = list(
Можно чуть проще (сразу получать только список лет и проще в список перевести)

```python
years_data = list(Festival.objects.values_list("year", flat=True))
return JsonResponse({"years": years_data}, status=status.HTTP_200_OK)
```

Но в целом можно и не менять и мерджить как есть.

2021-11-07 14:06 UTC, nkiryanov commented on apps/info/views/__init__.py
> +__all__ = (
Ура!

2021-11-07 14:06 UTC, nkiryanov commented on apps/info/tests/test_urls.py
> +    def test_get_festival_detail(self, client, festival):
Обожаю тесты 👍

2021-11-07 14:16 UTC, merged