Bugfix/error in status button mixin
Studio-Yandex-Practicum/Lubimovka_backend pull request #582
Opened 2022-08-04 13:37 UTC by stepakiselev

Тикет вашего PR (если есть):
    ___[ваш тикет](https://www.notion.so/edb698620366460ba33d153c92162f75)___

была маленькая ошибка в слове "performance", поправил.

Добавил ограничение на блоги/новости/проекты теперь нельзя опубликовать блог/новость/проект если в блоке конструктора задествоан блок с пьесами, у которых статус "не опубликовано". Не уверен что такое ограничение нужно.

2022-08-05 10:28 UTC, Omnomus commented on apps/core/utils.py
> +        return f"Статус {articles[name]} не обновлён. В блоке/элемент (блок пьес) пьесы должна быть опубликованы!"
Что-то не очень понятное сообщение) Может просто "...В блоке пьес все Пьесы должны быть опубликованы!"?

2022-08-05 10:28 UTC, Omnomus commented on apps/core/utils.py
> +def check_status_plays(obj, name):
лучше check_plays_status

2022-08-05 10:28 UTC, Omnomus commented on apps/core/utils.py
> +            if element.item.items.filter(published=False).exists()
а можешь мне тут объяснить? Element - это же экземпляр AbstractContent, откуда у него item? Я в конструкторе плавать начинаю, если с ним задача не связана ((

2022-08-05 10:28 UTC, Omnomus commented on apps/core/utils.py
> +def add_message_error(name):
ну тоже бы изменила  на add_error_message. По названиям функций это субъективное восприятие)

2022-08-05 13:46 UTC, stepakiselev commented on apps/core/utils.py
> +            if element.item.items.filter(published=False).exists()
ох, в этом конструкторе я запутываюсь. насколько я понял: сперва с помощью этой конструкции `obj.contents.filter(content_type__model="playsblock")` я нашел объект `OrderedPlay`, у него есть `ForeignKey` Play и по нему переходим в пьесы, где смотрим поле `published`. короче нагромождение вышло, наверно его можно как то оптимизировать, если есть мысли дай знать

2022-08-07 16:06 UTC, Omnomus approved these changes

2022-08-07 16:12 UTC, Omnomus commented on apps/core/utils.py
> +            if element.item.items.filter(published=False).exists()
так, Антон сказала не будем ограничение у артиклей вводить, тогда эту часть убираем и вопросов нет)

2022-08-07 16:13 UTC, Omnomus requested changes

2022-08-07 16:13 UTC, Omnomus commented on apps/core/utils.py
> +            if element.item.items.filter(published=False).exists()
жаль только, что часть кода выкинем

2022-08-07 16:16 UTC, AntonZelinsky approved these changes

2022-08-07 16:16 UTC, AntonZelinsky commented on apps/core/utils.py
> +            if element.item.items.filter(published=False).exists()
Вообще, хотелось бы в 1 или максимум 2 запроса всё сжать, так как если будет 20 блоков с пьесами, то для каждого блока будет запрос.

2022-08-07 16:44 UTC, Omnomus commented on apps/core/utils.py
> +            if element.item.items.filter(published=False).exists()
Ты же писал, что не будем эти ограничения добавлять? Тогда весь этот блок становится не нужен

2022-08-07 20:18 UTC, AntonZelinsky commented on apps/core/utils.py
> +            if element.item.items.filter(published=False).exists()
Да, точно, давайте делать как проще. В конце концов, на самой пьесе будет написано, что она не опбликована.

2022-08-10 17:06 UTC, AntonZelinsky approved these changes

2022-08-10 18:25 UTC, merged