Feature/generate css file
Studio-Yandex-Practicum/Lubimovka_backend pull request #589
Opened 2022-08-09 15:47 UTC by inferno2f

[Тикет PR](https://www.notion.so/css-d96ab694ad484ee5bda60dd0b6af1b76)
[Второй тикет](https://www.notion.so/14ea55d0c690401989810df499c9ba1c)

- В общих настройках появились поля для цветов основного фона и акцента
- Добавлен метод `generate_css` для автогенерации css файла (хранится в `apps/core/static/`)
- Файл css генерится при сохранении любой из настроек цвета
- Исправлена опечатка в названии настройки с PR директором

2022-08-09 16:11 UTC, AntonZelinsky approved these changes

2022-08-09 16:11 UTC, AntonZelinsky commented on apps/core/static/site_colors.css
> +:root {
Файл нужно в гит игнор добавить, так как он постоянно бдует маячить и думаю, что нет смысла его сюда добавлять, так как при накатывании твоих миграций, он будет перегенерирован.
Хотя, может для истории и просмотра кода через гит хаб пусть будет тут

2022-08-09 16:11 UTC, AntonZelinsky commented on apps/core/models.py
> +            css_file_contents = f":root {{\n--background-color: {main_color};\n--accent-color: {secondary_color};\n}}\n"
Не красиво и не читаемо( Объяви строку с помощью ''', а потом, с помощью format установи значения.

2022-08-09 17:27 UTC, inferno2f commented on apps/core/models.py
> +            if self.text:
По поводу `self.text` - можно, конечно, наверное сделать кастомные валидатор чтобы ни одно из значений не было пустым. Проверка в нынешнем виде позволяет не запускать генерацию css файла если значение удалили (случайно), но вообще при желании с таким кодом можно сделать как минимум одно поле пуустым

2022-08-09 17:30 UTC, inferno2f commented on apps/core/models.py
> +            if self.text:
А можешь пояснить как ты предлагаешь объединить эти ифы? Вопрос из серии "я тупой" )))
что-то вроде такого?
'color_settings_keys = ("background_color", "accent_color")'
`if self.settings_key in color_settings_keys`

2022-08-09 17:31 UTC, inferno2f commented on apps/core/models.py
> +        secondary_color = self.get_setting("accent_color")
Блин... ) Ну как всегда... Сначала пишешь костыль, который сложнее и запутаннее чем нужный код....
Уже исправил 🙈

2022-08-09 18:16 UTC, inferno2f commented on apps/core/models.py
> +            css_file_contents = f":root {{\n--background-color: {main_color};\n--accent-color: {secondary_color};\n}}\n"
Если сделать стринг через `"""`, то возникает лишний геморрой с лишними отступами при переносе на новую строку. У меня был более "красивый и читаемый" вариант, но его наши прекомит хуки не пускают по требованиям black.
Пример (красным мой код, зеленым - то, как хочет black):
<img width="1459" alt="Screen Shot 2022-08-09 at 2 13 14 PM" src="https://user-images.githubusercontent.com/25581875/183730777-ee1ce721-ed26-44d0-bfba-cd0df29d7f6d.png">

2022-08-10 10:53 UTC, AntonZelinsky commented on apps/core/models.py
> +            if self.text:
```suggestion
        if self.text and (self.settings_key == "background_color" or self.settings_key == "accent_color"):
```

2022-08-10 10:59 UTC, AntonZelinsky commented on apps/core/models.py
> +            css_file_contents = f":root {{\n--background-color: {main_color};\n--accent-color: {secondary_color};\n}}\n"
По идее, так должно работать. Блэку скажи проигнорировать строки на которые он жалуется. Он не должен мешать нам делать понятный и читаемый код
```
css = """
:root {
 --background-color: {main_color};
 --accent-color: {secondary_color};
 }
"""
css .format(
```

2022-08-10 13:12 UTC, Omnomus commented on apps/core/migrations/0028_add_color_settings.py
> +    )
Еще нужно актуализировать миграцию 0002

2022-08-10 13:20 UTC, inferno2f commented on apps/core/migrations/0028_add_color_settings.py
> +    )
А зачем в двух местах править название?
Я видимо туповат, по этому вместо того, чтобы исправить опечатку в первоначальной миграции 0002, просто переделал значение целиком в новой миграции 0028

2022-08-10 13:31 UTC, Omnomus commented on apps/core/migrations/0028_add_color_settings.py
> +    )
Нет, ты все правильно сделал, изменения в 0002 уже не дадут никакого эффекта. Но там их все же надо внести, так как мы по мере сил стараемся ее держать в полностью актуальном состоянии

2022-08-10 13:39 UTC, Omnomus requested changes

2022-08-10 13:39 UTC, Omnomus commented on apps/core/migrations/0028_add_color_settings.py
> +        "description": "Цвет основного фона сайта",
это тоже поменяй, пожалуйста

2022-08-10 13:39 UTC, Omnomus commented on apps/core/migrations/0028_add_color_settings.py
> +        field_type="TEXT",
Здесь нужно через get_or_create и внести в 0002. Я про это писала в слаке.

2022-08-10 13:49 UTC, inferno2f commented on apps/core/migrations/0028_add_color_settings.py
> +        field_type="TEXT",
🫠

2022-08-10 14:10 UTC, Omnomus approved these changes

2022-08-10 16:28 UTC, AntonZelinsky commented on apps/core/migrations/0028_add_color_settings.py
> +    )
Всё верно, ведь если в какой-то момент, кто-то решит узнать все значения которые мы вставляем в базу руками, придётся перерыть все миграции, а это очень будет тяжело!

2022-08-10 16:32 UTC, merged