Feature/add edit review
Studio-Yandex-Practicum/Lubimovka_backend pull request #590
Opened 2022-08-10 09:58 UTC by stepakiselev

Тикет вашего PR (если есть):
    ___[ваш тикет](https://www.notion.so/f0e21b92fc234971a922a50aee52836d)___

На странице фестиваля (на админке) у волонтёров нет возможности посмотреть или изменить отзыв

Добавил прокси модель Review, от нее создал модель для админки где фигурируют только два поля заголовок и текст, на которую можно попасть только через кнопку редактировать отзыв из. модели VolunteerInline

2022-08-14 21:36 UTC, AntonZelinsky approved these changes

2022-08-17 09:29 UTC, Omnomus requested changes

2022-08-17 09:29 UTC, Omnomus commented on apps/info/migrations/0025_review.py
> +# Generated by Django 3.2.13 on 2022-08-07 13:12
Надо миграцию поменять на 0026, 0025 уже есть, Влад правил

2022-08-17 09:29 UTC, Omnomus commented on apps/library/models/play.py
> +from apps.info.models.festival import Festival
А зачем это?..

2022-08-20 10:07 UTC, stepakiselev commented on apps/library/models/play.py
> +from apps.info.models.festival import Festival
там проблема была с импортами

2022-08-21 07:40 UTC, Omnomus approved these changes

2022-08-21 13:04 UTC, AntonZelinsky approved these changes

2022-08-21 13:04 UTC, merged