Feature/add factory and tests info
Studio-Yandex-Practicum/Lubimovka_backend pull request #67
Opened 2021-11-16 10:19 UTC by AnnaKPolyakova

Дополнила фабрики (festival, image)
Добавила тесты для Festival и FestivalTeam

2021-11-17 18:16 UTC, KonstantinRaikhert reviewed
Круто! Тесты. Pytest выглядит не так ужасно.

2021-11-18 20:30 UTC, evi1ghost commented on apps/info/tests/factories.py
> +    selected_plays_count = factory.Faker("random_int", min=1, max=200, step=1)
Если я правильно понял, то общее число пьес (plays_count) должно превышать число отобранных пьес (select_plays_count). Предлагаю поставить для select_plays_count разброс от 1 до 20, а для plays_count - от 20 до 200.

2021-11-18 21:27 UTC, DRAGANmik approved these changes

2021-11-20 19:08 UTC, nkiryanov requested changes
Пожелания:

1. Переформатировать тесты соблюдая AAA, думать о простоте
2. Давать более подробные названия тестам, отражающие его суть
3. Тесты проверяющие более 1 штуки разбивать на 2
4. Не бояться хардкодить в тесты url

2021-11-20 19:08 UTC, nkiryanov commented on apps/info/tests/test_views.py
> +            FestivalTeam.TeamType.ART_DIRECTION,
Да не нужно выносить в такие переменные. Тут реально нужно URL написать и его и проверить. Я бы рекомендовал вообще 2 теста разных написать. Которые будут почти копией друг друга.

Вот представь фронту или кто-то разбирается почему тест упал. Нужно будет искать что значит это `FestivalTeam.TeamType.ART_DIRECTION`.
А если будет просто

```python
url = http://blbla-bla.ru/teams/?art-director=True
response = client.get(url)
``` 

станет гораздо полезнее и понятнее

2021-11-20 19:08 UTC, nkiryanov commented on apps/info/tests/test_views.py
> +    def test_get_teams_detail(self, client, team):
Тут не пишу, но в целом для всех тестов примерно одни пожелания.

2021-11-21 10:18 UTC, AnnaKPolyakova commented on apps/info/tests/factories.py
> +                self.volunteers.add(volunteer)
Если передавать вот так: self.volunteers.add(extracted), то будет ошибка:  TypeError: Field 'id' expected a number but got [<Volunteer: Руслан Лихачев - волонтёр фестиваля 2018 года>, <Volunteer: Вышеслав Горшкова - волонтёр фестиваля 2019 года>, <Volunteer: Георгий Алексеев - волонтёр фестиваля 2018 года>]

2021-11-21 10:40 UTC, AnnaKPolyakova commented on apps/info/tests/test_urls.py
> +            FESTIVAL_YEARS_URL,
Вроде везде через revers. Где не через него? Как по именно через него и надо использовать.

2021-11-21 11:00 UTC, AnnaKPolyakova commented on apps/info/tests/conftest.py
> +        for _ in range(random.randint(0, 5))
Тогда кол-во объектов для каждой фикстуры придется захардкодить в отдельной константе и обращаться к ней из тестов, это не выглядит удобным

2021-11-21 11:02 UTC, AnnaKPolyakova commented on apps/info/tests/test_urls.py
> +    def test_get_teams(self, client, teams):
тут ошиблась, тут мы вообще урл проверять должны, поправила

2021-11-21 11:09 UTC, AnnaKPolyakova commented on apps/info/tests/test_views.py
> +            assert data.get(field) == getattr(festival, field), (
Я не оч понимаю, что ты хочешь вместо assert data.get(field) == getattr(festival, field)? Отдельный метод, который даст значение поля? Зачем усложнять? Act - мы сделали запрос с url и получили data, далее assert - проверяем соответствуют ли поля.

2021-11-21 11:09 UTC, AnnaKPolyakova commented on apps/info/tests/test_views.py
> +    def test_get_teams(self, client, teams):
Да, из урл убрала его, от там по ошибке остался

2021-11-21 11:13 UTC, AnnaKPolyakova commented on apps/info/tests/test_views.py
> +            assert FestivalTeam.objects.filter(
Где не соответсвие AAA?

2021-11-21 11:19 UTC, AnnaKPolyakova commented on apps/info/tests/test_views.py
> +            FestivalTeam.TeamType.ART_DIRECTION,
Зачем делать 2 теста и дублировать код? Это неправильно. Если тест падает, то  пояляется сообщение в котором виден понятный и человекочитаемый url AssertionError: Проверьте, что при GET запросе /api/v1/info/about-festival/team/?team=fest возвращаются только соответствующие объекты 0 != 1

2021-11-21 11:20 UTC, AnnaKPolyakova commented on apps/info/tests/test_views.py
> +            FestivalTeam.TeamType.ART_DIRECTION,
Нигде не видела рекомендаций использовать url, всю учебу в практикуме учили выносить именно так

2021-11-21 11:36 UTC, AnnaKPolyakova commented on apps/core/management/commands/filldb.py
> +            self.stdout.write(
В следующий раз посмотрю

2021-11-21 12:17 UTC, nkiryanov commented on apps/info/tests/conftest.py
> +        for _ in range(random.randint(0, 5))
А почему прямо здесь не написать:

```
PersonFactory.create_batch(5)
SponsorFactory.create_batch(5)
```

И всё. Чем это плохо? Мне кажется так:
- выглядит проще
- результат предсказумее (создается по 5 объектов и можем использовать это знание в тестах)

2021-11-21 13:10 UTC, nkiryanov requested changes
Прокомментировал и ответил.

Тут в общем ничего нового практически не добавилось, скорее разъяснял вопросы с прошлого ревью.

2021-11-21 13:10 UTC, nkiryanov commented on apps/info/tests/test_views.py
> +            assert FestivalTeam.objects.filter(
Вот это — `assert FestivalTeam.objects.filter(`

Тут в assert занимаешься "arrange" — подготовкой данных. Это сложно для понимания и чтения тестов.

Посмотри plz примеры тестов по ссылке и какие там асёрты. Вот к таким нужно нам стремиться.

2021-11-21 13:10 UTC, nkiryanov commented on apps/info/tests/test_urls.py
> +@pytest.mark.django_db(
Вроде писал где-то, но найти не могу.
А вот такое объявление в начале файла не убирает необходимости добавлять декоратор классам/тестам?

`pytestmark = (pytest.mark.django_db,)`

2021-11-21 19:26 UTC, AnnaKPolyakova commented on apps/info/tests/conftest.py
> +        for _ in range(random.randint(0, 5))
Тем, что это кол-во надо в константу выносить, если ты хочешь в тесте ссылаться на него. Ибо хардкодить в нескольких местах одно и то же значение - это плохо. Должно быть так - меняем значение в одно месте - меняется везде.

2021-11-21 19:34 UTC, AnnaKPolyakova commented on apps/info/tests/test_urls.py
> +            FESTIVAL_YEARS_URL,
FESTIVAL_YEARS_URL = reverse("festivals_years") - эта константа содержит revers

2021-11-21 19:37 UTC, AnnaKPolyakova commented on apps/info/tests/test_urls.py
> +            FESTIVAL_YEARS_URL,
Во втором случае константа revers ибо мне надо в урл год фестиваля вставить, который я могу достать только из фикстуры в самом тесте. Считаю, что не должно быть в самих тестах никаких захардкоженых значений, поэтому все вынесено в константы. В случае чего, меняем значение в водно месте - меняется везде.

2021-11-21 20:04 UTC, AnnaKPolyakova commented on apps/info/tests/test_views.py
> +            assert data.get(field) == getattr(festival, field), (
К цитате вопросов нет, но никаких вызовов сценариев getattr не делает. Зачем нам заменять эту 1 строчку отельным методом?  Какое название переменной не понятно? Если уж очень хочется пояснить, можно добавить строчку "expected_field_value = getattr(festival, field) и ниже эту переменную передавать в assert".

2021-11-21 20:27 UTC, AnnaKPolyakova commented on apps/info/tests/test_views.py
> +            assert FestivalTeam.objects.filter(
Если смущает именно вычисления в assert -  можно выносить их в переменные строкой выше. часто это вычисления, которые не будут повторяться в других тестах и не имеет смысла делать под это отдельный метод. 
В какой момент было у нас внутри был утвержден именно такой подход к написани тестов, как по ссылке?

2021-11-21 20:38 UTC, AnnaKPolyakova commented on apps/info/tests/test_views.py
> +            FestivalTeam.TeamType.ART_DIRECTION,
Думаю, что в данном случае, не стоит копировать весь тест. Если не очевидно, что происходит, то лучше тогда в соответсвующие переменные вынести действия, например:
            count_festival_teams = FestivalTeam.objects.filter(
                team=teams_filter
            ).count()
            count_objects_in_data = len(data)
            assert count_festival_teams == count_objects_in_data, (
                f"Проверьте, что при GET запросе "
                f"{TEAMS_URL_FILTER + teams_filter}"
                f" возвращаются только соответствующие объекты"
            )

2021-11-21 20:49 UTC, AnnaKPolyakova commented on apps/info/tests/test_views.py
> +    @pytest.mark.django_db(transaction=True)
Да, только если вот так pytestmark = pytest.mark.django_db

2021-11-21 20:51 UTC, AnnaKPolyakova commented on apps/info/tests/test_views.py
>          for field in [
Ключевое - не принципиально

2021-11-22 22:08 UTC, nkiryanov requested changes
Осталось:

- вопрос с случайными значениями для фикстур
- порядок задания переменных в тестах (что сначала Arrange, потом Act)

2021-11-22 22:08 UTC, nkiryanov commented on apps/info/tests/test_views.py
> +            assert data.get(field) == getattr(festival, field), (
Да про это и речь.
Это тебе сейчас понятно что делает `getattr(festival, field)`, но совсем не очевидно зачем именно это делаем когда будешь смотреть тест через месяц. Вынос в переменную упрощает + соответствует AAA

2021-11-22 22:08 UTC, nkiryanov commented on apps/info/tests/conftest.py
> +        for _ in range(random.randint(0, 5))
Во-первых можно в константу.
Во-вторых, фикстуры для тестов. Не предполагается, что их будут править без правки тестов.
В-третьих даже если не выносить в константу это точно **не хуже** случайных значений.

В итоге зачем случайные значения?

Я готов оставить случайные, но какой от этого профит для тестов?

В чем минусы:
- создание фикстура чуть сложнее чем могло бы быть
- сразу возникает вопрос, зачем случайные значения (нужно думать об этом, а думать — плохо)
- если в каком-то тесте нужно будет проверить количество объектов не сможем это сделать

2021-11-23 10:18 UTC, AnnaKPolyakova commented on apps/info/tests/conftest.py
> +        for _ in range(random.randint(0, 5))
Ок, соглашусь, что случайность выбора нам тут, наверное, ничего не даст. Но, считаю, что проверять кол-во объектов в тесте в любом случае правильно именно подсчетом объектов, а не ссылкой на константное значение.

2021-11-23 23:09 UTC, nkiryanov approved these changes
Апрув!

2021-11-23 23:25 UTC, merged