django admin image preview
Studio-Yandex-Practicum/Lubimovka_backend pull request #68
Opened 2021-11-17 15:12 UTC by DRAGANmik

2021-11-17 17:12 UTC, AntonZelinsky commented
Кстати, тут есть пример того, как можно решить подобную задачу. Просто делюсь, так как попало на глаза
https://books.agiliq.com/projects/django-admin-cookbook/en/latest/imagefield.html

2021-11-20 19:22 UTC, nkiryanov requested changes
В целом очень приятный PR.

Написал пару комментариев. Из самых критичных (то есть других более критичных нет) это формат докстринга.

Почему не апрвунул: не понял, почему удаляем регистрацию модели изображения в core.

2021-11-20 19:22 UTC, nkiryanov commented on apps/core/utilities/mixins.py
> +    """
За докстринг спасибо! Но он чуть не по фэншую.

[Вот так](https://www.python.org/dev/peps/pep-0257/#multi-line-docstrings) по PEP

2021-11-20 19:22 UTC, nkiryanov commented on apps/core/utilities/mixins.py
> +    image_preview_change_page.short_description = "Превью"
В [django 3.2](https://docs.djangoproject.com/en/3.2/ref/contrib/admin/#the-display-decorator) можно в декоратор убирать.

Так красивее и понятнее.

2021-11-20 19:22 UTC, nkiryanov commented on docs/admin_image_preview.md
> +**Как подключить превью в админке:**
Оу, оу 👍

2021-11-20 19:22 UTC, nkiryanov commented on apps/core/admin.py
> -admin.site.register(Image)
Стоп, а это удалять не нужно тут. Регистрировать картинку нужно core. Расскажешь для чего удалили?

2021-11-20 19:43 UTC, DRAGANmik commented on apps/core/admin.py
> -admin.site.register(Image)
Просто в конструкторе есть изображения, показалось, что это одно и тоже. Вернул

2021-11-20 19:55 UTC, nkiryanov requested changes
Ой. `pass` видать на огонек в субботу пришел 👍

2021-11-20 19:55 UTC, nkiryanov commented on apps/core/utilities/mixins.py
> -    Mixin makes preview for uploaded images
По фэншую вот так:

```python
"""Mixin makes preview for uploaded images.

Need to add parameters in admin class
    list_display = ("image_preview_list_page",)
   readonly_fields = ("image_preview_change_page",)
"""
```

То есть в данном случае есть заголовок. Его в одно предложение наверх. Потом через пустую строку текст.

2021-11-20 19:55 UTC, nkiryanov commented on apps/core/utilities/mixins.py
>          pass
😗😗😗  😂

2021-11-20 20:09 UTC, nkiryanov approved these changes

2021-11-20 20:10 UTC, DRAGANmik commented on apps/core/utilities/mixins.py
> -    Mixin makes preview for uploaded images
Поправил

2021-11-20 20:10 UTC, DRAGANmik commented on apps/core/utilities/mixins.py
>          pass
убрал

2021-11-20 20:11 UTC, merged