add a ckeditor
Studio-Yandex-Practicum/Lubimovka_backend pull request #69
Opened 2021-11-17 17:35 UTC by Polinavas95

Добавила редактор в админку в "Тексты". Можно применять стили, выделять курсивом/жирным/пассажирным стилем буквы и слова. есть коготки, лапки, цитата, поддерживает неразрывный пробел

2021-11-17 18:11 UTC, KonstantinRaikhert reviewed
на продакш работать похоже не будет) Надо включить приложение в настройках джанги.
И обязательно взять последний pull с develop ветки.

2021-11-17 18:11 UTC, KonstantinRaikhert commented on config/settings/local.py
> +INSTALLED_APPS += ["ckeditor"]  # noqa: F405
Может стоит добавить в prod.py или base.py?

2021-11-20 19:41 UTC, nkiryanov requested changes
1. Нужно обновить миграции (проверил, что отсутствуют новая)
2. Микро комментарий про переносы на новые строки.

2021-11-20 19:41 UTC, nkiryanov commented on apps/content_pages/models/content_items.py
> +    text = RichTextField(blank=True, null=True)
У нас есть [правила](https://github.com/Studio-Yandex-Practicum/Lubimovka_backend/blob/develop/docs/codestyle.md) как пишем такие поля в моделях и когда. Давай придеорживаться plz.

Тут же: а почему разрешаем не заполнять это поле? Оно обязательное для заполнения было. Это не ошибка.

2021-11-22 21:42 UTC, nkiryanov requested changes
Полина, ну ка соберись :)

Что нужно делать, чтоб PR быстрее проверялись:
1. Исправить/закрыть все правки из прошлого ревью.
2. Вот тут на скриншоте кнопочка — это запросить повторный ревью. Значит, что всё готово и задачу передаешь ревьюверу.

В этот PR нужно миграцию добавить.
<img width="367" alt="Screenshot 2021-11-23 at 00 37 15" src="https://user-images.githubusercontent.com/70921439/142939312-38733210-b544-4327-a97f-3f9f34496168.png">

2021-11-24 20:17 UTC, nkiryanov approved these changes
Апрув.
Но ребятам с фронта неплохо написать об изменениях с примером что поменялось.

2021-11-26 16:37 UTC, merged