Bugfix/event api
Studio-Yandex-Practicum/Lubimovka_backend pull request #75
Opened 2021-11-21 22:28 UTC by evi1ghost

Изменения ответа api афиши:
1. Поля `directors` и `dramatists` в `event_body` читки, а также поле `hosts` мастер-класса отдаются в виде списков (до этого драматург, режиссер и ведущий у этих событий мог быть только один);
2. В `event_body` всех событий включено поле project (связь с Проектом для возможности отображения названия проекта в афише);
3. `event_body` спектакля дополнено полем image (главная картинка из модели Пьесы, по которой ставится спектакль);

Изменения меделей библиотеки:
1. Для того, чтобы не плодить лишние таблицы, добавляя m2m между Reading, MasterClass и Person, модель PerformancePerson преобразована в TeamMember, через которую с Person связаны все типы событий (читка, спекталь, мастер-класс).
2. Изменен тип поля для роли члена команды - теперь это FK к новой таблице Role (это позволит при необходимости создовать новые роли).
3. В отдельную миграцию зашито создание базового набора ролей.
4. В спектакль, читку, мастер-класс добавлена необязательная связь с моделью Project.

Пример обновленного ответа api афиш
![afisha](https://user-images.githubusercontent.com/76372522/142781159-c3ac5595-a844-4243-b83e-3e5c4139b209.png)
и:

2021-11-22 21:32 UTC, nkiryanov requested changes
Ключевое изменение которое нужно сделать: добавить ролям slug/code и использовать в работе БД его. По нему сортирвоать, его отдавать фронту.

Подобное изменение нужно для event (там проще делаются).
Есть мысли как сделать код красивее и оптимизировать, обращения к БД но это чуть подход поменять нужно будет, не оч быстро и ща не обязательно.

2021-11-22 21:32 UTC, nkiryanov commented on apps/library/serializers/performanceperson.py
> +    role = serializers.ReadOnlyField(source="role.name")
Так ок. Но я везде SlugRelatedField люблю использовать. Оно более универсальное. Ему новый атрибут будет нужен (read_only=True). В общем по желанию. Так ок.

2021-11-22 21:32 UTC, nkiryanov commented on apps/library/serializers/masterclass.py
> +    hosts = serializers.SerializerMethodField()
Вообще так будет работать, но каждый запрос к API будет требовать кучу запросов к базе данных. Всё потому что происходит в SerializerMethodField происходит каждый раз фильтрация.

Можно сделать оптимизировать запросы и сделать красивее — перенеся эту логику в QuerySet  и аннотировов кверисет. Тогда код сериализаторов станет совсем простым, а запросов к БД уменьшится.

В целом так сделать не сложно и не оч долго. Если дойдут руки расскажу.

2021-11-22 21:32 UTC, nkiryanov commented on apps/afisha/serializers/event.py
>              "type",
Пишу тут, но вообще относится к модели.
Давай сделаем так как делаем на всём проекте и как архитектурно более правильно.

Варианты выбора из кортежа заменить на TextChoices.
Хранить в базе и фронту отдавать названия в латинице (PERFORMANCE), а в админке будем показывать Спектакль.

Чтобы тип был

`"type": "PERFORMANCE"`
а не
`"type": "Спектакль"`

2021-11-22 21:32 UTC, nkiryanov commented on apps/library/models.py
> +class Role(BaseModel):
У роли нужно добавить slug или код. То что будет написано латиницей и не будет меняться. Название (кирилицей) давать возможность менять.

2021-11-22 21:32 UTC, nkiryanov commented on apps/library/models.py
> +    name = models.CharField(
Если нет slug, то имя должно быть уникальным.
Но давай добавим slug или code.

2021-11-22 22:34 UTC, nkiryanov commented on apps/library/serializers/masterclass.py
> +    hosts = serializers.SerializerMethodField()
Не нашел ничего лучше чем прислать ссылку на дипломный проект, там были достаточно любопытные аннотации.

[Ссылка](https://github.com/nkiryanov/foodgram-project-react/blob/9b8fd8c9e828b427892dca33cc822c99b2efbe0b/backend/foodgram/recipes/models.py#L108)

Суть в том, что аннотируем (добавяляем) в queryset набор полей и потом с ними работаем в сериалайзере как с обычными.
Оч удобно, код весь в моделях остается, все вычисления на уровне БД (то есть быстрее).

2021-11-23 22:50 UTC, evi1ghost commented on apps/afisha/admin.py
>          return qs
По созданию события:
Предполагается, что сначала создается читка, мастер-класс или спектакль, а потом на их основе событие (базовое событие создается автоматически для каждого из перечисленных объектов).
Из админки события создать читку, мастер-класс или спектакль не получится. Не учерен, что это можно легко и быстро исправить. Думаю на данном этапе можно отправить пользователя в админку библиотеки.
Сейчас хочется отдать api на фронт.

А где ты нашел информацию, что мастер-класс не может быть платным?

2021-11-23 22:51 UTC, evi1ghost commented on apps/library/serializers/performanceperson.py
> +    role = serializers.ReadOnlyField(source="role.name")
Этот сериализатор больше не нужен. Удалил.

2021-11-23 23:05 UTC, nkiryanov commented on apps/afisha/admin.py
>          return qs
А может быть тогда вообще уберем события из админки или сделаем их только для просмотра?
Просто у меня не удалось создать вообще ничего.

>А где ты нашел информацию, что мастер-класс не может быть платным?

Хм. Видел, что спектакль может быть платным, а про остальное ничего про платность не было. Может быть платным им быть ок, мастер-класс же.
Давай оставим, ага.

2021-11-25 23:07 UTC, evi1ghost commented on apps/afisha/admin.py
>          return qs
Если убрать события из админки, то как же их создавать пользователю?
Убрал CommonEvent из админки.
В Event для поля события добавил help_text.

2021-11-25 23:11 UTC, evi1ghost commented on apps/library/serializers/masterclass.py
> +    hosts = serializers.SerializerMethodField()
Пока вывод членов команды реализовал через функцию (в apps/library/utilities.py)
Попробовал засунуть эту функцию в QuerySet - не получилось. Возможно не до конца разобрался как это работает. Высплюсь - попробую еще раз.

2021-11-27 19:46 UTC, nkiryanov requested changes
Есть небольшие правки по оформлению и codestyle (ща думаю что всё по стилю кода нужно как-то автоматизировать, чтоб не тормозить ими PR + точно не было ошибок).

2021-11-27 19:46 UTC, nkiryanov commented on apps/afisha/models.py
> +    class EventType(models.TextChoices):
👍

2021-11-27 19:46 UTC, nkiryanov commented on apps/afisha/models.py
> +    def clean(self):
[Есть порядок](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/#model-style) размещения методов в моделях. 

Может есть какое-то расширение для flake8 которое умеет такое проверять, что не ручками замечать 🧐

2021-11-27 19:46 UTC, nkiryanov commented on apps/library/models/author.py
> +                fields=["author", "name"],
Можно и кортежиком сделать. Как и сам constraints если на то пошло дело.

2021-11-27 19:46 UTC, nkiryanov commented on apps/library/models/participation_application.py
> +    Заявки на участие в фестивале
Тут docstirng не по фэншую (наверное не твой код, но мне на глаза попался).

Вот тут точно есть расширение для flake8, поставим.

2021-11-27 19:46 UTC, nkiryanov commented on apps/library/models/participation_application.py
> +        Generate new filename as "Last_name-Title" format
Вообще тоже докстринг не по PEP257

2021-11-27 19:46 UTC, nkiryanov commented on apps/library/models/participation_application.py
> +        Save generated filename
И тут не PEP257

2021-11-27 19:46 UTC, nkiryanov commented on apps/library/utilities.py
> +def team_collector(model, filters: dict = None) -> defaultdict:
Можно разобраться для чего метод, но нужно прямо въехать. Тут нужен dostring который опишет что происходит.

Я сделал то же самое, чуть по другому. Не могу сказать, какой из способов лучше. Давай запушим с твоим способом, а позже подумаем как сделать это оптимальнее и может быть универсально.

2021-11-28 07:39 UTC, evi1ghost commented on apps/afisha/models.py
> +    def clean(self):
Попробовал найти что-нибудь для flake8. Есть [flake8-django](https://github.com/rocioar/flake8-django). Заявлено, что умеет проверять code style в моделях (см. DJ12 в List of Rules), но почему-то не срабатывает, хотя специально расставлял неправильный порядок... Запускал через `flake8 --select=E,F,W,C90,DJ,DJ10,DJ12`
Находит только это: 
`./apps/core/models.py:156:19: DJ01 Avoid using null=True on string-based fields such CharField.
`

2021-11-28 08:11 UTC, evi1ghost commented on apps/library/models/participation_application.py
> +    Заявки на участие в фестивале
Да, есть - [flake8-docstrings](https://pypi.org/project/flake8-docstrings/)
Лучше отдельным PRом + определить какие ошибки скипать. Сейчас находит очень много, в основном - отсутствие docstring для публичных методов.

2021-11-28 11:01 UTC, nkiryanov approved these changes
👍  Апрув!

2021-11-28 11:01 UTC, nkiryanov commented on apps/content_pages/serializers/content_items.py
> +from apps.core.models import Person
О, это я пропустил? Спасибо!

2021-11-28 19:56 UTC, merged