set permissions via management command
Studio-Yandex-Practicum/Lubimovka_backend pull request #76
Opened 2021-11-23 11:14 UTC by Omnomus

Права для групп пользователей Админ и Редактор устанавливаются по команде ./ manage.py set_perms. В README внесены правки.

2021-11-23 14:45 UTC, AntonZelinsky requested changes
Опиши в теме ПР что делают эти изменения и для чего они нужны

2021-11-23 14:45 UTC, AntonZelinsky commented on apps/core/management/commands/fixture/fixture_group_perms.json
> +[{"model": "auth.group", "pk": 1, "fields": {"name": "admin", "permissions": [5, 6, 7, 8, 45, 46, 47, 48, 41, 42, 43, 44, 113, 114, 115, 116, 125, 126, 127, 128, 105, 106, 107, 108, 121, 122, 123, 12
А можно поподробнее описать, что за магические числа и что вообще этот ПР делает, потому что сейчас выглядит как странная магия.

2021-11-23 15:07 UTC, Omnomus commented on apps/core/management/commands/fixture/fixture_group_perms.json
> +[{"model": "auth.group", "pk": 1, "fields": {"name": "admin", "permissions": [5, 6, 7, 8, 45, 46, 47, 48, 41, 42, 43, 44, 113, 114, 115, 116, 125, 126, 127, 128, 105, 106, 107, 108, 121, 122, 123, 12
Числа - права (пермишены), указаны для группы Админ и Редактор. Изначально вручную распределены в админке, выгружены в json. Весь ПР - загрузка этих прав (распределение) одной командой - по аналогии с filldb.

2021-11-23 20:17 UTC, DRAGANmik commented
Пока что оставим так, потому что зашить это в миграции проблематично (если найдём решение, поменяем)

2021-11-23 20:17 UTC, DRAGANmik approved these changes

2021-11-24 20:39 UTC, nkiryanov approved these changes
Я апрувну, но попрошу мне рассказать в чём проблема через миграции сделать.
Чтоб самому быть побольше в теме + понимать где проблемы вообще.

2021-11-25 08:12 UTC, Omnomus commented
Проблема в чем: при загрузке в миграциях дампа таблицы auth.group  миграция не проходит, так как самих пермишенов еще нет (моя миграция идет последней). Можно зашить в миграцию и сами пермишены, но они дальше тянут таблицу контенттайп. Если все три таблицы в миграции - все проходит. Нашла вот такой тикет, кажется, это мой случай. https://code.djangoproject.com/ticket/23422

2021-11-27 11:33 UTC, AntonZelinsky approved these changes

2021-11-27 11:33 UTC, AntonZelinsky commented on apps/core/management/commands/set_perms.py
> +class Command(BaseCommand):
Command плохое название!Абсолютно не понятно что за команда.

2021-11-27 11:37 UTC, AntonZelinsky approved these changes
Поскольку данные не подгрузятся автоматически, как через миграции, то в процессе деплоя необходимо вызывать эту команду и создавать пользователя с правами редактор

2021-11-27 11:37 UTC, AntonZelinsky commented on apps/core/management/commands/set_perms.py
> +class Command(BaseCommand):
Command плохое название!Абсолютно не понятно что за команда.

2021-11-27 15:59 UTC, closed without merging

2021-11-27 16:01 UTC, Omnomus commented
Открыт новый PR (накладка вышла - этот PR сделан из форка).