Feature/users factory with roles
Studio-Yandex-Practicum/Lubimovka_backend pull request #80
Opened 2021-11-26 18:13 UTC by Omnomus

Добавила фабрики для пользователей с ролями админ (ники  admin_1 ... admin_5) и редактор (editor_1 ... editor_5). Пароль для входа в админка у всех один - pass. В README внесены изменения. Пользователи создаются по команде FILLDB (команда дополнена).

2021-11-27 18:26 UTC, nkiryanov requested changes
1. Нужно чуть оптимизировать fill_db (следовать DRY)
2. Комментарий про задание паролей в фабрике: в целом можно оставить как есть
3. Разрешить конфликты (ща появились)

2021-11-27 18:26 UTC, nkiryanov commented on apps/core/management/commands/filldb.py
> +            for _ in range(5):
Сейчас Аня в fill_db добавила хорошую функцию чтоб не дубировать код с оповещениями. Можно и нужно его использовать.

2021-11-27 18:26 UTC, nkiryanov commented on apps/core/tests/factories.py
> +    password = factory.PostGenerationMethodCall("set_password", "pass")
Ого! Не видел такого решения.

Я бы пожалуй рекомендовал использовать [другой подход из документации](https://factoryboy.readthedocs.io/en/stable/recipes.html#custom-manager-methods).
Почему:
- так мы вызываем кастомный менеджер и если в нём что-то изменится, то фабрика тоже будет работать ок
- можно будет задавать свои пароли при создании пользователей и они будут работать (как понимаю тут не сработает)

Но вполне ок, что это вкусовщина. Тут года меньше и выглядит красивее. Только не совсем неочевидно, что задаваемый пароль по умолчанию "pass" тут.

2021-11-27 18:26 UTC, nkiryanov commented on apps/core/management/commands/filldb.py
> +            self.stdout.write(
Сходу не помню исправлено ли уже в смердженном PR или они не пересекаются, но тут код дубируется. Прямо хочется сделать всё по красоте и избавиться от дубликатов. М?

2021-11-28 11:42 UTC, Omnomus commented on apps/core/tests/factories.py
> +    password = factory.PostGenerationMethodCall("set_password", "pass")
Тут оставила - меньше кода, кажется лаконичнее и красивее

2021-11-28 11:42 UTC, Omnomus commented on apps/core/management/commands/filldb.py
> +            for _ in range(5):
Сделано!

2021-11-28 11:42 UTC, Omnomus commented on apps/core/management/commands/filldb.py
> +            self.stdout.write(
вот тут не совсем поняла про что говоришь? про уведомления? тогда это первый комментарий твой, его поправила.

2021-11-28 21:09 UTC, elisey commented on apps/core/management/commands/filldb.py
> +                index += 1
Тут можно слегка упростить и вручную index не инкрементировать, пусть его инкрементит range. А если нужно, чтобы он начинался с 1, то

```
for index in range(1, 6)
    ...
    username=f"admin_{index}", add_role_admin=True
```

2021-11-29 00:26 UTC, nkiryanov approved these changes
В целом у меня нет дополнений.
Идея Елисея про индекс классная.

2021-11-29 08:43 UTC, elisey approved these changes
Я не против вмержить прям так, а замечанием можно поправить в следующем ревью, чтобы это не затягивать

2021-11-29 10:35 UTC, Omnomus commented on apps/core/management/commands/filldb.py
> +                index += 1
поправила!

2021-11-29 10:49 UTC, merged