Fix/vpg/get method
Studio-Yandex-Practicum/Lubimovka_backend pull request #81
Opened 2021-11-26 20:34 UTC by Polinavas95

добавила APIView для передачи информации на главную страницу в зависимости от статуса фестиваля. В админке есть возможность добавлять или убирать блоки по желанию

2021-11-26 22:57 UTC, AntonZelinsky requested changes

2021-11-26 22:57 UTC, AntonZelinsky commented on apps/core/views.py
> +        global contex
Ой, а можно поподробнее рассказать, зачем это нужно? У нас просто в проекте, насколько я знаю, ещё ни разу не использовался global и я хотел ы понять, действительно ли он нужен.

2021-11-26 22:57 UTC, AntonZelinsky commented on apps/core/serializers/festival.py
> +class SettingsSerializer(serializers.ModelSerializer):
Что-то я ни в твоём ПР, ни в старом коде не увидел, чтобы использовался этот сериализатор. И мне кажется, что он явно не должен быть

2021-11-26 22:57 UTC, AntonZelinsky commented on apps/core/views.py
> +        if festival_status:
То есть, у тебя будут получены данные о всех возможных вариантах главной страницы, но в конце, почему-то отсеятся какая-то часть... и это была сделана пустая работа?!?

2021-11-26 22:57 UTC, AntonZelinsky commented on apps/core/views.py
> +        if festival_status:
Так же, было ведь чёткое условие, что блоки должны выключаться и включаться!(

2021-11-26 22:57 UTC, AntonZelinsky commented on apps/info/serializers/partners.py
> +        )
подозреваю, что тут эксклюд нужен из как в классе выше

2021-11-26 22:57 UTC, AntonZelinsky commented on apps/info/serializers/places.py
> +class PlacesSerializer(serializers.ModelSerializer):
полная копия класса выше и нигде не используется

2021-11-26 22:57 UTC, AntonZelinsky commented on apps/info/serializers/sponsors.py
> +        )
тоже экслюды упущены. Вообще, у меня есть сомнения насчёт необходимости этого класса, даже если какое-то поле не нужно. 

эксклюд можно добавить так SponsorsSerializer(sponsors, many=True, exclude='persons')

2021-11-26 22:57 UTC, AntonZelinsky commented on apps/library/serializers/reading.py
> +class ReadingEventsSerializer(serializers.ModelSerializer):
То же есть вопросы к сериализатору!

2021-11-26 23:02 UTC, AntonZelinsky requested changes

2021-11-26 23:02 UTC, AntonZelinsky commented on apps/core/views.py
> +        if festival_status:
Должно для каждого меняемого поля отправляться запрос в сетинг (а лучше один, который просто достаёт необходимые свойства), а потом проверяется, если нужно свойство, то достают из базы записи, нет, к следующему. И сразу, добавлять в контекст по ключу и значению, а не один в конце

2021-11-26 23:04 UTC, AntonZelinsky commented on apps/core/views.py
> +        if festival_status:
Должно для каждого меняемого поля отправляться запрос в сетинг (а лучше один, который просто достаёт необходимые свойства), а потом проверяется, если нужно свойство, то достают из базы записи, нет, к следующему. И сразу, добавлять в контекст по ключу и значению, а не один в конце

2021-11-29 14:04 UTC, AnnaKPolyakova commented on apps/core/views.py
> +        if festival_status:
Поменяла условия

2021-11-29 14:04 UTC, AnnaKPolyakova commented on apps/info/serializers/partners.py
> +        )
+

2021-11-29 14:05 UTC, AnnaKPolyakova commented on apps/info/serializers/places.py
> +class PlacesSerializer(serializers.ModelSerializer):
Удалила

2021-11-29 14:05 UTC, AnnaKPolyakova commented on apps/info/serializers/sponsors.py
> +        )
+

2021-11-29 14:05 UTC, AnnaKPolyakova commented on apps/library/serializers/reading.py
> +class ReadingEventsSerializer(serializers.ModelSerializer):
+

2021-11-29 20:30 UTC, nkiryanov requested changes
Есть некоторые правки и думаю что нужно что-то с копипастой сериалайзеров сделать. Но это можно чуть позже отрефакторить.

В целом впечатление ОЧЕНЬ положительное. Видно, что продумано многое и некоторые решения классные.

2021-11-29 20:30 UTC, nkiryanov commented on apps/core/migrations/0012_add_settings.py
> +    Settings.objects.create(
Это блок с баннерами. Их несколько, не один. То есть давай в множественном числе его назовем.

2021-11-29 20:30 UTC, nkiryanov commented on apps/library/serializers/program_type.py
> +class ProgramTypeSerializer(serializers.ModelSerializer):
Вот это вообще по-моему не нужен.

2021-11-29 20:30 UTC, nkiryanov commented on apps/main/models.py
> +    def clean(self):
👍 за проверку, но кажется реализация подкачала

Вот этот метод — `Banner.objects.get()` в исключение упадет если объектов более чем 1 (а их будет больше чем 1)

По-моему тут нужно проверять есть ли id у self и в зависимости от этого делать filter и exists() по ID (по None или id)

2021-11-29 20:30 UTC, nkiryanov commented on apps/main/serializers.py
> +    def get_event_body(self, obj):
Тут ща ок (для ускорения процесса), но вообще это выглядит копипастой сериалайзера из афишы. Тогда либо в афише всё-таки делать "базовый" сериалайзер (который не будет меняться при если захотим что-то в афише поменять) или всякие сложные штуки (как метод get_event_body) вынести в сервис.

2021-11-29 20:30 UTC, nkiryanov commented on apps/main/serializers.py
> +        return event_body_serializers[type(event_body)](event_body).data
Вот эту штуку уже 3 (!!!) ревью прошу сделать понятно и оно перекочевало теперь в мэйн. Эх.

2021-11-29 20:30 UTC, nkiryanov commented on apps/main/serializers.py
> +        ]
Список, а не кортеж

2021-11-29 20:30 UTC, nkiryanov commented on apps/main/serializers.py
> +from apps.library.serializers.play import AuthorForPlaySerializer
Наверное просто из apps.library.serializers нужно брать

2021-11-29 20:30 UTC, nkiryanov commented on apps/main/serializers.py
> +class BlogItemListForMainSerializer(BlogItemBaseSerializer):
Вот тут нравистя как получилось :)

2021-11-29 20:30 UTC, nkiryanov commented on apps/main/utils.py
> +class Context:
Это очень нравится 👍

2021-11-29 20:30 UTC, nkiryanov commented on apps/main/utils.py
> +        program = ProgramType.objects.get(name="Шорт-лист")
Это на подумать: очень смущает когда используем "захардкоденные" названия. Тут бы slug какой.

2021-11-29 20:30 UTC, nkiryanov commented on apps/main/utils.py
> +        plays_items = program.plays.filter(festival=festival, is_draft=False)[
я б тут сразу назвал shot_list_plays, но это вкусовщина.

2021-11-29 20:30 UTC, nkiryanov commented on apps/main/views.py
> +        return Response({"context": context.context})
Статус код бы отдать явно добавить. Но вроде необязательно.

2021-11-29 20:35 UTC, AnnaKPolyakova commented on apps/articles/serializers/news_items.py
> +class NewsItemsSerializer(serializers.ModelSerializer):
Убрала

2021-11-29 20:40 UTC, AnnaKPolyakova commented on apps/core/migrations/0012_add_settings.py
> +        settings_key="main_add_affiche",
это ок, но почему именно ее не перевели?)

2021-11-29 20:44 UTC, AnnaKPolyakova commented on apps/core/migrations/0012_add_settings.py
> +    Settings.objects.create(
ок

2021-11-29 20:44 UTC, AnnaKPolyakova commented on apps/library/serializers/program_type.py
> +class ProgramTypeSerializer(serializers.ModelSerializer):
ок

2021-11-29 20:56 UTC, nkiryanov commented on apps/core/migrations/0012_add_settings.py
> +        settings_key="main_add_affiche",
эээ. Наверное потому что у нас плохо с английским языком. Если б ща не написала, я бы думал что afisha это ок :) 

Ну и потому что так сложилось в русском интернете: есть afisha.yandex.ru, но не affiche.. 
Если б начинали с нуля даже подумал бы как правильнее сделать.

2021-11-29 21:01 UTC, AnnaKPolyakova commented on apps/main/models.py
> +    def clean(self):
исправила

2021-11-29 21:05 UTC, AnnaKPolyakova commented on apps/main/serializers.py
> +    def get_event_body(self, obj):
Я все сериалайзеры копипастила, на мой взгляд, лучше переиспользовать сериализаторы, в любом случае нужно делать тесты, они и будут контролировать наличие необходимых полей у объектов и вообще адекватность работы вьюшки. И в этом случае не придется бояться, что сериализатор поменяется и все посыпется. В данном случае просто сделал как ты просил.

2021-11-29 21:07 UTC, AnnaKPolyakova commented on apps/main/serializers.py
> +        return event_body_serializers[type(event_body)](event_body).data
ахаха)) исправила

2021-11-29 21:14 UTC, AnnaKPolyakova commented on apps/main/utils.py
> +        program = ProgramType.objects.get(name="Шорт-лист")
слаг добавила

2021-11-29 21:14 UTC, AnnaKPolyakova commented on apps/main/utils.py
> +        plays_items = program.plays.filter(festival=festival, is_draft=False)[
ок

2021-11-29 22:15 UTC, AnnaKPolyakova commented on apps/main/views.py
> +        return Response({"context": context.context})
Да вроде и так статус возвращается

2021-11-29 22:16 UTC, AnnaKPolyakova commented on apps/main/serializers.py
> +    def get_event_body(self, obj):
В общем, предлагаю это систематизировать позднее

2021-11-29 22:41 UTC, nkiryanov commented on apps/main/serializers.py
> +    def get_event_body(self, obj):
Да, конечно, давай сделаем позднее.

2021-11-30 03:39 UTC, nkiryanov requested changes
Есть несколько комментариев.

То, что показалось можно сделать ещё лучше добавил отдельным PR. Посмотри его пожалуйста. Может быть возьмешь частично мои идеи.

2021-11-30 03:39 UTC, nkiryanov commented on apps/main/utils.py
> +import datetime
Переименовал с своём PR. Мне конечно utils больше нравится, но всё же лучше везде одинаково сделать

2021-11-30 03:39 UTC, nkiryanov commented on apps/main/views.py
> +class MainView(APIView):
Стал смотреть как отдаем фронту и понял что нет документации (swagger).
Добавить руками её сложно и подумал, что может помочь сериалайзер. Подумал, что сериалйзер тут вообще неплохо выглядит переписал в своём PR метод с сериалайзером.

Почему-то сразу не пришло в голову так сделать, хотя так даже проще получается.
Посмотри пожалуйста.

2021-11-30 12:26 UTC, AnnaKPolyakova commented on apps/main/utils.py
> +        self.context["places_team_serializer"] = places_team_serializer.data
ок

2021-11-30 14:35 UTC, nkiryanov approved these changes
Если учесть, что решили с сериализаторами и баннерами (то что их всех 3 и целая модель для них) разобраться позже, то по-моему всё отлично.

Апрув!

2021-11-30 14:47 UTC, closed without merging