to_review
Studio-Yandex-Practicum/Lubimovka_backend pull request #82
Opened 2021-11-26 21:01 UTC by MarselMulyukov

Когда создаёте PR, убедитесь, что:

- [ ] вы проверили обновления в [брифе](https://www.notion.so/00f5d5a6d39e426fa1ea7ab69b694f07)
- [ ] синхронизировали изменения кода с [ER-диаграммой базы данных](https://drive.google.com/file/d/1RCIPaEgaLUSqek3znd38VPCKSzOlmJFy/view) связей моделей
- [ ] тесты все пройдены и нет конфликтов
- [ ] созданы необходимые миграции

Когда ваш PR смержен:

- [ ] если у вас были изменения в API, сообщите об этом команде Фронта, им это важно знать!

2021-11-27 16:34 UTC, kr0t commented on apps/library/urls.py
> +    filters,
Я бы тут в названии немного конкретизировал, к чему относятся эти фильтры.

2021-11-27 16:44 UTC, kr0t commented on apps/library/views/filters.py
> +    years = list(
Я бы тут написал через [List Comprehensions](https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions)

2021-11-27 16:45 UTC, kr0t reviewed
Есть небольшие комментарии на поразмышлять.

2021-11-27 16:49 UTC, kr0t commented on apps/library/views/filters.py
> +    years = list(
Первые 2 линка в гугле говорят, что текущий вариант по идее работает быстрее) Но второй мне ближе)

2021-11-27 17:45 UTC, nkiryanov requested changes
**Что беспокоит**: что рекомендуемые мной изменения требуют по сути полностью переписать PR (хотя он и не оч большой). Тут может быть имеет смысл проконсультироваться с тимлидом тимлидов: правильные даю рекоменадции или и так сойдёт. Подниму вопрос в чатике тимлидов.

1. Мы же используем везде CBV. Совмещать CBV и FBV — плохая практика. Т.е давай использовать APIview
2. У нас уже есть API который возвращает список всех годов фестивалей. Он делался для того же самого. Если потребовалось расширить функционал, то давай "приберем" то, что уже не нужно.
3. Насколько понимаю ProgramType относится больше к фестивалю, чем библиотеке. Может быть имеет смысл перенести эту модель и API в инфо? Или как минимум удалить API с списком годов фестивалей.
4. Мне нравится идея отредактировать прошлый action у фестиваля. Почему бы не заменить years на что-то другое и отдавать там и программы. Ну или к другому эндпоинту прикрепить, если почему-то фестиваль не нравится.

2021-11-27 17:45 UTC, nkiryanov commented on apps/library/views/filters.py
> +def filters(request):
Мы же используем везде CBV. Совмещать CBV и FBV — плохая практика. Т.е давай использовать APIview

2021-11-27 17:45 UTC, nkiryanov commented on apps/library/views/filters.py
> +    years = list(
Посмотрите как получаем года в фестивале. Есть же **гораздо более оптимальный способ** который УЖЕ используем в проекте.

Вообще просматривать чужие PR много чему может научить, рекомендую :)

2021-11-27 17:45 UTC, nkiryanov commented on apps/library/urls.py
> +    filters,
Да, название неудачное. Имею в виду вообще filters должно быть запрещенным названием для view. Потому что по этому названию ожидаем увидеть именно фильтры (то, что фильтрует). А оказывается параметры годов типы программ.

2021-11-28 11:10 UTC, nkiryanov approved these changes
Написал комментарий по одному из параметров: не уверен, что он нужен. Но тут тебе виднее.

Апрув!

2021-11-28 11:10 UTC, nkiryanov commented on apps/library/views/playfilters.py
> +            json_dumps_params={"ensure_ascii": False},
Не уверен, что json_dumps_params={"ensure_ascii": False}, нам нужен, но ок.

2021-11-28 11:12 UTC, merged