add settings type on admin
Studio-Yandex-Practicum/Lubimovka_backend pull request #93
Opened 2021-12-02 20:32 UTC by KondratevAD

Черновой вариант. Пока не трогал миграции.

Что сделал:
- Добавил в модель Settings поле settings_group с выбором группы настроек. Предварительно разделил на 4 типа:
    I. Настройки почты
    II. Настройки главной страницы
    III. Настройки первой страницы
    IV. Общие настройки
- Получилось 4 proxy-модели.
- Зарегистрировал их в админке, за базу взял класс SettingsAdmin и в каждой отфильтровал queryset.

2021-12-02 21:07 UTC, nkiryanov requested changes
Подход верный и количество групп ща нравится.
Но есть что можно сделать чуть по другому/универсальнее.

2021-12-02 21:07 UTC, nkiryanov commented on apps/core/admin.py
> +class SettingsMailAdmin(SettingsAdmin):
queryset нужно определять в proxy моделях. Так у нас логика вся будет в моделях.
Для этого нужно задать переопределить мэнеджер, а [скорее сразу queryset](https://docs.djangoproject.com/en/3.2/topics/db/managers/#creating-a-manager-with-queryset-methods)

Вообще переопределиние менеджера по умолчанию (objects) считается не очень хорошей практикой, но у нас это proxy модели и мы их делаем как раз для этой цели. То есть от них наследовать ничего не будем и потому переопределить сразу objects будет ок.

Тогда модели в админке будут вообще изёвые.

2021-12-02 21:07 UTC, nkiryanov commented on apps/core/models.py
> +    GROUP_CHOICES = (
Для этого есть более удобная сущность — models.TextChoices
Это красивее и прекрасный API для доступа к значениям.

+ стоит придерживаться одного подхода во всём проекте. Если посмотришь буквально на 10 строчек выше, то уже есть пример на который можно было ориентироваться.

2021-12-02 21:07 UTC, nkiryanov commented on apps/core/models.py
> +    settings_group = models.CharField(
Я бы назвал просто group (как собственно и setting_key так себе название).
У нас же и так модель setting, уже понятно про что речь.

2021-12-02 21:07 UTC, nkiryanov commented on apps/core/models.py
> +        ordering = ("settings_group",)
Давай добавим ещё имя ключа. Чтоб в одной группе ключи сортировались по имени

2021-12-02 21:07 UTC, nkiryanov commented on apps/core/models.py
> +class SettingsMail(Settings):
Email пожалуй

2021-12-03 13:21 UTC, KondratevAD commented on apps/core/admin.py
> +class SettingsMailAdmin(SettingsAdmin):
Что-то не понимаю как это сделать. Точнее не очень понимаю как вывести это в админке.

2021-12-03 19:37 UTC, nkiryanov commented on apps/core/admin.py
> +class SettingsMailAdmin(SettingsAdmin):
Как сделать: есть пример в приложении content_pages
Там мы создаем кастомный queryset и добавляем мэенеджер (в модели ext_objects)

В данном случае удобно сделать для каждой прокси модели сделать свои queryset и назначить как manager по умолчанию (objects)

В админке тогда фильтровать ничего не нужно: будет отдаваться сразу нужный queryset

2021-12-03 19:38 UTC, nkiryanov commented on apps/core/admin.py
> +class SettingsMailAdmin(SettingsAdmin):
В целом могу даже написать и запушить в эту ветку. Кода совсем не много. Нужно?

2021-12-03 19:42 UTC, nkiryanov commented on apps/core/admin.py
> +class SettingsMailAdmin(SettingsAdmin):
Хотя... Кастомный queryset и manager тут даже лишние.
Можно [просто переопределить queryset по умолчанию](https://docs.djangoproject.com/en/3.2/topics/db/managers/#modifying-a-manager-s-initial-queryset).

2021-12-04 20:04 UTC, nkiryanov requested changes
Подход нравится, но есть некоторые правки.

2021-12-04 20:04 UTC, nkiryanov commented on apps/core/models.py
> +    name_group = "EMAIL"
Это вкусовщина, но я бы назвал `group_name`. Но если считаешь, что то, как есть лучше, то ок.

2021-12-04 20:04 UTC, nkiryanov commented on apps/core/models.py
> +    object = SettingsGroupManager()
Вот тут такая штука, что если от модели будем наследоваться (не будем, но могли же!), то потом столкнемся с серьезными проблемами.

Фишка в том, что теперь` SettingsEmail.objects.all()` вернет ошибку, что атрибута `objects` нет. Потому что мы указали другой manager и по умолчанию вообще не создался.

Давай назовём стандартно `objects` (s потеряли)

2021-12-04 20:04 UTC, nkiryanov commented on apps/core/models.py
> +class SettingsMain(Settings):
Вообще подход нравится 👍

2021-12-05 11:53 UTC, KondratevAD commented on apps/core/migrations/0015_sorting_settings_by_groups.py
> +    for setting in settings_first_screen:
Не очень понял как тут можно просто циклом сделать. Название ключей разное. У first_screen есть приставка main, и не всегда она идет после main. Из идей, это только сделать большой словари со всеми setting_key.
![image](https://user-images.githubusercontent.com/78818362/144745302-dc39c723-bf6d-4345-8dda-00d050efccc0.png)

2021-12-05 13:50 UTC, AntonZelinsky commented on apps/core/models.py
> +    name_group = "EMAIL"
Колин вариант правильный! 
Я обычно проверяю так: добавляю между словами of и смотрю что получилось:
name of group — имя группы
group of name — группа имён
но в данном случае, если убрать of, то всё сломается, так как [group name](https://context.reverso.net/%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%BE%D0%B4/%D0%B0%D0%BD%D0%B3%D0%BB%D0%B8%D0%B9%D1%81%D0%BA%D0%B8%D0%B9-%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9/group+name) общепринятая форма.

Я минут 15 спорил с нативным носителям языка, но так и не смог доказать или добиться правила подтверждающее это.

2021-12-05 13:50 UTC, AntonZelinsky commented on apps/core/admin.py
> +admin.site.register(SettingsFirstScreen, SettingsFirstScreenAdmin)
Может модели админки, стоит регистрировать с [помощью декоратора](https://docs.djangoproject.com/en/3.2/ref/contrib/admin/#the-register-decorator)? Так как моделей очень много, есть шанс пропустить какие-то, да и с декораторами — новый модный способ.

К тому же, так можно не одну, а несколько моделей зарегистрировать для одной админ модели

2021-12-06 22:34 UTC, AntonZelinsky requested changes

2021-12-06 22:34 UTC, AntonZelinsky commented on apps/main/views.py
> +        if main_add_first_screen:
У тебя не последняя версия кода (из дева), так как на главной эту страничку уже переделали.

2021-12-06 22:41 UTC, nkiryanov requested changes
Есть комментарии. Ну и нужно внимательно забрать изменения из develop — этот PR в таком виде сломает БД (не накатятся миграции) + даже если б накатились, то сломали бы эндпоинт главной страницы.

2021-12-06 22:41 UTC, nkiryanov commented on apps/core/admin.py
> +@admin.register(Image)
👍 
Давай добавим это в наш codestyle и везде будем переходить на эту реализацию, м?

2021-12-06 22:41 UTC, nkiryanov commented on apps/core/admin.py
> +    list_display = (
Стыд то какой :)
👍

2021-12-06 22:41 UTC, nkiryanov commented on apps/core/migrations/0005_settings.py
> +            name='Setting',
Тут вроде нельзя так делать. Вернее мы позже будем наводить порядок в миграциях и наверное их вообще пересоздавать с нуля.

Старую миграцию нужно оставить как есть. А создать новую на переменование модели. Чтоб все у кого есть уже модель с Setting**s** тоже переменовали при накатывании новых миграций.

2021-12-06 22:41 UTC, nkiryanov commented on apps/core/migrations/0006_create_settings_objects.py
> +def add_setting(apps, schema_editor):
А вот тут setting**s** было в самый раз. Мы же настройки создаем.
По поводу правок старых миграций написал выше.

2021-12-06 22:41 UTC, nkiryanov commented on apps/main/views.py
> +        main_add_blog = Setting.get_setting("main_add_blog")
Вот тут откатываешь к старой версии кода и main сломается. Не стоит этого делать :)
Забери plz все изменения из develop корректно plz. Может быть даже можно rebase сделать от develop сейчас.

2021-12-08 12:19 UTC, KondratevAD commented
Долго мучился с merge`м этой ветки с develop. Вроде все слил с develop.
Добавил две миграции в core:
0015 - rename модели Setting и добавление моделей SettingEmail и тд.

2021-12-08 14:05 UTC, AntonZelinsky commented on apps/core/models.py
> +class Setting(BaseModel):
Этот файл на 260 строк, самое время разделить его, и вынести хотя бы настройки в отдельный файл
![image](https://user-images.githubusercontent.com/1431279/145221349-0e7c0e04-94f9-45c7-bc0b-57f10e32ea8b.png)

И настройки в админке выглядят в каком-то не нормальном порядке

2021-12-08 15:04 UTC, nkiryanov commented on apps/core/migrations/0015_auto_20211208_1147.py
> +                'verbose_name': 'Настройки первой страницы',
А я поспорю: тоже сначала хотел назвать его как-то по другому, но по тому как он работает + по макету в figma это первая страница.

Это то, что всегда открывается, когда нажимаешь на значок 💚
В обще очень даже первая страница.

Но если будешь настаивать — давай заведем ещё задачку на борде и сделаем следующим PR. Это ведь не относится к разделению настроек на группы.

2021-12-08 15:06 UTC, nkiryanov commented on apps/core/migrations/0014_data_add_missing_main_settings.py
> +        description="На все читки и мастер-классы фестиваля вход свободный по предварительной регистрации.",
Не, это текстовое поле.
Только значение почему-то написал в description (это должен был быть текст), а описание вообще не оформил.

Тоже предлагаю оставить как есть и сам попроавлю в ближайшем PR (на проде уже всё поправлено). Просто не относится к разделению настроек на группы.

2021-12-08 15:07 UTC, nkiryanov commented on apps/info/views/festival.py
> +class FestivalAPIView(RetrieveAPIView):
А вот это проблем: это же не твой код. Это код, который взят из develop.
Давай сделаю rebase ветки?

2021-12-08 15:07 UTC, nkiryanov commented on apps/info/views/festival.py
> +class FestivalYearsAPIView(APIView):
И тоже код из develop, не твой.

2021-12-08 16:46 UTC, AntonZelinsky commented on apps/info/views/festival.py
> +class FestivalYearsAPIView(APIView):
Так, а в чём проблема? Это же явно улучшения?

2021-12-08 16:51 UTC, nkiryanov commented on apps/info/views/festival.py
> +class FestivalYearsAPIView(APIView):
Проблема, что этот код не писался в этом PR.
Это в другом PR делали, который уже слит с develop. Почему пишу так уверенно: потому что сам и писал 😃

2021-12-08 18:15 UTC, AntonZelinsky commented on apps/core/migrations/0015_auto_20211208_1147.py
> +                'verbose_name': 'Настройки первой страницы',
Окей, пусть остаётся

2021-12-08 18:24 UTC, AntonZelinsky commented on apps/info/views/festival.py
> +class FestivalYearsAPIView(APIView):
Мне кажется, что сделали лучше, чем было, но если ты знаешь о чём говоришь, то окей.

2021-12-08 18:25 UTC, AntonZelinsky commented on apps/info/views/festival.py
> +class FestivalYearsAPIView(APIView):
А названия без ViewSet в 100 раз лучше!

2021-12-08 19:05 UTC, nkiryanov commented on apps/info/views/festival.py
> +class FestivalYearsAPIView(APIView):
Слушай, ну я не знаю как ещё объяснить.

Посмотри plz на код в develop.
Посмотри plz вот этот PR
https://github.com/Studio-Yandex-Practicum/Lubimovka_backend/pull/104

Суть в том, что здесь зафиксированы изменения, которые по факту не делались. Соответственно в итоговом проекте будет неправильный автор кода, информация о коммитах будет нарушена.

2021-12-08 19:06 UTC, nkiryanov commented on apps/info/views/festival.py
> +class FestivalYearsAPIView(APIView):
Я на 150% согласен что сделали лучше, потому что сам и делал :)

2021-12-11 16:12 UTC, nkiryanov approved these changes
Апрув.
Только добавь plz в README (в codestyle), что в админка модели регистрируем через декоратор. Чтоб все наши будущие изменения уже с учётом этого решения делать.

2021-12-11 20:08 UTC, elisey approved these changes

2021-12-12 18:04 UTC, AntonZelinsky approved these changes

2021-12-12 18:04 UTC, merged