Feature/library factories
Studio-Yandex-Practicum/Lubimovka_backend pull request #98
Opened 2021-12-02 23:28 UTC by MarselMulyukov

Когда создаёте PR, убедитесь, что:

- [ ] вы проверили обновления в [брифе](https://www.notion.so/00f5d5a6d39e426fa1ea7ab69b694f07)
- [ ] синхронизировали изменения кода с [ER-диаграммой базы данных](https://drive.google.com/file/d/1RCIPaEgaLUSqek3znd38VPCKSzOlmJFy/view) связей моделей
- [ ] тесты все пройдены и нет конфликтов
- [ ] созданы необходимые миграции

Когда ваш PR смержен:

- [ ] если у вас были изменения в API, сообщите об этом команде Фронта, им это важно знать!

2021-12-03 01:37 UTC, evi1ghost requested changes
Есть некоторые замечания по работе фабрик.
filldb - надо соблюсти порядок использования фабрик для корректной работы.

И еще есть желание изменить принцип работы add_play для фабрики авторов (смотри в комментариях).

2021-12-03 01:37 UTC, evi1ghost commented on apps/library/tests/factories.py
> +    # performance = factory.Iterator(Performance.objects.all())
Тут тоже

2021-12-03 01:37 UTC, evi1ghost commented on apps/library/tests/factories.py
> +    project = factory.Iterator(Project.objects.all())
То же замечание, что и по остальным.

2021-12-03 01:37 UTC, evi1ghost commented on apps/library/tests/factories.py
> +    year = factory.LazyFunction(lambda: fake.year())
Тут с `LazyFunction` перебор. Можно проще.

    first_name = factory.Faker("first_name", locale="ru_RU")
    last_name = factory.Faker("last_name", locale="ru_RU")
    birthday = factory.LazyFunction(
        lambda: fake.past_datetime(tzinfo=pytz.UTC)
    )
    city = factory.Faker("city_name", locale="ru_RU")
    phone_number = factory.Faker("phone_number")
    email = factory.Faker("email")
    title = factory.LazyFunction(lambda: fake.word().capitalize())
    year = factory.Faker("year")
    file = factory.LazyAttribute(lambda obj: f"{obj.title}.txt")

2021-12-03 01:37 UTC, evi1ghost commented on apps/core/management/commands/filldb.py
> +            authors = []
Надо соблюсти очередность использования фабрик. Автор, например, при создании через complex_create() попробуется создать пьесу, а для нее нужна программа, которой нет.

P.S.: Ниже в фабриках еще просьба по изменению поведения add_play для фабрики авторов.

2021-12-03 01:37 UTC, evi1ghost commented on apps/core/management/commands/filldb.py
> +                authors.append(AuthorFactory.complex_create())
Давай в этот цикл не будем засовывать фабрики из библиотеки. Он вроде для персон. Лишняя зависимость появляется.
Можно проще: `authors = [AuthorFactory.complex_create() for _ in range(15)]`

2021-12-03 01:37 UTC, evi1ghost commented on apps/core/management/commands/filldb.py
> +                    "других пьес",
Думаю тут нет смысла расписывать зависимые от автора модели, а пьесы лучше создать отдельно.
Я предлагаю создать сначало штук 10 пьес, а после 15 авторов. Тогда с учетом предложенных изменений для фабрики автора (см. ниже) получится, что у нас у некоторых пьес будет несколько авторов, что хорошо для тестирования.

2021-12-03 01:37 UTC, evi1ghost commented on apps/core/management/commands/filldb.py
> +                self, perfomances, "спектаклей, отзывов и медиа отзывов"
Если у нас нет отдельных эндпоинтов для вывода отзывов и медиаотхывов, то предлагаю их не указывать в отчете, т.к. взаимодействие с ними идет через спектакли.

2021-12-04 20:41 UTC, nkiryanov requested changes
Начал ревьювить и подумал что:

1. Для того чтоб хорошо отревьвить фабрики нужно нормально так погрузиться: смотреть не только на код, а для каких моделей фабрики создаем и удачный ли подход
2. Что согласен с комментариями Андрея :)

У меня пока нет возможности хорошо погрузиться, а правки Андрея актуальные + сам написал пару.

Давай более вдумчиво поревьювлю, после того как
1. Подправишь правки Андрея
2. Заодно приведешь код к нашему codestyle (перенос строк, котртежи и прочее)

+ у меня сложилось впечатление (может ошибочное), что используешь некоторые блоки по подобию других, но не всегда оптимально. Просьба оценить что именно не понимаешь в фабриках и разобраться или задавай нам вопросы — объясним. Это позволит писать понятнее + красивее.

2021-12-04 20:41 UTC, nkiryanov commented on apps/library/tests/factories.py
>      name = factory.LazyFunction(
Не призываю исправлять, но зачем случайное значение? Почему бы не итератор? Будет проще, а нам для тестовых данных вполне ок.

2021-12-04 20:41 UTC, nkiryanov commented on apps/library/tests/factories.py
> +        Create a Play object and add it to plays field for Author.
Вообще если уж такие штуки делаем, то они могли бы сильно помочь в тестах (будущих). Мне было удобно иметь две опции добавления связанных обеъектов:
1. Укахать количество сколько связнных объектов добавить. Добавит любые, не больше этого количества
2. Указать точные объекты которые добавить. Тогда буду уверен, какие объекты связан.

Выглядело это примерно так:

```
class RecipeFactory(factory.django.DjangoModelFactory):
    """Rely on User and RecipeTag and Ingredient objects.
    
    Creates recipe with at least one tag and ingredient.
    It supports 'tags__num' and 'ingredients__num' values. If them passed
    creates recipes with that values.
    """

    ...
    
    @factory.post_generation
    def tags(self, create, extracted, **kwargs):
        if not create:
            return

        if extracted:
            tags = extracted
            self.tags.add(*tags)
            return

        at_least = 1
        num = kwargs.get("num", None)
        how_many = num or at_least

        tags_count = RecipeTag.objects.count()
        how_many = min(tags_count, how_many)

        tags = RecipeTag.objects.order_by("?")[:how_many]
        self.tags.add(*tags)
```

2021-12-04 20:41 UTC, nkiryanov commented on apps/library/tests/factories.py
> +        role__name="Ведущий",
поддержу

2021-12-04 20:41 UTC, nkiryanov commented on apps/library/tests/factories.py
> +    name = factory.LazyFunction(lambda: fake.word().capitalize())
А зачем делать называние заглавными символами?

2021-12-04 20:48 UTC, evi1ghost commented on apps/library/tests/factories.py
> +    name = factory.LazyFunction(lambda: fake.word().capitalize())
Для красоты :)

2021-12-04 21:18 UTC, AntonZelinsky reviewed
Захожу в ПР, смотрю 25 коментов и 2 файла, даже прифигел от этого. А тут оказывается файл на 500 строк. Было бы круто, сделать его пакетом, как это сделано в большинстве больших файлов в приложении.

2021-12-14 19:13 UTC, AntonZelinsky approved these changes

2021-12-14 19:13 UTC, AntonZelinsky commented on apps/library/tests/factories/performance.py
> +        if extracted:
Так можно уменьшить схлопнуть if и убрать лишний блок: `if not created or extracted:`

2021-12-14 19:21 UTC, evi1ghost commented on apps/core/management/commands/filldb.py
> +            authors = [AuthorFactory.complex_create() for _ in range(15)]
Тут Марсель применяет мой кастомный метод создания авторов с заполнением всех полей - https://github.com/Studio-Yandex-Practicum/Lubimovka_backend/blob/3f4c977a42825a5af91ea34c8c68a7c37d647f99/apps/library/tests/factories.py#L195    
Create_batch создаст авторов, но не заполнит необязательные поля, т.к. завязан на стандартном методе create.

2021-12-14 19:25 UTC, nkiryanov commented on apps/core/management/commands/filldb.py
> +            authors = [AuthorFactory.complex_create() for _ in range(15)]
Давайте эту задачу заведем на борду.
Например для фабрик "articles" тоже написан `complex_create`, но с поддержкой create_batch() и тут логично так же сделать. Но можно в след. PR

2021-12-15 19:52 UTC, evi1ghost approved these changes

2021-12-15 19:53 UTC, merged